### ISSUE TITLE
An Interactive Introduction to Secret Sharing

### ISSUE THREAD

**Issue by nkohen** [TABConf/6.tabconf.com#101]
# Description
### What is this workshop about? Provide as many details as possible. 
Secret sharing (aka secret splitting) is an interactive process in which a group of parties hold parts (aka shards, aka shares) of a secret and can subsequently agree to reconstruct (or else use without reconstructing) the secret should enough of the parties agree. This cryptographic primitive sees myriad of uses in Bitcoin from cold storage solutions and hot wallet solutions to threshold signatures (MuSig and FROST and such) and more!

In this pencil-and-paper (and maybe calculator) workshop, I will ask groups a series of questions and we will discover a couple rudimentary secret sharing schemes, including some simple examples of the famous Shamir Secret Sharing. We will then construct an example of a Multi-Party Computation (MPC) using our secret sharing to solve a problem. If time permits, we'll investigate Shamir Secret Sharing in general.

### What would an attendee learn from this workshop?
An attendee will learn what secret sharing is, a couple examples of secret sharing schemes, including Shamir Secret Sharing which is used in most modern multi-party computations (like MuSig and FROST), and will get a sense for how secret sharing can be used as part of Multi-Party Computations.

### Is there anything attendees should read up on before they attend this talk?
Nope! Some amount of rigor has been removed in order to make this workshop accessible to all!

### Is there anything attendees should set up before the workshop?
Nope! This will be a pencil-and-paper workshop.

### Relevant Links
https://en.wikipedia.org/wiki/Secret_sharing (You don't need to understand anything on this page, just figured I'd leave it here in case it helps people get interested).

 
# Level of difficulty 
 
Beginner (If you have seen the mathematical details of secret sharing before, this workshop is likely not for you)
# About the Speaker
I previously worked at Suredbits and was a contributor to the bitcoin-s library and the DLC specifications. These days I am pursuing a PhD in Mathematics at Indiana University focusing on Combinatorics. I also still do some Bitcoin consulting and teach math to high schoolers using Inquiry Based Learning during the summers at MathILy.

### Social Links
Github: https://github.com/nkohen
Twitter: https://twitter.com/nadav_kohen

# Workshop Details
### Length of workshop
1-2 Hours (2 hours means we get to cover everything, 1 hour means some things will be abridged, I'm open to having a time slot of any length in this range). 
### Preferred Day/Time Slot 
None.

**Comment by iglesiasbrandon** [comment]
thank you for conducting this workshop!
