### ISSUE TITLE
A Combinatorial Game Theory Adventure

### ISSUE THREAD

**Issue by nkohen** [TABConf/6.tabconf.com#102]
# Description
### What is this workshop about? Provide as many details as possible. 
Say that a rook is placed somewhere on a chess board, and you and a friend (or enemy) take turns moving it either down or to the left. If you wish to be the one to put the rook in the bottom-left corner, how can you ensure victory? What if there are multiple rooks and one can be moved each turn and you wish to be the one to place the last rook in the corner? In this interactive workshop, we will play and eventually solve a series of games, including this one, which will lead us to discovering and proving a big result from Combinatorial Game Theory!

This workshop is an introduction to the mathematical theory of combinatorial games, which was what got me into math! This topic is not, strictly speaking, very relevant to Bitcoin, but of course some perspectives one can gain from studying this field are certainly relevant to iteratively constructed Bitcoin contracts enforced by transaction trees. That being said, this workshop will not really be applicable to Bitcoin and is rather intended as a fun and nerdy brain warm-up for conference attendees.

### What would an attendee learn from this workshop?
An attendee would discover how to, in principle, play any impartial combinatorial game perfectly! I hope that this workshop also serves as a gentle invitation to new mathematical ways of thinking.

### Is there anything attendees should read up on before they attend this talk?
Nope! I will be assuming participants have no mathematical background.

### Is there anything attendees should set up before the workshop?
Nope! This workshop will be pencil-and-paper (and maybe chess board).

### Relevant Links
https://en.wikipedia.org/wiki/Combinatorial_game_theory

 
# Level of difficulty 
 
Beginner (Please note however, that if you have a mathematical background but aren't specifically knowledgable about combinatorial game theory, then this will still be an appropriate and fun workshop to attend!)

# About the Speaker
### Social Links
Github: https://github.com/nkohen
Twitter: https://twitter.com/nadav_kohen

# Workshop Details
### Length of workshop
1-2 Hours (2 hours means we get to cover everything, 1 hour means some things will be abridged, I'm open to having a time slot of any length in this range).

### Preferred Day/Time Slot 
None.

**Comment by asherp** [comment]
Hey, this sounds really cool! The NextGen village is a space for games and tutorials that teach the concepts in and around Bitcoin. We'd be glad to have you. Also, you may want to chat with Scott Lindberg if you want to take the idea further.

**Comment by iglesiasbrandon** [comment]
thank you for conducting this workshop!
