### ISSUE TITLE
Not your keys, not your name. Introducing a decentralized, cypherpunk-centric naming protocol built on Bitcoin.

### ISSUE THREAD

**Issue by ca98am79** [TABConf/6.tabconf.com#105]
# Description

Public Key Infrastructure (PKI) is a critical component of internet security, enabling secure communication and authentication between parties. However, traditional PKI systems often rely on centralized authorities, which can be vulnerable to attacks, censorship, and single points of failure. This has led to a growing interest in decentralized PKI solutions, particularly those built on blockchain technology. Over the past decade, various decentralized naming protocols have emerged to address this need. These innovations fall short of delivering the security attributes inherent to a robust Proof-of-Work blockchain such as Bitcoin. Spaces Protocol addresses these problems by creating a decentralized naming system built on the Bitcoin network, providing a more secure, private, and censorship-resistant solution beyond the control of centralized third parties. 

### What is this talk about? Give us as many details as possible.

Neutral money like bitcoin preserves economic liberty. It respects individual freedom. It silently advocates for property rights. Whether you’re an individual or a business, it gives you complete empowerment over your decisions about production, investment, and consumption without the threat of censorship, confiscation, or debasement. Without the involvement of governments, this encourages self-reliance and contributes to social harmony. Bitcoin, in other words, is essential for maintaining a free, prosperous, and just society. The same is true for naming. If anything is as important to society as money, it’s naming. Names are needed for almost everything and individuals & businesses should be able to own their name without it being in the control of a centralized, third party.
Names and money both have historically relied on trust for their efficacy, but just like bitcoin as money ushered in an era of trustlessness, the same must be accomplished for names.
This talk will focus on the current, centralized state of naming, touch on the previous attempts to solve this issue (e.g namecoin) and why they have fallen short, while unpacking a novel approach (Spaces Protocol) that seeks to solve this critical need once and for all. 

What is needed is a truly decentralized, permissionless naming system built on Bitcoin, free from third party certificate authorities, that empowers users with control and privacy over their online identities. And in contrast to attempts that came before, naming needs to be done in a cypherpunk-centric way without a new blockchain, or modifications to Bitcoin itself, without a new token, foundation, or premine. Users must be entirely in control of how they register, manage, and transfer names.

### What would an attendee learn from this talk? 

They would learn about the current state of naming, how it works, the centralizing forces at play, and examples of censorship/property confiscation these gatekeepers are guilty of. Attendees will learn the history of other protocols/projects that have attempted to solve this issue and why they have fallen short. Lastly, they will learn a novel approach to bringing decentralized naming to Bitcoin. 

### Is there anything folks should read up on before they attend this talk? 

No, folks can come into this talk blind. 

### Relevant Links
- https://github.com/spacesprotocol

# About the Speaker
[Mike Carson](https://twitter.com/ca98am79) is the founder of [Spaces Protocol](https://spacesprotocol.org/), a decentralized naming system built on Bitcoin that empowers users with control and privacy over their online identities.  Prior to founding Spaces Protocol, Carson founded and successfully exited Park.io, a domain name backordering service, and co-founded WizeHive, which grew to $10 million in revenue before being acquired by a private equity firm. With a robust background in technology, Carson has acquired and managed three ICANN-accredited domain registrars and has worked with various ccTLD registries, including facilitating .ai's transition to EPP. He has previously contributed core code to ENS and Handshake, and, having been involved in the Bitcoin community since 2013, managed one of the first 50 nodes on the Lightning network and made the third purchase ever for physical goods on the network. Carson studied computer science at the College of Wooster and the University of Minnesota and has been active with technology for the last 15 years both as a developer and entrepreneur.

### Social Links
Github: https://github.com/ca98am79 
Twitter: https://cypherpunk.com 
Website: https://spacesprotocol.org

**Comment by andrewlunde** [comment]
I'm willing to support Mike in this topics with a demonstration of my implementation of the Spaces Protocol on StartOS.  I have working s9pk files for Start9 Pure(x86).  Also we may want to engage Matt Hill of Start9 from a performing spaces related activity secretly perspective.  I have contact with him if you want to go in this direction.

**Comment by andrewlunde** [comment]
Spoke with Mike yesterday and he's planning on making it to TABConf.  I think his session will be of interest to the crowd.
