### ISSUE TITLE
The Bitaxe: open source mining table

### ISSUE THREAD

**Issue by skot** [TABConf/6.tabconf.com#108]
<img width="1053" alt="image" src="https://github.com/user-attachments/assets/95356b65-c487-49b1-bf91-433bb1bffe11">

## Project
[The Bitaxe](https://bitaxe.org) is a fully open source permissionless Bitcoin mining project. It's a small miner that you can buy from a global network of manufacturers and sellers or build yourself and very easily run at home. We hope to get more people into this most excellent part of Bitcoin to properly decentralize it.

#### Description:
On a suggestion from @miketwenty1 I think it would be cool to have a table with some Bitaxe setup and running. They could be mining to a local node to show off top-to-bottom self sovereign mining in action. I will be at the table to answer any questions about the project, and maybe recruit some new contributors!

#### Link(s) to source Repos:
[Bitaxe HW Repo](https://github.com/skot/bitaxe)
[Bitaxe FW Repo](https://github.com/skot/esp-miner)

#### What would an attendee learn from visiting this projects table at Builder Days?
- What is a Bitaxe?
- Why is open source, decentralized, permissionless mining important?
- How was the Bitaxe made? How does it work?
- I'm into _x_, how can I get involved with open source mining?

#### What should people read up on before finding the table at Builder Day?
- Best thing would be to checkout [bitaxe.org](https://bitaxe.org) and look through the hardware and/or firmware GitHub repos. 
- [Open Source Miners United Discord](https://discord.gg/osmu): We have a very active community on Discord. Reading here would be a great way to get involved.

#### Schedule:
- Both days, all day. (I can talk about Bitaxe forever)

#### Builder Table Staff: 
- Skot - Bitaxe instigator
- Hopefully some more! Are you a Bitaxer and want to help out here?

#### Space: 
- Table, AC power and ideally a decent wifi connection.

**Comment by aassoiants** [comment]
Will there be demo BitAxes or will participants need to bring their own?

**Comment by iglesiasbrandon** [comment]
Thank you for hosting this!
