### ISSUE TITLE
An Exposition of Pathfinding Strategies Within Lightning Network Clients

### ISSUE THREAD

**Issue by sindurasaraswathi** [TABConf/6.tabconf.com#109]
# Description
### What is this talk about? Give us as many details as possible. 
Due to a source-based routing of payments, different pathfinding strategies are used in the Lightning Network in practice, trading off different objectives for each other such as payment reliability and routing fees. In this talk, we will:

* Explore the differences within pathfinding strategies used by prominent Lightning Network node implementations including LND, CLN, LDK and Eclair, with a focus on how their distinct channel weight functions influence shortest path algorithms.
* Evaluate pathfinding strategies through comparative analysis and simulations, assessing their efficacy across metrics such as success rate, fees, path length, and timelock. 
* Investigate the impact of Lightning node connectivity levels on routing efficiency. 
* Present our experimental results and analysis. 

By leveraging insights gained from this study, future developments in weight functions can be directed towards enhancing pathfinding efficacy. We expect that integrating the findings into the design of sophisticated weight functions for routing could yield substantial improvements.

### What would an attendee learn from this talk?
* Attendees will learn about the strengths and weaknesses of each Lightning Network client variant, with a focus on how the construction of weight functions and the strategic selection of design elements significantly impact performance. 
* The talk will provide a comparative analysis of the single-path pathfinding algorithms used by LND, CLN, LDK, and Eclair. 
* Attendees will gain insights into potential future improvements for pathfinding strategies and algorithms within the Lightning Network, informed by the empirical performance and findings of the analysis.

### Is there anything folks should read up on before they attend this talk?
For those unfamiliar with the Lightning Network, reading the Lightning Network whitepaper or any online article that explains the network, including the basics of pathfinding, would be helpful in understanding the key terminologies that will be referenced during the talk.

https://lightning.network/lightning-network-paper.pdf
https://github.com/lnbook/lnbook
https://ellemouton.com/posts/onion-routing-prelims/
### Relevant Links

# About the Speaker
Sindura Saraswathi is a PhD student at the University of North Carolina at Charlotte, focusing her research on the Bitcoin Lightning Network. Her work revolves around pathfinding algorithms within the Lightning Network, with a current emphasis on developing a multipath pathfinding algorithm. She recently interned at Bitcoin Layers, where she contributed to Bitcoin Layer 2 risk analysis and opcode reviews.

### Social Links
Github: https://github.com/sindurasaraswathi
Twitter: https://x.com/btcsindura
LinkedIn: https://www.linkedin.com/in/sindurasaraswathi/ 

# Talk Details
### Length of Talk
25 Minutes

**Comment by btsea** [comment]
Hi @sindurasaraswathi we would be willing to host this talk in the Socratic Village. Are you still interested/able to come to TABConf?

**Comment by sindurasaraswathi** [comment]
Hi @btsea, Amazing! Yes, I will be attending TABConf for all days and would love to participate in the Socratic Village. Looking forward to it!

**Comment by btsea** [comment]
Okay great! We have added you to our village. We are still working out the schedule and will update this issue once we have an exact time slot for you.

**Comment by iglesiasbrandon** [comment]
thank you for conducting this talk!
