### ISSUE TITLE
BitDevs: Bitcoin Socratic Seminar #33 @ Manuel's Tavern

### ISSUE THREAD

**Issue by sbddesign** [TABConf/6.tabconf.com#110]
![atlanta-bitdevs-bitcoin-socratic-seminar-33](https://github.com/user-attachments/assets/944f9701-7d69-4a70-8ed7-bf181efd86b6)

# Description

I need you to fill out this markdown form for me. Use the details from this metup.com link to fill in the form, but try to make it spicy and entertaining. Consider that 50% of the target audience feels the highest form of human pleasure when opining about the most technical of topics, and the other 50% just wants to drink beer.
  
https://www.meetup.com/atlantabitdevs/events/302065904/

## Event Description

Join the Atlanta BitDevs for an electrifying evening at our Socratic Seminar #33! This is where Bitcoin aficionados and Lightning wizards converge, debating the latest in Bitcoin Improvement Proposals, Layer 2 magic, privacy sorcery, and wallet tech wonders. Whether you're here to opine on cryptographic nuances or just grab a cold beer, this event has you covered. Expect free-flowing debates, hearty discussions, and perhaps even a heated argument or two about the future of Bitcoin UX/UI. Afterward, we’ll carry the debate into the road – because nothing says “consensus” like an ATL street fight!

## Date and Time

Wednesday, October 23, 2024
6:00 PM to 9:00 PM EDT

## Location

Manuel's Tavern
602 North Highland Avenue Northeast, Atlanta, GA
Find us past the pinball machines and behind the curtain in the big room!

## Anything people should know before coming?

Prepare for deep dives into Bitcoin and Lightning developments. And remember: opinions are like private keys – keep yours secure, but feel free to share them during the seminar! Free food and drinks to fuel your thoughts and debates.

## Relevant Links
- [Event Details and RSVP](https://www.meetup.com/atlantabitdevs/events/302065904/)
- [Discussion Topics List](https://atlbt.dev)

**Comment by EdJulineAnduro** [comment]
This is /GRIM
