### ISSUE TITLE
Bitcoin Pumpkin Carving Competition

### ISSUE THREAD

**Issue by lizmparrish** [TABConf/6.tabconf.com#113]
# Description
### What is this workshop about? Provide as many details as possible.  
A fun way to carve your favorite bitcoin designs into pumpkins. Be as creative and spooky as you want! For all ages and there will be a competition for the best pumpkin. Pumpkins will be displayed at HODLween the following night unless you want to take yours home. Feel free to bring your own pumpkin! There will be pumpkins provided on a first come, first serve basis. 

Can carve pumpkins all day. If you want to be included in the competition, be sure to leave your contact info near your pumpkin. Pumpkins must be complete by 4:00PM. Winners will be announced at 4:30PM. 

Winnings: 
1. Cold card + Satoshi hat + Magazine + HODLween Mug + 100,000 sats
2. Hat +  Bitcoin magazine + HODLween Mug + 50,000 sats
3. Hat +  Bitcoin magazine + HODLween Mug + 25,000 sats

![369418469-7b8ea6ee-4ccb-4c48-adee-82d09b670ddb](https://github.com/user-attachments/assets/5478e35d-7932-4add-a50b-d99b0fb9038b)

### What would an attendee learn from this workshop? 
Learn how to combine bitcoin ideas with art! Network with other individuals and see what creativity you can come up with!  
### Is there anything attendees should read up on before they attend this talk? 
Just be prepared with your bitcoin design!
### Is there anything attendees should set up before the workshop? 
A limited amount of pumpkins and carving materials will be provided. Feel free to bring your own pumpkin to guarantee a carving.
### Relevant Links

 
# Level of difficulty  
Beginner
 
# About the Speaker
Bitcoin Charlotte is a local meetup in Charlotte that has been hosting HODLween for 4 years now. The night prior to HODLween it is a tradition to carve pumpkins and then have them displayed at HODLween. We believe you don't need permission to be your own bank and you don't need permission to have fun!
### Social Links
[HODLWEEN](https://hodlween.party)

# Workshop Details
### Length of workshop
2 hrs
### Preferred Day/Time Slot 
Friday, Oct 25th
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by lizmparrish** [comment]
We need about 2 hours for this workshop. Will there be a specific time slot for Friday?

**Comment by iglesiasbrandon** [comment]
Thank you for hosting this!
