### ISSUE TITLE
Testnet Bitcoin Giveaway Extravaganza! (also interactive sidechain demo)

### ISSUE THREAD

**Issue by theblackmarble** [TABConf/6.tabconf.com#114]
# Description

Free Bitcoin Testnet 3 & 4 faucets! (also sidechains)

|Network| Amount|
| -------- | ------- |
|Testnet4|50 BTC!!!!|
|Testnet3|.01 BTC|
|Testnet Coordinate|.01 cBTC|
|Testnet Alys|.01 ALYS|

The attendee will learn how to interact with multiple 2-way pegged sidechains active currently against Bitcoin Testnet3.  They will also get a ton of testnet bitcoin.
 
# Reading material
Coordinate Whitepaper

# What to bring

 Laptop

# Relevant Links

 anduro.io

# Level of difficulty 

 Intermediate

# About the Speakers

### PortlandHODL

 Bitcoin Enthusiast / Educator
 Slipstream visionary @ Mara
 Github: [russeree](https://github.com/russeree)
 Twitter: [Portland.HODL](https://x.com/portlandhodl)

### Michael B. Casey

 Director of Engineering at Mara
 Chief Architect of Anduro
 Head Lifeguard of Mara Pool
 Github: @theblackmarble
 Twitter @theblackmarble

### Nicholas Vincent

 Alys Lead @ Anduro

# Workshop Details
2 hours
### Preferred Day/Time Slot 
Any Day
10-12 or 1-3

**Comment by iglesiasbrandon** [comment]
Thank you for conducting this workshop!
