### ISSUE TITLE
Build a compact block filter wallet with BDK

### ISSUE THREAD

**Issue by rustaceanrob** [TABConf/6.tabconf.com#116]
# Description
### What is this workshop about? Provide as many details as possible. 

I am working on a [compact block filter client](https://github.com/rustaceanrob/kyoto) with a [Bitcoin Dev Kit integration](https://github.com/ValuedMammal/bdk-kyoto) and would like to demonstrate how users may integrate their existing BDK wallets with CBF. Although the workshop and core libraries are in Rust, I am also working on [a branch of BDK-FFI](https://github.com/rustaceanrob/bdk-ffi/tree/kyoto-bindings) to add the CBF client to the native Swift, Kotlin, and Python language bindings.

### What would an attendee learn from this workshop?

The user would learn how to build a _watch only_ wallet using BDK and compact block filters. Existing BDK users would get to try a new approach to wallet syncing, and users interested in BDK will learn how to make their first wallet.

### Is there anything attendees should read up on before they attend this talk?

Attendees should be familiar with Rust or other statically-typed programming languages like C++, Swift, Kotlin, etc.

Optionally, users may want to read BIP157 and BIP158 for a strong understanding of the motivation for compact block filters, although this is certainly not required.

### Is there anything attendees should set up before the workshop?

Users should have Rust and Git installed.

### Relevant Links

Libraries Used:

- [Kyoto, compact block filter client implementation](https://github.com/rustaceanrob/kyoto)
- [BDK-Kyoto, integration of Kyoto with BDK](https://github.com/ValuedMammal/bdk-kyoto)
- [BDK Wallet](https://github.com/bitcoindevkit/bdk)
- [Tokio](https://docs.rs/tokio/latest/tokio/)

Optional, but certainly not required:

- [BDK documentation](https://docs.rs/bdk_wallet/latest/bdk_wallet/)
- [Blog on building compact block filters from scratch](https://ellemouton.com/posts/bip158/)
- [tokio documentation](https://docs.rs/tokio/latest/tokio/)

 
# Level of difficulty 

Advanced

 
# About the Speaker

- Got into FOSS with Chaincode Lab's _Start Your Career in FOSS_ program
- Grantee of the BDK Foundation, OpenSats to work on compact block filters and contribute to the BDK ecosystem. 

### Social Links
[Github](https://github.com/rustaceanrob)
Twitter
Website

# Workshop Details
### Length of workshop
~ 1 hour
### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

Anything works

**Comment by notmandatory** [comment]
ACK from me on this one. the Kyoto CBF node is a super interesting project and I'd love to see more folks taking a look at it and learning out to use it with BDK.

**Comment by iglesiasbrandon** [comment]
Thank you for hosting this!
