### ISSUE TITLE
Build a DLC wallet and bet on the presidential election

### ISSUE THREAD

**Issue by matthewjablack** [TABConf/6.tabconf.com#117]
# Description

[Atomic Finance](https://github.com/orgs/AtomicFinance) has been developing the [Bitcoin Abstraction Layer](https://github.com/AtomicFinance/bitcoin-abstraction-layer) (BAL), the only JS library for Discreet Log Contracts (DLCs). DLCs enable the creation of Bitcoin oracle contracts, which can be used for bets, futures, options contracts, and more.

In this workshop, attendees will learn how to create a DLC wallet and interact with DLCs using BAL. This intermediate-level workshop will cover the following topics:

1. **Introduction to DLCs**: Understand the basics of Discreet Log Contracts and their use cases.
2. **Creating a DLC Wallet using BAL**: Step-by-step guide to setting up a DLC wallet.
3. **Creating Oracle Announcements and Attestations**: Learn how to create and manage oracle announcements and attestations.
4. **Entering and Exiting a DLC**: Practical demonstration of entering into and exiting a DLC.

### What would an attendee learn from this workshop?
Attendees will gain hands-on experience with BAL and learn how to:
- Set up and manage a DLC wallet.
- Create and handle oracle announcements and attestations.
- Enter into and exit from DLCs.

### Is there anything attendees should read up on before they attend this talk?
Attendees are encouraged to read the [Introduction to DLCs](https://github.com/discreetlogcontracts/dlcspecs/blob/master/Introduction.md) to familiarize themselves with the basic concepts.

### Is there anything attendees should set up before the workshop?
Attendees should have Node.js installed on their machines. It would also be beneficial to clone the [Bitcoin Abstraction Layer](https://github.com/AtomicFinance/bitcoin-abstraction-layer) repository and follow the setup instructions in the README.

### Relevant Links
- [Bitcoin Abstraction Layer](https://github.com/AtomicFinance/bitcoin-abstraction-layer)
- [DLC Specification](https://github.com/discreetlogcontracts/dlcspecs)

# Level of difficulty
Intermediate. Attendees should have general web development skills and some experience with JavaScript (both browser and Node.js).

# About the Speaker
Matt is the Co-founder of Atomic Finance.

### Social Links
- **GitHub**: [@matthewjablack](https://github.com/matthewjablack)
- **Twitter**: [@matthewjablack](https://twitter.com/matthewjablack)

# Workshop Details
### Length of workshop
1-1.5 hours

### Preferred Day/Time Slot
Any time works.

**Comment by iglesiasbrandon** [comment]
thank you for conducting this!
