### ISSUE TITLE
DLCs, Oracles, and Lava Loans

### ISSUE THREAD

**Issue by shehzanmaredia** [TABConf/6.tabconf.com#118]
# Description
### What is this talk about? Give us as many details as possible. 
This talk will cover the basic concepts behind DLCs, how they work, why they are useful, the advantages of DLCs vs smart contracts on Ethereum, and the limitations of DLCs. It will also discuss the oracles, how DLC oracles are different than other oracle implementations, the tradeoffs, and the privacy characteristics behind DLC oracles. The talk will end by explaining a use-case for DLCs: Lava Loans. 
 
### What would an attendee learn from this talk?
The basics behind DLCs, oracles, reasoning about different ways to do smart contracts, and how a DLC-based protocol works.

### Is there anything folks should read up on before they attend this talk?
https://github.com/lava-xyz/loans-paper/blob/main/loans_v2.pdf
https://github.com/discreetlogcontracts/dlcspecs

### Relevant Links
Above

# About the Speaker
### Social Links
Shehzan's Personal Twitter: https://x.com/MarediaShehzan

# Talk Details
### Length of Talk
30m
### Preferred Day/Time Slot 
Flexible

**Comment by iglesiasbrandon** [comment]
Hey @andrewlunde, this seems like it could be a cool DLC workshop.
Are you open to converting this talk to a workshop instead?

**Comment by btsea** [comment]
Hey @shehzanmaredia are you still planning to come to the conference? We are putting together a DLC panel in the Socratic Village and would love your participation if you are interested. I can share more info if so.

**Comment by iglesiasbrandon** [comment]
Thank you for hosting this!
