### ISSUE TITLE
State of the Ark

### ISSUE THREAD

**Issue by ErikDeSmedt** [TABConf/6.tabconf.com#119]
# Description
### What is this talk about? Give us as many details as possible. 

The talk will be titled: State of the Ark

Last year @stevenroose gave a great talk with the same title.
This year, he can't join Tabconf so I'd like to take his place.

### What would an attendee learn from this talk?

I'll explain the Ark-protocol works and what the benefits are for using it.
I will also give an update on recent developments and how to use them.

### Is there anything folks should read up on before they attend this talk?

No, everyone with a understanding of bitcoin should be able to understand the talk.

### Relevant Links

# About the Speaker

I'm Erik De Smedt and work on Ark.
Before that, I worked at Blockstream where I contributed to Greenlight.

### Social Links
Github: https://github.com/ErikDeSmedt/
Codeberg: https://codeberg.org/erikdesmedt
Twitter: https://x.com/erikdesmedt/

# Talk Details
### Length of Talk
I think 45 minutes + 15 minutes for questions would be ideal. But I'm flexible on timings.

### Preferred Day/Time Slot

Anything should work

**Comment by btsea** [comment]
Hey @ErikDeSmedt! While we don't have space for this talk in the Socratic Village, would you be interested in participating in a Socratic Panel that includes discussion about Ark? Here are the details, please let me know: https://github.com/TABConf/6.tabconf.com/issues/152

I can share some more details with you if you'd like to join. We'd be very grateful for your participation. 

Thanks!

**Comment by ErikDeSmedt** [comment]
I'd be happy to participate in the panel

PS: I'd could also convert the talk into a workshop called "Make your first Ark payment" if that fits the schedule better

**Comment by btsea** [comment]
Amazing, thanks so much for your participation @ErikDeSmedt. I'm really grateful. I will share some more details about the panel in the issue in the coming days. 

As for converting this to a workshop, please refer to @iglesiasbrandon and @miketwenty1 for that.

**Comment by btsea** [comment]
Hey @ErikDeSmedt. We found a 40 minute slot between 3:10PM - 4:10PM on the 3rd day to fit this in. If that works, please let me know.

**Comment by ErikDeSmedt** [comment]
> Hey @ErikDeSmedt. We found a 40 minute slot between 3:10PM - 4:10PM on the 3rd day to fit this in. If that works, please let me know.

That works for me

**Comment by ErikDeSmedt** [comment]
@btsea : It is a bit unclear on what format I should go for?

Will it be a socratic seminar or a workshop?

**Comment by iglesiasbrandon** [comment]
thank you for conducting this talk!
