### ISSUE TITLE
Bitcoin Changes - Soft Fork History and Theory

### ISSUE THREAD

**Issue by miketwenty1** [TABConf/6.tabconf.com#120]
# Description
### What is this talk about?
- There is a lot of talking new softforks that are needed to enable sidechains. 
- There's the great restoration project and many other proposals.
- How have changes in Bitcoin evolved over time?
- What will changes in Bitcoin look like going forward?
- Who wants ossification and what does that mean?
- How can we relate Bitcoin to other protocols and technologies and what can we learn from them?

# Looking for a Speaker:
I'm looking for a qualified speaker likely someone who has done deep research with forks and bitcoin consensus. I'd prefer this person to be someone prominent either with their current or past work and contributions. Perhaps even someone who is currently vehemently opposed to ossification and wants specific softforks now, or someone passionately pro ossification and what bitcoin needs to get there.

**Comment by psztorc** [comment]
I can do this one if you want.

First -- I have a new way of doing soft forks which I think is vastly superior to the current method(s) -- the "Core Untouched Soft Fork" or CUSF. There is a site here: https://bip300cusf.com/ with code for Bip300 and OP CAT. There is also a paper here: https://bip300cusf.com/cusf.pdf

Second, I have written extensively about forks over the years -- in 2016 https://www.truthcoin.info/blog/protocol-upgrade-terminology/ -- https://www.truthcoin.info/blog/forks-and-splits/ -- I also presented on Soft Forks and Governance for MIT expo last year -- https://www.drivechain.info/media/slides/mit-2023.pdf -- and the Soft Fork panel with Jeremy Rubin on open source stage at the big miami conference.

I would probably do it more along the lines of "Soft Forks - past present future", along the MIT talk, plus my new CUSF content.

**Comment by miketwenty1** [comment]
@psztorc we are going to make you the speaker for this topic.

**Comment by iglesiasbrandon** [comment]
thank you for conducting this talk!
