### ISSUE TITLE
The Future is Splice

### ISSUE THREAD

**Issue by AAtlasBTC** [TABConf/6.tabconf.com#121]
# Description

Splicing is a cutting edge new development coming the Lightning network which makes it easier to manage a node, combine transactions, rebalance channels, etc.

But actually doing a Splice can be difficult if you’re not a developer. Enter “Splice Script”! This new script makes splices fast, easy, and error free. Learning to use it can help you to combine transactions while increasing privacy and decreasing fees. Come learn about this new script language by the guy that wrote the Splice Script itself and the creator of splicing, Dusty Daemon.

### What is this talk about? Give us as many details as possible. 

This talk is about the new release of the Splice Script, which makes using lightning and lightning node running appreciably safer, easier, and more efficient.

### What would an attendee learn from this talk?

Attendees will learn how to use Splice Script to change their relationship with bitcoin transactions, revolutionize their lightning payments, and possibly get a girlfriend (or boyfriend)(based on preference).

### Is there anything folks should read up on before they attend this talk?

The bitcoin white paper.

### Relevant Links

lightningsplice.com

# About the Speaker

Dusty Daemon is an independent lightning protocol developer and the creator of splicing and Splice Script.  Dusty is an avid support of OP_CODESEPARATOR.  Dusty enjoys sailing and long walks on the blockchain.

### Social Links
Github: @ddustin
Twitter: @Dusty_Daemon
Website: lightningsplice.com

# Talk Details
### Length of Talk
45 minutes
### Preferred Day/Time Slot 
Not the morning please. Afternoon highly preferred.
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by AAtlasBTC** [comment]
Hi @iglesiasbrandon and @miketwenty1 
Please note that Lighting Dev @ddustin would be giving this speech, not me @AAtlasBTC

**Comment by iglesiasbrandon** [comment]
ok, this issue has not been accepted yet but if it does i will assign ddustin.

**Comment by ddustin** [comment]
> ok, this issue has not been accepted yet but if it does i will assign ddustin. 

@iglesiasbrandon Could you please assign this to 12pm-1pm on Day 4 to Workshop Room 1?

Thanks 🙏
