### ISSUE TITLE
Let's Analyze Tidwell's Chess

### ISSUE THREAD

**Issue by ddustin** [TABConf/6.tabconf.com#122]
# Description
### What is this workshop about? 

Let's go through Tidwell's public chess game and see what his strengths and weaknesses are. We'll use chess computers and various statistical analysis tools and techniques to see how we can best beat him at chess.

### What would an attendee learn from this workshop?

1) You're going to learn how Tidwell plays chess -- both what he does right and what his weaknesses are.

2) You will learn how to beat Tidwell at chess

### Is there anything attendees should read up on before they attend this talk?

Understanding of the rules of chess is critical and being aware of some basic chess strategy will be helpful.

### Is there anything attendees should set up before the workshop?

A chess.com account so you can follow along. A free account will work but a premium account will give you access to more tools.

### Relevant Links

Chess.com

# Level of difficulty 

Intermediate chess skills

# About the Speaker

Chess adversary of Tidwell who would like to beat him at chess.

### Social Links

Twitter: @dusty_daemon

# Workshop Details
### Length of workshop
30+ minutes

### Preferred Day/Time Slot 
Not the morning -- afternoon preferred

**Comment by oprey** [comment]
R* chess?

**Comment by miketwenty1** [comment]
lol @ddustin this actually got accepted.. is this fr?
