### ISSUE TITLE
The Ethereumization of Bitcoin

### ISSUE THREAD

**Issue by adiabat** [TABConf/6.tabconf.com#123]
### The Ethereumization of Bitcoin
or
#### Opcodes, opcodes, everywhere, but not a node to sync

# Description

### What is this talk about? Give us as many details as possible. 

Is Bitcoin starting to feel a bit like Ethereum?  NFTs, BRC-20, L2s, rollups, MEV... hold on, this is a **Bitcoin** conference, right?

This talk will focus on the different scaling solutions on Ethereum and Bitcoin -- payment channels, L2s, rollups -- and look at some of the similarities and differences.  For example, there's a lot of talk in Bitcoin about OP_CAT, and how it can enable powerful and useful new things in Bitcoin.  From the start, Ethereum has had not just OP_CAT*, but pretty much any opcode you could want, so if we're thinking about what people could do with new opcodes, let's look at what people have done on Ethereum first!

(Spoiler: I think replicating the Ethereum L2 ecosystem is something Bitcoin should try to avoid.)

(Note: I understand that Tabconf is a Bitcoin conference, and I do not intend to promote Ethereum or any L2s, tokens, etc.  But I also don't want to give an "anti-eth" talk, which would probably just be preaching to the choir and not useful at Tabconf.)

(Also I am not a disinterested party here, and I'm probably biased towards things I've worked on like LN / utreexo, and so maybe against other competing ideas?  I try to to be pretty neutral though and mostly just want lots of people to be able to use Bitcoin securely and privately.)

(*Actually there's no OP_CAT, but there's left shift and OR, which together do the same thing.  Left shift has been in since 2018's constantinople hard fork.  TIL!)
### What would an attendee learn from this talk?

How rollups / L2s work in practice today on Ethereum, compared with L2s and scaling solutions on Bitcoin (LN, Rollups, Payment Channels).

Accumulator designs for scaling, Utreexo and "Stateless clients"

Economic vs Technical limitations on scaling

What fundamental limits L2 style scaling solutions face, regardless of opcodes and transaction design.

The power balance between L1s, L2s, developers, companies, and users.

And so much more!

### Is there anything folks should read up on before they attend this talk?

Probably not - I'll read a bunch of ethereum code, papers, and talk to people working on this stuff so you don't have to!

### Relevant Links

https://bitcoinops.org/en/topics/op_cat/
https://eprint.iacr.org/2022/1478

# About the Speaker
Tadge Dryja has worked on Bitcoin for a bit over a decade now.  Co-author of The Bitcoin Lightning Network, author of Discreet Log Contracts and Utreexo.  Currently working part-time on open source Bitcoin projects.

Disclosure: I've never owned any Ether or worked for compensation on Ethereum.  I have some familiarity with Ethereum from working at MIT DCI, and I did some Ethereum related work 10 years ago. (Hashimoto Proof of Work paper https://diyhpl.us/%7Ebryan/papers2/bitcoin/meh/hashimoto.pdf)

### Social Links
Github
https://github.com/adiabat
Twitter
https://twitter.com/tdryja
Website
I should make one huh.

# Talk Details
### Length of Talk
30 min, or could go to 45 min with questions.
### Preferred Day/Time Slot 
Anytime is OK

**Comment by iglesiasbrandon** [comment]
thank you for conducting this!
