### ISSUE TITLE
Slipstream: Making impossible TXs, Possible

### ISSUE THREAD

**Issue by russeree** [TABConf/6.tabconf.com#124]
# Description
### What is this talk about? Give us as many details as possible. 

This talk would be about the history, tradeoffs, and lessons learned regarding mining nonstandard transactions to the Bitcoin timechain in exchange for extra fee revenue. The primary focus being on relay policy rules vs consensus policy rules.

### What would an attendee learn from this talk?

- Why do relay rules exist?
- Broad overview of consensus rules.
- The deep history of mining nonstandard transactions in Bitcoin.
- Problems of mining nonstandard transactions
  - Mining an invalid block   
  - Upgrade Hooks
  - Forking off the network
  - Creating a block that attack Bitcoin miners DoS  
  - Block propagation issues
  - Social issues about the use cases for Bitcoin
  - Private mempool and associated fragmentation
  - Forces to centralize mining
- Benefits of mining nonstandard transactions
  - Fee revenue
  - Less restrictive use of the Bitcoin protocol (innovation)
  - Censorship resistance
  - Why Bitcoin needs independent template generating hashers
- So I am sold, How would I build my own Slipstream?

### Is there anything folks should read up on before they attend this talk?
Nothing is needed as everything will be covered in the talk,

### Relevant Links

# About the Speaker
### Social Links
[Github](https://github.com/russeree) 
[Twitter](https://x.com/portland.hodl)

# Talk Details
### Length of Talk
30-40 minutes
### Preferred Day/Time Slot 
any

**Comment by iglesiasbrandon** [comment]
thank you for conducting this talk!
