### ISSUE TITLE
Live Painting by Tommy™️

### ISSUE THREAD

**Issue by frankee21** [TABConf/6.tabconf.com#130]
# Description 
Bitcoin artist, Tommy™️ , paints an original onsite! 
### What is this idea? Give us as many details as possible.
**[** Live painting experience with Tommy™️ **]** 

Tommy will set up his canvas in an area where he can paint while keeping the workspace clean and organized. Ideally, the space will be well-lit, with the option to adjust lighting throughout the conference to enhance the atmosphere. Inspired by Bitcoin and the TAB conference energy, Tommy’s artwork will unfold as the event progresses. Attendees can stop by and interact with him as he paints, adding a collaborative touch to the final piece!

Tommy is Artist in Residence at Bitcoin Magazine and co-founder of Satoshi House Auctions, "**SHA**" for short, and would like to auction his painting at the pleb-tastic after party, **Hodlween**. 
### What would an attendee gain from this?

Every conference needs a chance for attendees to take a break and recharge their networking batteries.

Tommy, a Bitcoiner who began his rabbit hole journey in 2017, brings an approachable, Bob Ross-like vibe. Attendees will have the chance to interact with him during the event, and who knows? Your input might just influence the final masterpiece! 
### Relevant Links

Twitter (dying on this hill) profile [link](https://x.com/YungGucciT)
https://www.tommy.studio/artworks/end-fiat-before-fiat-ends-us 
![ENDFIAT_TOMMY](https://github.com/user-attachments/assets/8719a8a0-7116-42c7-b793-ceadaa2b8583)

**Comment by iglesiasbrandon** [comment]
Hey @frankee21 this looks awesome! What would you do with the painting at the end of the conference?

**Comment by frankee21** [comment]
GM, Brandon 😆

My name is Frankee, and I am a volunteer for Hodlween. So nice to e-meet
you!

Tommy and Erik, the co-founders of SHA, were planning on a non-reserve
auction which would conclude at Hodlween.

Did you have any ideas ? 👀

Best,
Frankee

**Comment by EllyPembroke** [comment]
Love this idea! We can host you at NextGen village, which is an interactive learning space at TabConf. Can you bring a tarp to protect the floor?

**Comment by EllyPembroke** [comment]
Also, would you be opposed to us supplying (small) canvas, paint and brushes to other conference attendees who might be inspired by you and would like to create their own piece of art?

**Comment by frankee21** [comment]
Hey Elly! Yes, we can definitely bring a tarp! 

Also, ABSOLUTELY !!! This is such a sweet idea... a real Boss Ross opportunity 🥰 

ps: I'm a volunteer of Hodlween/Tommy's unofficial assistant haha we're looking forward to meeting you all!

**Comment by iglesiasbrandon** [comment]
thank you for conducting this!
