### ISSUE TITLE
How do you feel about adding a pumpkin carving activity ?

### ISSUE THREAD

**Issue by marumover** [TABConf/6.tabconf.com#131]
The HODLween organizers did a pumpkin carving last year as a satellite event to the party and I think it would be a good addition for the nextgen village. Do you have any space in the schedule for it? 
@lizmparrish @partyp

**Comment by marumover** [comment]
You can close this issue I see it has been added on schedule. Thanks

**Comment by miketwenty1** [comment]
Noting that I believe this was closed because of #113
