### ISSUE TITLE
Wen Mainstream?  Put Devs Magic at Center Stage with V4V Music

### ISSUE THREAD

**Issue by caineroad** [TABConf/6.tabconf.com#133]
### What is this panel discussion about? 
V4V.  Bitcoin.  Nostr.  We all love talking about them, and the idea of mass adoption, but what does it really mean for this to ‘win’ and what does the pathway look like?

### What would an attendee learn from this talk?
How close to mainstream is V4V?  
What steps need to be taken to by those ‘in the know’ to accelerate the adoption?  
What does it mean to “opt out” and go V4V as a customer?  As a company?  As an artist?
What moves the needle if you really support the movement but are not a developer?  
How much of the adoption rate is due to the functionality or ease of use of the tools, versus getting the tools in the hands of the influential users?

### Relevant Links
https://tunestr.io/
https://phantompowermusic.io
https://wavlake.com
https://fountain.fm

### Moderator: 
Santos Hernandez

Santos is a Tabconf organizer.  He is a passionate Bitcoin educator, builder, and leader.  See his background and work at [Santos Hernandez](https://santos.lol/)

Panelist:
OpenMike, Just Loud, _TBD THIRD PANELIST_

OpenMike is the founder and CEO of Tunestr, a V4V music streaming platform using the zap.stream source code. A leader in the independent music world, OpenMike oversees the finances of over 1,200 concerts a year at independent venues only, is a founding member of the National Independent Venue Association & hosted the first V4V Tour with Ainsley Costello & Just Loud in December 2023. 

Just Loud is an American musician who had 10 million Spotify streams and played Lollapalooza under a record label deal, but unable to support himself financially as an artist.  Breaking free of his contractual obligations, he is now independent and recently played the first Tunestr V4V concert in Minneapolis in December 2023, earning over 10 million sats in one tour stop.  He has since played at Bitcoin 2024 in Nashville, and is appearing at HODLween during Tabconf.

OpenMike
Nostr
https://primal.net/openmike

GitHub
https://github.com/caineroad/tunestr.io

Twitter
@tunestr21

Websites
www.tunestr.io
www.nivassoc.org

### Who will be helping organize this panel?
OpenMike, Santos

### Length of the panel discussion
45 minutes

### Preferred Day/Time Slot 
Any time Friday preferred.  Thursday also works.

**Comment by asherp** [comment]
@caineroad We have space for this at the NextGen Village, but only on Saturday.

**Comment by caineroad** [comment]
Saturday works for us.  I would prefer late morning or early afternoon.  Thanks!

**Comment by iglesiasbrandon** [comment]
thank you for hosting this!

**Comment by caineroad** [comment]
Thank you for having us and putting on the event.  Great time.

On October 26, 2024 at 2:02 PM, Brandon Iglesias ***@***.***> wrote:

thank you for hosting this!

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you were mentioned.Message ID: ***@***.***>

-- 
Sent with https://mailfence.com  
Secure and private email
