### ISSUE TITLE
El Salvador: Real-world adoption pathways

### ISSUE THREAD

**Issue by JordanPendley** [TABConf/6.tabconf.com#134]
# Description
El Salvador: Real-world adoption pathways

### What is this talk about? Give us as many details as possible. 

I have been visiting El Salvador since spring 2023 to figure out what it means for El Salvador to make Bitcoin legal tender. I want to discuss the key pathways I have found there and how to understand where this might be going. You could categorize the pathways as Individual, community, and government and they specifically relate to the work Mi Primer Bitcoin is doing with educating high school students, the town of Berlin as the first real "Bitcoin City", and I want to speculate on the significance of Bukele's legal tender decision. 

I want to explain why Mi Primer Bitcoin is the most important thing happening in the entire Bitcoin space and why Berlin is the most significant developing circular economy and may offer more insight about Bitcoin's local economic properties than el zonte or anywhere else. I want to explore the idea that Bukele is setting up the first demonstration of Bitcoin as collateral but more importantly is giving it the freedom to be money and how bitcoin as money may be the most important distinction relative to what we know about the US's current and possible approach. 

### What would an attendee learn from this talk?

The attendee would get a realistic depiction of where the advancing edge of BTC adoption in El Salvador currently stands. They would leave knowing where they could go to experience it for themselves.  They would also have an idea of what this historic decision might mean for the macro landscape and for Bitcoin and El Salvador's future.

### Is there anything folks should read up on before they attend this talk?

no

### Relevant Links
https://myfirstbitcoin.io/
https://x.com/BitcoinBerlinSV

# About the Speaker
Low-key Bitcoin veteran of almost 11 years now. I was at the city council meeting in this appalachian town when the sheriff attempted to take his salary in Bitcoin in Nov 2013. https://www.coindesk.com/markets/2013/12/05/kentucky-police-chiefs-salary-paid-in-bitcoin/ 
I moved to a trailer in appalachia after experiencing that to study and focus on understanding this shift and have been continuing that ever since. I'll offer an interesting intro on myself around this in the presentation. It ironically fits the rest of the presentation on adoption. Independent analyst.

### Social Links
Github 
Twitter @jopendus
Website

# Talk Details
### Length of Talk

30 minutes should be doable. I can take questions if there is extra time. 

### Preferred Day/Time Slot 

anytime

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by asherp** [comment]
This is Awesome! @iglesiasbrandon We're Happy to have this in the NextGen space

**Comment by iglesiasbrandon** [comment]
thank you for conducting this talk!
