### ISSUE TITLE
Intro to Digital Logic (Silas Pembroke)

### ISSUE THREAD

**Issue by asherp** [TABConf/6.tabconf.com#136]
# Description
### What is this talk about? Give us as many details as possible. 

Silas continues his interactive presentation on digital logic and the foundations of computer science. 

### What would an attendee learn from this talk?

From basic logic gates to rudimentary CPU, this course demonstrates how a few simple rules can be used to create powerful machines.

### Is there anything folks should read up on before they attend this talk?

Silas builds on his previous lectures, but they are not required. Last year's lecture may be found here https://www.youtube.com/watch?v=B9Owo0kGwyQ

### Relevant Links

# About the Speaker

Silas is a homeschooler with a passion for mathematics and computer science. This will be his third year attending Tabconf as its youngest contributor. Over the past year he has been documenting his math adventures, covering topics from set theory and geometric algebra to lambda calculus.

### Social Links

Silas's website/math blog https://silaspe.github.io/maths/

# Talk Details
### Length of Talk

30-40 m

### Preferred Day/Time Slot

Saturday

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by iglesiasbrandon** [comment]
Thank you for hosting this!
