### ISSUE TITLE
Lessons to be learned - CSW v Bitcoin

### ISSUE THREAD

**Issue by TrisSherliker** [TABConf/6.tabconf.com#137]
# Description

### What is this talk about? Give us as many details as possible. 

I'm proposing to talk about Craig Wright's claim to be Satoshi Nakamoto, how it went down in Court, and some lessons that can be learned from it for Bitcoin as a whole. 

I've spent the last two years or more as part of the team working on behalf of COPA (Crypto Open Patent Alliance). There's a lot of information out there, from media reports to thousands of pages of evidence - which while detailed, isn't particularly digestible.  I think there's room for a deeper understanding of three things:

 - first, what could have resulted if the case went the other way (e.g. which IP rights were being asserted and how the claims could affect the industry), 
 - second, examples of the sort of technical evidence that was presented. This is mainly of technical interest, but it is interesting. 
 - third, the lessons discussed below.

### What would an attendee learn from this talk?

In my opinion there are three 'lessons' to take from the casee -

- One is to recognise that an open-source model as a whole cases some vulnerabilities, and to be vigilant to those.

- The second is a specific point, arising from one part of Craig Wright's litigation campaign. There is an appeal court ruling to the effect that the MIT licence *may* leave open-source contributors liable to people who use their software. That isn't a final ruling, but everyone in the industry would benefit from some level of awareness of it, and what it could mean. I've linked to the court decision itself in the links below, but the most relevant quotation from the judgment is pasted here: 

  > "Pulling all this together, I recognise that for Tulip's _[Craig Wright's company's]_ case to succeed would involve a significant development of the common law on fiduciary duties. I do not pretend that every step along the way is simple or easy. However there is, it seems to me, a realistic argument along the following lines. The developers of a given network are a sufficiently well defined group to be capable of being subject to fiduciary duties. Viewed objectively the developers have undertaken a role which involves making discretionary decisions and exercising power for and on behalf of other people, in relation to property owned by those other people. That property has been entrusted into the care of the developers. The developers therefore are fiduciaries. The essence of that duty is single minded loyalty to the users of bitcoin software. The content of the duties includes a duty not to act in their own self interest and also involves a duty to act in positive ways in certain circumstances. It may also, realistically, include a duty to act to introduce code so that an owner's bitcoin can be transferred to safety in the circumstances alleged[.]"

- The third is about the benefits of the community spirit of Bitcoin, and to encourage a community spirit in facing IP and other similar challenges.

### Is there anything folks should read up on before they attend this talk?

No. Many people will have some level of awareness of the case, but it does not presume background knowledge.

### Relevant Links

[Tulip Trading v Bitcoin Developers -- Court of Appeal decision](https://www.bailii.org/ew/cases/EWCA/Civ/2023/83.html)

[COPA v Wright -- decision on Wright's claims to be Satoshi](https://www.bailii.org/ew/cases/EWHC/Ch/2024/1198.html)

# About the Speaker

I'm a lawyer in the UK at Bird & Bird, acting for COPA in the case described above. My main practice is in Intellectual Property disputes in the UK.  I myself am relatively technical, appreciate FOSS greatly, and enjoy tinkering with software, and making things of my own.

### Social Links

Website: https://www.twobirds.com/en/people/t/tristan-sherliker

# Talk Details
### Length of Talk

I suggest 30 minutes to 1 hour.  A longer slot would allow for more discussion and technical detail - a deep dive, which can be interesting since the detail helps with understanding.  Some of the message could be compressed into a shorter time at the expense of nuance. 
 
I'm submitting as a talk, but I am also open being part of a panel discussion or other format.

### Preferred Day/Time Slot 

23rd and 24th October are preferable.

**Comment by btsea** [comment]
@TrisSherliker I have spoken to @miketwenty1 and @iglesiasbrandon. If you are still able to come to the conference, please let me know and we will fit you into the Socratic Village as a 30 minute talk. Please accept this invitation by Monday September 30th.

**Comment by miketwenty1** [comment]
@btsea I want to have this recorded. I know your room won't be setup for AV. Unless you want to make an exception. we should chat about this.

**Comment by miketwenty1** [comment]
update: plan is to have this in the bitdevs socratic room and this will not be recorded.

**Comment by TrisSherliker** [comment]
All,
I'm sorry to say that it's looking like I won't be able to attend after all and will have to withdraw the proposal. Many apologies folks - this was outside my control, and I was really grateful for the discussion and invitation. Perhaps next time, or at another place we can work something out. 
Tris

**Comment by TrisSherliker** [comment]
Closing as not-planned, with regrets.

**Comment by TrisSherliker** [comment]
Michael, Apologies if I have mistagged this. I mean that since I can no
longer attend, I'm not planning to give the talk.
