### ISSUE TITLE
Funding a 1.2 Trillion Dollar Asset: How do Core Devs get paid?

### ISSUE THREAD

**Issue by oprey** [TABConf/6.tabconf.com#138]
# Description
We will present a comprehensive overview of how Bitcoin Core Developers are funded today, from both non-profits and corporate entities. After speaking to the leads and senior personnel of all the major organizations, we are presenting a summary covering how bitcoin development is funded today; the various models, and the surprising challenges and vulnerabilities.

# What would an attendee learn from this talk?

## Introduction
Why are we doing this?
How does Bitcoin funding compare?
Why is this?
What are we going to cover?
## Funding Landscape
Who Funds Bitcoin Development Today?
How is Bitcoin funded today?
What do each of these orgs focus on?
How much does each org provide?
## Key Challenges and Ideas
Summary of what we heard from talking to the major orgs

# Is there anything folks should read up on before they attend this talk?

Not required, but feel free to read the full report ahead of time:
http://1a1z.com/fund.html

# About the Speakers

Dan O’Prey - Dan has been a bitcoiner for over a decade, holding executive positions at Bakkt, Digital Asset, and Hyperledger. Dan is now researching opportunities within the bitcoin and freedom-tech space.
https://www.linkedin.com/in/danoprey/

Mas Nakachi - Currently runs corporate development and principal investments for XBTO and is looking for new ways to advance freedom technologies overall.
https://www.linkedin.com/in/mas-nakachi-b1b848/

# Talk Details
### Length of Talk
15 - 25 minutes

### Preferred Day/Time Slot 
We cannot do Friday afternoon or Saturday unfortunately!

**Comment by vnprc** [comment]
I think I would really enjoy this talk!

**Comment by adam2k** [comment]
I'd be interested in hearing this talk too.

**Comment by bigbuzz** [comment]
I am looking forward to this talk

**Comment by btsea** [comment]
We would be happy to host this in the BitDevs Socratic Village! @oprey we will keep you abreast of scheduling over the next two weeks.

**Comment by oprey** [comment]
@btsea Amazing! Thanks a lot and look forward to hearing from you. My email is dan @ [mygithubusername] .io if you need it

**Comment by btsea** [comment]
Also, we can allot 30 minutes in our schedule for this, including questions. @oprey

**Comment by oprey** [comment]
@btsea That sounds great to us. We can easily expand to 20/25 pres

**Comment by btsea** [comment]
Sounds good! And please note @oprey we do not have recording equipment in the Socratic Village. If you would like to record your talk you will need to make arrangements.

**Comment by oprey** [comment]
@btsea Hey, I see a timeslot was allocated. Unfortunately noted that we couldn't do Friday afternoon... Are there any slots possible Wednesday or Thursday? Or worst case early Friday? Apologies

**Comment by btsea** [comment]
Ah I missed that, sorry @oprey. What time are you available until Friday? Wednesday and Thursday are Builder Days, there are no talks on those days. 

Thanks.

**Comment by oprey** [comment]
@btsea Ideally before 11am if possible? Otherwise 12 latest to rush to the airport!

**Comment by btsea** [comment]
Okay so the opening remarks on the main stage are from 9:30 - 9:45, then there is this talk until 10:15 by @adamjonas: https://github.com/TABConf/6.tabconf.com/issues/56

We definitely can't overlap with that given the relevance. Then for 15 minutes there is the welcome ceremony in the Socratic Village, which includes a very significant announcement which is relevant to your talk, actually. 

So realistically the absolute earliest I could get you in 10:45, right after our welcome ceremony. That seems to be okay from what you said, but please confirm and I will adjust the times. You would be done by 11:15. 

Thanks

**Comment by oprey** [comment]
@btsea That would be fantastic! And agree, really don't want to clash with Jonas and great to follow the announcement. Thanks so much for accomodating!

**Comment by iglesiasbrandon** [comment]
thank you for conducting this talk and creating this report @oprey
