### ISSUE TITLE
Socratic Panel: Mining Centralization in 2024 - Risks and Mitigations

### ISSUE THREAD

**Issue by vnprc** [TABConf/6.tabconf.com#139]
# Description

The degree of mining centralization in the Bitcoin network is at an all time high. Between custody providers, hashrate laundering, FPPS payout schemes, centralized hardware manufacturers and future risks surrounding MEV and out-of-band fee payments, the future of Bitcoin’s censorship resistance is at stake. In this panel we will review various efforts to relieve these pressures and discuss the risks posed by various actors and strategies employed across the mining industry.

# Format

This is a Socratic Panel, which means the event will be a two-way dialogue. It is expected for both panel participants and members of the crowd to ask and answer questions.

To begin the panel, each panelist will give a short 5-10 minute presentation on the topic. Once the presentations are complete, the moderator will pose a few questions to stimulate discussion. From here, the crowd and panelists will be offered a chance to steer discussion with their own questions.

## Panelists
- @average-gary
- @skot
- @vnprc
- @thebluematt

## Moderator
- @btsea

### Length of the panel discussion
1hr

### Preferred Day/Time Slot 
It just can't conflict with other panelist talks.

**Comment by vnprc** [comment]
This panel will be part of the Socratic Village.

**Comment by btsea** [comment]
Hey @vnprc can you please change the title of the issue to Socratic Panel: Mining Centralization in 2024 - Risks and Mitigations

Thank you! 🙏

**Comment by skot** [comment]
ACK
I can speak to the hardware centralization side.

**Comment by vnprc** [comment]
lol oops I did not mean to click that. ACK as well from me.

**Comment by average-gary** [comment]
ACK

**Comment by btsea** [comment]
Hi @TheBlueMatt @skot @vnprc @average-gary thanks again for your participation on this Socratic Panel.

Please see [this document](https://docs.google.com/document/d/1w5-gM0u-El4tVUMSz1CIZtJdGFw1C5dYDsalRJ3wcSM/edit?tab=t.0) on how to prepare. This is not a normal panel, so there are additional requirements. Let me know if you have any questions.

**Comment by skot** [comment]
I get access denied from google docs when clicking on that link.

**Comment by iglesiasbrandon** [comment]
Thank you for hosting this!
