### ISSUE TITLE
Basics of using Fusion360 to design physical bitcoin products

### ISSUE THREAD

**Issue by myklhodls** [TABConf/6.tabconf.com#140]
# Description
### What is this talk about? Give us as many details as possible. 

I'm a Mechanical Engineer and Product Developer. I propose a demo of Autodesk's Fusion360 design software which I use to design cases for bitcoin hardware wallets, etc.

### What would an attendee learn from this talk?

How to get started with 3D design to design products for 3D printing or manufacturing.

### Is there anything folks should read up on before they attend this talk?

No

### Relevant Links

My latest related project: geyser.fund/project/satsboy

# About the Speaker
### Social Links
Github: myklhodls
Twitter: @myklhodls, @lfgogames
Website: lfgo.co

# Talk Details
### Preferred Day/Time Slot : Friday or Saturday, any time
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by iglesiasbrandon** [comment]
thank you for hosting this!
