### ISSUE TITLE
Play Mission Bitcoin - a bitcoin board game for all ages 6+

### ISSUE THREAD

**Issue by myklhodls** [TABConf/6.tabconf.com#141]
# Description
### Relevant Links: lfgo.co

# About the Speaker - Mykl is a bitcoiner, Mechanical Engineer, product developer, and the designer of Mission Bitcoin.

### Social Links
Github - myklhodls
Twitter @lfgogames , @myklhodls
Website lfgo.co

# Talk Details
### Preferred Day/Time Slot - Anytime Friday or Saturday
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by asherp** [comment]
Happy to have you!

**Comment by jegamboafuentes** [comment]
Hey @myklhodls! 👋

I saw your awesome issue and thought I'd let you know about [Lightning Bounties](https://www.lightningbounties.com/)! 🚀 It's a super easy-to-use app where you can add a Bitcoin reward to this issue, encouraging devs to jump in and help you solve it.

Here’s a quick tutorial to get started: [Lightning Bounties Tutorial](https://docs.lightningbounties.com/docs/posting-a-bounty/create-a-github-issue-and-submit-a-new-reward). 💡 You can post your issue there, set up a bounty, and whoever cracks the code gets rewarded instantly in Bitcoin. 🔥

Let me know if you have any questions or need help setting it up!

Cheers! ⚡

**Comment by Admasnd** [comment]
Will be attending. Looking forward to it!

**Comment by iglesiasbrandon** [comment]
thank you for hosting this!
