### ISSUE TITLE
Single Elimination Chess Tournament

### ISSUE THREAD

**Issue by ChrisKCBtcYolo** [TABConf/6.tabconf.com#142]
### What is this event about?

A single elimination chess tournament is a competitive event where players face off against each other in a series of matches, with each defeat resulting in immediate elimination until there is only one winner remaining.

### What would an attendee learn from this event?
This tournament is all about the strategic game of chess, a classic board game that has been played for centuries. The objective is to outsmart your opponent by capturing their pieces while protecting your own. 

### Details: 
Single Elimination Tournament, once you lose, you're out. 

### Buy in:
 Sats equivalent to $20 buy in. Winner takes all 

### Is there anything attendees should do before playing?
Practice

### Is there anything attendees should set up?
Chess boards will be provided. If we get any donations we will provide light refreshments. 

### Registration Link:
https://btcpay386958.lndyn.com/apps/2vocXKGKVPVN1r6AnyBVHv8aThWv/pos

### Level of difficulty
Intermediate chess skills

![33AC1F95-CAC9-48BA-A4DD-5D8C7CBC09B8](https://github.com/user-attachments/assets/018adbf3-ce10-4227-b024-f2a9d05521ff)

**Comment by ChrisKCBtcYolo** [comment]
alright lets do Wed 9 AM
limit signups to 8-12 people
single elimination
5 2 games. 
ill get a link popped in here to signup
simple btcpayserver
@miketwenty1

**Comment by ChrisKCBtcYolo** [comment]
Here's the official link to get registered for the single elimination chess tournament at TabConf 2024 in Hotlanta! Time to sharpen your chess skills and put on your thinking caps! Who's gonna try and beat me?

https://btcpay386958.lndyn.com/apps/2vocXKGKVPVN1r6AnyBVHv8aThWv/pos

![2AEB84E3-1517-4084-B3DC-A41C14E38491](https://github.com/user-attachments/assets/811dc57c-b0fc-451c-9122-449991cfcf1f)

**Comment by iglesiasbrandon** [comment]
thank you for hosting this!
