### ISSUE TITLE
Hackathon Semifinalists Pitches

### ISSUE THREAD

**Issue by zantoshi** [TABConf/6.tabconf.com#143]
# Description
### What is this idea? Give us as many details as possible. 
This will be a hackathon pitches for the semifinalists to get selected to potentially win a category.
### What would an attendee gain from this?
Win prizes!

**Comment by EllyPembroke** [comment]
We'll block out two hours for you in case anyone goes overtime

**Comment by iglesiasbrandon** [comment]
thank you for creating another amazing hackathon!
