### ISSUE TITLE
Socratic Session: Bitcoin Core - Project Updates and Cherry Picked PRs

### ISSUE THREAD

**Issue by btsea** [TABConf/6.tabconf.com#147]
# Description

A focused Socratic Seminar on Bitcoin protocol development. If you are curious about the latest updates in Bitcoin Core, this is the event for you. We'll be reviewing select pull requests as well as surveying some of the long-running development priorities within the project.

# Format

Socratic Sessions are condensed versions of a [Socratic-style meetup](https://bitdevs.org/about#socratic-seminars). A discussion leader will curate content based on a general theme and come prepared to give background on the material and provide discussion questions for the group.

## Moderators

- @btsea 
- @davidgumberg
- @murchandamus

## Topics
- Kernel
    - [Tracking issue](https://github.com/bitcoin/bitcoin/issues/27587)
    - [Recent write-up](https://thecharlatan.ch/Kernel/)
- [Bitcoin Core Security Policy and Recent CVEs](https://bitcoincore.org/en/security-advisories/)
- [Multiprocess](https://github.com/bitcoin/bitcoin/issues/28722) 
- [Erlay](https://github.com/bitcoin/bitcoin/issues/30249)
- [Fee Estimation via Fee rate Forecasters](https://github.com/bitcoin/bitcoin/issues/30392)

- Pull Requests
    - [Short-lived tor broadcast](https://github.com/bitcoin/bitcoin/pull/29415)
    - [Don't empty dbcache on prune flushes: >30% faster IBD](https://github.com/bitcoin/bitcoin/pull/28280)
    - [Drop -dbcache limit](https://github.com/bitcoin/bitcoin/pull/28358)

**Comment by btsea** [comment]
Hey @davidgumberg can you please put an ACK in here and I will assign this issue to you. Thanks!

**Comment by davidgumberg** [comment]
ACK

**Comment by murchandamus** [comment]
ACK

**Comment by davidgumberg** [comment]
## Kernel

Project tracking issue: https://github.com/bitcoin/bitcoin/issues/27587
Recent write-up: https://thecharlatan.ch/Kernel/

## CVE's

https://bitcoincore.org/en/security-advisories/


## Cherry Pick

Short-lived tor broadcast: https://github.com/bitcoin/bitcoin/pull/29415
