### ISSUE TITLE
Socratic Session: Lightning BOLT Spec and Implementation Updates

### ISSUE THREAD

**Issue by btsea** [TABConf/6.tabconf.com#148]
# Description

A focused Socratic Seminar on lightning protocol development. Topics will be selected from the lightning-dev mailing lists, prominent Github repositories, network graphs, research papers, vulnerability reports and other sources.

# Format

Socratic Sessions are condensed versions of a [Socratic-style meetup](https://bitdevs.org/about#socratic-seminars). A discussion leader will curate content based on a general theme and come prepared to give background on the material and provide discussion questions for the group.

## Moderators

- @vnprc 
- @Randy808
- @niftynei

## Topics

@vnprc
- [The Breez SDK Adds Nodeless: A Liquid Implementation](https://github.com/breez)
  - [StashPay is the first wallet to ship using the brand new Breez Liquid SDK](https://blog.onionmill.com/p/welcome-to-the-stashpay-testflight)
- [BOLT12 Offers Merged](https://github.com/lightning/bolts/pull/798)
- [Building Bolt12 Into Strike](https://strike.me/blog/bolt12-offers/)
- [Mutiny Wallet](https://blog.mutinywallet.com/mutiny-wallet-is-shutting-down/) and [10101](https://10101.finance/blog/10101-is-shutting-down/) are both shutting down. 😢

@niftynei
- [LN Summit 2024 Notes & Summary/Commentary](https://delvingbitcoin.org/t/ln-summit-2024-notes-summary-commentary/1198)
- [Lightning Welder](https://github.com/alexlwn123/Lightning-Welder)

@Randy808
- [Spec for dual funding merged into BOLTs](https://github.com/lightning/bolts/pull/851)
- [Bitcoin Core 28 wallet integration guide](https://bitcoinops.org/en/bitcoin-core-28-wallet-integration-guide/) discusses the impact of TRUC transactions on anchor outputs and the potential future deprecation of update_fee as well RBF pinning attacks.

Open Discussion:
- [Hybrid Jamming Mitigation: Results and Updates](https://delvingbitcoin.org/t/hybrid-jamming-mitigation-results-and-updates/1147)
- [SuperScalar: Laddered Timeout-Tree-Structured Decker-Wattenhofer Factories](https://delvingbitcoin.org/t/superscalar-laddered-timeout-tree-structured-decker-wattenhofer-factories/1143)
- [LND custom channels PR](https://github.com/lightningnetwork/lnd/pull/8960/files#diff-d8ed3157089b4fb9b6e61d523fd956f2adfd223fdc76d000112bb8e2dab96e8e)
- [LDK rust-lightning v0.0.124 release notes](https://github.com/lightningdevkit/rust-lightning/releases/tag/v0.0.124)
- [LND Gossip Messages](https://github.com/lightningnetwork/lnd/pull/8044)
- [Eclair: Allow including routing hints when creating Bolt 11 invoice](https://github.com/ACINQ/eclair/pull/2909)
- [LDK: Support paying static invoices](https://github.com/lightningdevkit/rust-lightning/pull/3140)
- [LDK: Add the core functionality required to resolve Human Readable Names](https://github.com/lightningdevkit/rust-lightning/pull/3179)

**Comment by vnprc** [comment]
Potential topic list :point_up:

If there is a topic you would like to be discussed, drop it in that github issue. If it's already up there throw a thumbs up on the comment.

**Comment by Randy808** [comment]
ACK

**Comment by vnprc** [comment]
@vnprc
- [The Breez SDK Adds Nodeless: A Liquid Implementation](https://github.com/breez)
- [BOLT12 Offers Merged](https://github.com/lightning/bolts/pull/798)
- [Building Bolt12 Into Strike](https://strike.me/blog/bolt12-offers/)
- [Mutiny Wallet](https://blog.mutinywallet.com/mutiny-wallet-is-shutting-down/) and [10101](https://10101.finance/blog/10101-is-shutting-down/) are both shutting down. 😢

@niftynei
- [LN Summit 2024 Notes & Summary/Commentary](https://delvingbitcoin.org/t/ln-summit-2024-notes-summary-commentary/1198)

@Randy808
- [Spec for dual funding merged into BOLTs](https://github.com/lightning/bolts/pull/851)
- [Bitcoin Core 28 wallet integration guide](https://bitcoinops.org/en/bitcoin-core-28-wallet-integration-guide/) discusses the impact of TRUC transactions on anchor outputs and the potential future deprecation of update_fee as well RBF pinning attacks.

Open Discussion:
- [Hybrid Jamming Mitigation: Results and Updates](https://delvingbitcoin.org/t/hybrid-jamming-mitigation-results-and-updates/1147)
- [SuperScalar: Laddered Timeout-Tree-Structured Decker-Wattenhofer Factories](https://delvingbitcoin.org/t/superscalar-laddered-timeout-tree-structured-decker-wattenhofer-factories/1143)
- [LND custom channels PR](https://github.com/lightningnetwork/lnd/pull/8960/files#diff-d8ed3157089b4fb9b6e61d523fd956f2adfd223fdc76d000112bb8e2dab96e8e)
- [LDK rust-lightning v0.0.124 release notes](https://github.com/lightningdevkit/rust-lightning/releases/tag/v0.0.124)
- [LND Gossip Messages](https://github.com/lightningnetwork/lnd/pull/8044)
- [Eclair: Allow including routing hints when creating Bolt 11 invoice](https://github.com/ACINQ/eclair/pull/2909)
- [LDK: Support paying static invoices](https://github.com/lightningdevkit/rust-lightning/pull/3140)

**Comment by dstadulis** [comment]
More information about the [Custom channels lnd PR](https://github.com/lightningnetwork/lnd/pull/8960/files#diff-d8ed3157089b4fb9b6e61d523fd956f2adfd223fdc76d000112bb8e2dab96e8e)
  - main channel state machine and database now allow for processing and storing custom Taproot script leaves
    - meaning application hackers can incorporate application state into the t
    - lnd's RPCs have been enhanced s.t. an application can control the
      - routerrpc.HtlcInterceptor
        - 1 ) which allows the interceptor to read and interpreted by external software
        - 2) HLTC values can be manipulated by software external to LND

**Comment by iglesiasbrandon** [comment]
thank you for hosting this!

**Comment by vnprc** [comment]
Thank you for cohosting @niftynei and @Randy808. Great job! Y'all are awesome!
