### ISSUE TITLE
Socratic Panel: Modern Mempool Architecture

### ISSUE THREAD

**Issue by btsea** [TABConf/6.tabconf.com#149]
# Description

A functioning and logically-sound mempool exists at the core of the Bitcoin network. Without the ability to reliably broadcast and relay transactions, the security properties and censorship-resistance of both L1 and L2 transactions suffer. The structure and policies of the mempool are not however consensus rules. In light of novel classes of attacks against layer 2 schemes, as well as deficiencies in how transactions are associated and reasoned about in the context of mining and eviction policies, much work has been done to improve upon mempool logic. This panel will investigate changes such as Package Relay, Cluster Mempool, P2A/Ephemeral Anchors, Standardness Rules, and other mempool-focused research topics.

# Format

This is a Socratic Panel, which means the event will be a two-way dialogue. It is expected for both panel participants and members of the crowd to ask and answer questions.

To begin the panel, each panelist will give a short 5-10 minute presentation on the topic. Once the presentations are complete, the moderator will pose a few questions to stimulate discussion. From here, the crowd and panelists will be offered a chance to steer discussion with their own questions.

## Panelists

- @murchandamus
- @pinheadmz
- @glozow

## Moderator

- @btsea

**Comment by btsea** [comment]
Thanks for your participation @pinheadmz, @achow101, @murchandamus, and @glozow! Please post an ACK in here so I can assign the issue to you 🙏

**Comment by pinheadmz** [comment]
ACK

**Comment by achow101** [comment]
ACK

**Comment by glozow** [comment]
ACK

**Comment by murchandamus** [comment]
ACK

**Comment by btsea** [comment]
Thanks again for your participation @murchandamus @pinheadmz @glozow @achow101! 

Please see [this document](https://docs.google.com/document/d/1w5-gM0u-El4tVUMSz1CIZtJdGFw1C5dYDsalRJ3wcSM/edit?tab=t.0) on how to prepare. This is not a normal panel, so there are additional requirements. Let me know if you have any questions. Put a thumbs up on this message once you have read through the document. Thank you!

**Comment by iglesiasbrandon** [comment]
Thank you for hosting this panel!
