### ISSUE TITLE
Socratic Panel: Changing Channels - A Technical Review of Consensus Compatible Layer 2 Schemes 

### ISSUE THREAD

**Issue by btsea** [TABConf/6.tabconf.com#152]
# Description 

Significant research has gone into designing and developing novel L2 schemes that do not utilize channel-based primitives but are still functional without consensus changes. In this panel we will investigate some of those protocols. We will learn about how they "hook" into the base layer, what their design goals are, what security assumptions they make, and what user experience tradeoffs to expect. Specifically, we'll focus our time on BitVM2, Shielded CSV, and Ark.

# Format

This is a Socratic Panel, which means the event will be a two-way dialogue. It is expected for both panel participants and members of the crowd to ask and answer questions.

To begin the panel, each panelist will give a short 5-10 minute presentation on the topic. Once the presentations are complete, the moderator will pose a few questions to stimulate discussion. From here, the crowd and panelists will be offered a chance to steer discussion with their own questions.

## Panelists

- @jonasnick
- @RobinLinus
- @ErikDeSmedt

## Moderator

- @btsea

**Comment by btsea** [comment]
Thanks for your participation @jonasnick, @RobinLinux, and @ErikDeSmedt. Please ACK this message so I can assign this issue to you.

Additionally, please see [this document](https://docs.google.com/document/d/1w5-gM0u-El4tVUMSz1CIZtJdGFw1C5dYDsalRJ3wcSM/edit?tab=t.0) on how to prepare. This is not a normal panel, so there are additional requirements. Let me know if you have any questions. Put a thumbs up on this message once you have read through the document. Thank you!

**Comment by RobinLinus** [comment]
ACK

**Comment by jonasnick** [comment]
ACK

**Comment by ErikDeSmedt** [comment]
ACK

**Comment by iglesiasbrandon** [comment]
thank you for conducting this panel!
