### ISSUE TITLE
DIDdevs: Decentralized Web Meetup 4

### ISSUE THREAD

**Issue by sbddesign** [TABConf/6.tabconf.com#153]
![atlanta-diddevs-decentralized-web-october](https://github.com/user-attachments/assets/95288606-4e00-407d-aa8a-7ae6165a9ff0)

# Event Description

Come learn about the power and potential of the decentralized web! Everyday the web and other digital technology becomes even further enmeshed with our lives. But all this technology has become centralized and controlled by top-down authorities. What if there was a better way? A way for web applications developer to build products and services that return the power to the individual user and help us create a more fair and prosperous world? At DIDdevs, we explore decentralized identity and other tech solutions to make this world a reality.

Join us on the third Monday of every month for learning, engaging discussion, and networking in the decentralized web space. All skill levels welcome!

## Potential Topics

- Decentralized Identity (DID)
- Self-sovereign Identity
- Web5
- Web Development
- And more!

### Date and time
Monday, October 21
18:00 Atlanta Time

### Location

ATL BitLab
684 John Wesley Dobbs Ave NE, Suite A1, Atlanta, GA 30312
https://maps.app.goo.gl/m3iLHUe8JAVgRmvf6

### Anything people should know before coming?

Read up on DIDs and Web5 if you're curious, but otherwise, just come with an open mind.

### Relevant Links

https://www.meetup.com/atlbitlab/events/302187218/

**Comment by iglesiasbrandon** [comment]
We have them on both @sbddesign
