### ISSUE TITLE
Soft-Fork/Covenant Dependent Layer 2 Review

### ISSUE THREAD

**Issue by petertodd** [TABConf/6.tabconf.com#154]
# Description
### What is this talk about? Give us as many details as possible. 

I recently completed a large review paper on soft-fork/covenant dependent Layer 2's. Specifically, L2's intending to scale Bitcoin by allowing mutiple end users to share UTXOs: https://petertodd.org/2024/covenant-dependent-layer-2-review

In this talk I'll summarize my findings, explaining what an L2 is, what a covenant is, why L2's that share UTXOs between users need covenants, what L2 proposals are out there (in particular, Ark), what covenant types they need, what kind of scaling is actually possible, what risks this can pose, and what deployment could look like.

### What would an attendee learn from this talk?

The key thing a general, technical, audience attendee will get out of this is an overview of how people want to change the Bitcoin protocol for future L2s, and why.

### Is there anything folks should read up on before they attend this talk?

https://petertodd.org/2024/covenant-dependent-layer-2-review

### Relevant Links

https://petertodd.org/2024/covenant-dependent-layer-2-review

# About the Speaker

Founder of OpenTimestamps, and a significant enough contributor to Bitcoin Core to get sued by Craig Wright. Admittedly, that's a low bar...

### Social Links
https://twitter.com/peterktodd
https://petertodd.org

# Talk Details
### Length of Talk

30-60 mins, including questions. I can fit the talk to the timeslot available.

### Preferred Day/Time Slot 

**MANDATORY**: I can only give this talk on the first day of the conference due to the fact that I'm also committed to attending the Plan B forum.

**Comment by btsea** [comment]
Hey @petertodd! Unfortunately Day 1 and 2 are the builder days, so I am not sure a talk would satisfy those requirements. But @iglesiasbrandon and @miketwenty1 can confirm that.

**Comment by iglesiasbrandon** [comment]
Hey @btsea, yes, that's correct. Day 1 and 2 are workshops and builder days.

**Comment by petertodd** [comment]
Sorry, but I don't think there is a reasonable way to turn that into a workshop. It's inherently a relatively theoretical subject as I'm doing an overview of a bunch of systems that mostly don't actually exist yet.

If you're willing to make an exception, great, otherwise it's better for my scheduling if you reject it now.

**Comment by ariard** [comment]
Easy to turn a theoretical talk as a workshop, after presenting each L2 just give 2min to the attendees to think by themselves about the strengths and weaknesses of each L2 on a paper sheet. The attendees do some “work”.

**Comment by iglesiasbrandon** [comment]
hey @petertodd, yea I figured, but I wanted to make sure. I will talk to the org team and let you know.

**Comment by miketwenty1** [comment]
@petertodd ACK that you are able to come and we will mark as Accepted.

**Comment by petertodd** [comment]
ACK!

**Comment by ariard** [comment]
If that talk can be in the afternoon of the 23 or the 24th, interested and only landing midday of the 23 in ATL.

**Comment by iglesiasbrandon** [comment]
Thank you for conducting this talk!
