### ISSUE TITLE
Live Bitcoin Mining Auction

### ISSUE THREAD

**Issue by evanbaer** [TABConf/6.tabconf.com#155]
# Description

Mining is on the agenda for multiple talks this year. A live mining auction will give folks the opportunity to bid on hashrate, try mining first hand and take action to decentralize the network.

### What is this idea? Give us as many details as possible. 

Rigly is an auction marketplace for bitcoin mining:

- Mining farms list their hashrate for bid
- Bitcoiners buy hashrate and send to their mining pool account (or node)
- On-chain escrow allows sellers to receive partial payment upfront, with the balance paid out over time, as hashrate is delivered, to discourage rug pulls.

The idea is to do an in-person auction for several listings of hashrate.

Example listings:

- 120 TH/s for 30 days @ Texas
- 200 TH/s for 45 days @ South America off-grid natgas mine
- 500 TH/s for 90 days @ Africa off-grid hydro mine

The auction would use the commodity auction format, with live bid calling by an auctioneer.

Winners receive their hashrate after the auction close and can start mining right away.

Rigly will donate auction fees to open source development via OpenSats.

How this fits into the overall conference, where/when etc I'm open to discuss.

### What would an attendee gain from this?

It allows any attendee to mine bitcoin. 

Winning bidders are able to mine at a potential profit, and decentralize mining by distributing hashrate among different mining pools or mine solo, try stratum v2, etc as they see fit.

Select open source projects will see new funds as a result of the auction.

### Relevant Links

https://rigly.io

**Comment by asherp** [comment]
This is now an online auction running continuously throughout the conference. Place your bids here!

http://rigly.io/test-drive

**Comment by evanbaer** [comment]
Auctions just ended, 2.3m sats raised for Opensats 🙌 

[Rigly_opensats.pdf](https://github.com/user-attachments/files/17531063/Rigly_opensats.pdf)
