### ISSUE TITLE
Socratic Village: Welcome Ceremony and 🌝 Mystery 🌝 Announcements

### ISSUE THREAD

**Issue by btsea** [TABConf/6.tabconf.com#156]
# Description

This year's Socratic Village is sponsored by two projects that are coming out of stealth mode! Come learn about these projects and all the exciting content we have planned in our village. 

We will be rolling directly into the first Socratic Session at the end of our welcome ceremony.

**Comment by iglesiasbrandon** [comment]
Thank you!
