### ISSUE TITLE
Latest Advancements in Wallet Security and Privacy at Bitkey

### ISSUE THREAD

**Issue by jurvis** [TABConf/6.tabconf.com#159]
# Description
### What is this talk about? Give us as many details as possible. 

At Bitkey, our motto is, “easy to use, hard to lose”. From cloud-based recovery tools to Emergency Access Kit, we strive to make it seriously hard to lose your bitcoin—whether from mismanagement or external threats. This dual focus on safeguarding against both accidental loss and malicious attacks is the foundation of what we believe is important to make self-custodial wallets accessible for everyone.

We have been hard at work, looking at new ways that self-custody wallets can serve the needs of Bitcoin holders. As part of this effort, we’re exploring a design that leverages multi-party computation and zero-knowledge proofs, offering flexible and secure self-custody. This approach would allow users to start without a dedicated hardware wallet, with the option to transition to hardware when they’re ready—while maintaining a robust security profile that fits their personal needs.

We will show some of our work in this talk, and hope to solicit feedback and criticism from others. Here are some of the topics we will cover:

- Challenge the privacy tradeoffs we accept from pre-existing `OP_CHECKMULTISIG` collaborative custodial models
- Look into how MPC protocols like FROST help us create new ways of securing sensitive material, and can facilitate off-chain recovery, key share rotation, and upgrades to hardware backed security
- Explore how PIN-derived keys utilizing OPRFs address key loss challenges and improve data availability in self-custodial systems

### What would an attendee learn from this talk?

Attendees will dive into how technologies like FROST, Oblivious Pseudo-Random Functions (OPRFs), time-locks, and Verifiable Random Functions (VRFs) can be combined in practical, impactful ways to address challenges of self-custody, offering solutions that make it secure and resilient.

### Is there anything folks should read up on before they attend this talk?
You should go to the FROST panel!

### Relevant Links
NA for now

# About the Speaker
**Jesse Posner** is an engineer at Block. He works on Bitkey, and the FROST implementation in `secp256k1-zkp`.

**Jurvis Tan** is an engineer at Block working on making it hard to lose your bitcoin at Bitkey.

# Talk Details
### Length of Talk
45m

### Preferred Day/Time Slot 
–

**Comment by miketwenty1** [comment]
noting that @jurvis is open to having this at the NextGen village and prefers to have this during a non technical slot on the mainstage.

**Comment by jurvis** [comment]
@miketwenty1 would NextGen village have video recording equipment so we can record the talk?

**Comment by jurvis** [comment]
hey @iglesiasbrandon @miketwenty1! any updates here?

**Comment by iglesiasbrandon** [comment]
Hey @jurvis this issue has not been accepted yet. If it is, we will comment on here; we have a ton of submissions this year, we are doing our best to accommodate as many as possible.

**Comment by jurvis** [comment]
@iglesiasbrandon when would we know for sure if our talk will be selected / rejected?

**Comment by iglesiasbrandon** [comment]
hey @jurvis, since the conference is next week, its likely we won't be able to accept this issue :( The schedule is pretty much complete unless we have anyone drop out for some reason. I would say lobby con at TABConf is very strong; opening this issue signals to others you are interested in talking about this topic. I wouldn't be surprised if you end up having a bunch of conversations next week about this subject!
