### ISSUE TITLE
Introduction To Hashrate Accounting

### ISSUE THREAD

**Issue by asherp** [TABConf/6.tabconf.com#160]
# Description
### What is this talk about? Give us as many details as possible. 

Hashrate accounting is an often overlooked aspect of both mining operations and hashrate purchases. Mining rigs produce a variable amount of hashrate, owing to the unpredictability of hashrate itself and the myriad operational hazards. This talk explains how we measure hashrate performance over time at [Rigly.io](https://rigly.io/) to account for these effects. This talk will show how to apply time integration in a unit of account - “hashrate days” - to provide an auditable record of performance independent of the pool and hardware.

### What would an attendee learn from this talk?

Attendees will learn to enhance their privacy on chain through the mechanism of hashrate purchases.
They will understand how mining works in practice, from the machines to the proxy to the pool level.
They will learn how to build invoicing systems that leverage hashrate accounting as a form of payment.

### Relevant Links

[Rigly.io](https://rigly.io/) is a marketplace for hashrate, allowing uses to buy hashrate both on-demand and at auction

# About the Speaker

I'm a freelance bitcoin developer, data engineer and physicist. I designed Rigly's hashrate accounting system.

One of my fun side-projects is [audible-markets](https://audible-markets.com/).

### Social Links
[Github](https://github.com/asherp) 
[Twitter](https://x.com/asherp)

# Talk Details
### Length of Talk

30-45m

### Preferred Day/Time Slot

Any time, any where

**Comment by iglesiasbrandon** [comment]
thank you for conducting this talk!
