### ISSUE TITLE
Shinigami: Building a provable Bitcoin VM

### ISSUE THREAD

**Issue by b-j-roberts** [TABConf/6.tabconf.com#162]
# Description
### What is this talk about? Give us as many details as possible. 
Shinigami is an open-source Bitcoin Script VM built in Cairo. Enabling the creation of STARK proofs of generic Bitcoin Script computation, which could be used for a variety of things like extremely fast & secure IBD, Bitcoin Script rollups, secure bridges, and more. I would like to discuss the what, how, and why of building Shinigami and provable programs in general with languages like Cairo. I'd also like to cover lessons learned from the project and how people can get involved.

### What would an attendee learn from this talk?
Creating provable programs is as accessible as ever. This enables secure compression of generic compute, such as Bitcoin Script, at a large scale. STARKs can be used to super-power Bitcoin with or without soft-forks, and bring amazing things to devs.

### Is there anything folks should read up on before they attend this talk?
[Twitter thread on Shinigami](https://x.com/BitcoinWildlife/status/1830468876242727013)

### Relevant Links
[Github](https://github.com/keep-starknet-strange/shinigami)
[Shinigami telegram](https://t.me/ShinigamiStarknet)
[Validating first Bitcoin transaction with shinigami](https://x.com/BrandonR505/status/1831583014289133898)

# About the Speaker

Exploration engineer at StarkWare; primarily focused on exploring project ideas, doing R&D, and building open-source. Heavily interested in mathematics, applied cryptography, STARKs and L2 scaling. A bit of a tech and maths nerd.

### Social Links
[Github](https://github.com/b-j-roberts)
[Twitter](https://x.com/BrandonR505)

# Talk Details
### Length of Talk
15-20 minutes

### Preferred Day/Time Slot 
Any

**Comment by btsea** [comment]
Hi, we have approved this for inclusion in the BitDevs Socratic Village! While this content is not Socratic in nature, we do accept a small number of speakers who are offering non-Socratic content that can't fit on the main stage. Please note we only have two time slots left available, so we do not have flexibility to offer you selection on when you present. It will be between 4-5PM on the last day of the conference. If this is okay, please let us know. 

Thanks!

**Comment by b-j-roberts** [comment]
Hey @btsea , sounds like it would be awesome! Thank ya'll.
That slot works for me; I look forward to attending and sharing!

**Comment by iglesiasbrandon** [comment]
Thank you for hosting this!
