### ISSUE TITLE
Socratic Panel: DLCs in Production

### ISSUE THREAD

**Issue by btsea** [TABConf/6.tabconf.com#164]
# Description 

It has been 7 years since the original DLC paper was published. In this panel we will have a frank dialogue with DLC community members working on the state of the art. 

Some questions we will cover: 

1. Which projects are actively developing products that leverage DLCs and DLC-like constructions?
2. What problems are they solving and why are DLCs the ideal tool?
3. What difficulties have they faced when building/deploying DLC-based systems? 
4. What happened to the DLC Specs project? Why haven't DLCs gained more momentum in the wider developer community?

# Format

This is a Socratic Panel, which means the event will be a two-way dialogue. It is expected for both panel participants and members of the crowd to ask and answer questions.

To begin the panel, each panelist will give a short 5-10 minute presentation on the topic. Once the presentations are complete, the moderator will pose a few questions to stimulate discussion. From here, the crowd and panelists will be offered a chance to steer discussion with their own questions.

## Panelists

- @bennyhodl
- @shehzanmaredia
- @matthewjablack

## Moderator
- TBA

**Comment by btsea** [comment]
Thanks for your participation @bennyhodl, @shehzanmaredia, and @matthewjablack. Please reply with an ACK so we can assign this issue to you. 

Additionally, please see [this document](https://docs.google.com/document/d/1w5-gM0u-El4tVUMSz1CIZtJdGFw1C5dYDsalRJ3wcSM/edit?tab=t.0) on how to prepare. This is not a normal panel, so there are additional requirements. Let me know if you have any questions. Put a thumbs up on this message once you have read through the document. Thank you!

**Comment by matthewjablack** [comment]
ACK

**Comment by bennyhodl** [comment]
ACK

looking forward to a great panel!

**Comment by iglesiasbrandon** [comment]
Thank you for conducting this!
