### ISSUE TITLE
Bitcoin PIPEs: Covenants and ZKPs on Bitcoin Without Protocol Changes.

### ISSUE THREAD

**Issue by nemothenoone** [TABConf/6.tabconf.com#165]
# Description
### What is this talk about? Give us as many details as possible.
This talk is about Bitcoin PIPEs - a concept enabling covenants and ZKPs verification on Bitcoin without any softfork via leveraging QFE extension of an FH-MIPE scheme to encrypt the Schnorr signing key and yield a signature only in case a verification of an IPA-based proof system finishes correctly.

### What would an attendee learn from this talk?

Details of how Bitcoin PIPEs work, I hope to receive some criticism.

### Is there anything folks should read up on before they attend this talk?

There is a paper to read: https://x.com/nemothenoone/status/1843382870901235907
There is a good explanatory thread to take a look into as well: https://x.com/_weidai/status/1843526255045685253?s=46&t=OHVNt-4JbivH56CdK1W_Mw

### Relevant Links

# About the Speaker
### Social Links
Github: https://github.com/alloc-init, https://github.com/nemothenoone
Twitter: https://twitter.com/nemothenoone, https://twitter.com/alloc-init
Website: https://allocin.it

# Talk Details
### Length of Talk
15-20 minutes would be enough. I'm adjustable.

### Preferred Day/Time Slot 
Just pick one yourself - I'll be around anyway.

**Comment by btsea** [comment]
Hi, we have approved this for inclusion in the BitDevs Socratic Village! While this content is not Socratic in nature, we do accept a small number of speakers who are offering non-Socratic content that can't fit on the main stage. Please note we only have two time slots left available, so we do not have flexibility to offer you selection on when you present. It will be between 4-5PM on the last day of the conference. If this is okay, please let us know. 

Thanks!

**Comment by nemothenoone** [comment]
Hey @btsea! Yup, that works!

**Comment by iglesiasbrandon** [comment]
thank you for conducting this!
