### ISSUE TITLE
Lambda calculus and the foundations of functional programming (Silas Pembroke)

### ISSUE THREAD

**Issue by silaspe** [TABConf/6.tabconf.com#170]
# Description

### What is this talk about?

Lambda Calculus is the theoretical basis for functional programming techniques utilized by Bitcoin scripting languages such as Simplicity and programming languages such as Haskell, Lisp, and Clojure. It is a foundational system for understanding and defining computation through function abstraction and application. This talk provides a basic introduction to lambda calculus and and applications to beta reduction, currying, Church numerals, higher order functions (combinators), and immutability.

### What would an attendee learn from this talk?

Attendees will walk away with a deeper understanding of the principles underlying functional programming techniques, such as composition, immutability, currying, and flow control.

### Is there anything folks should read up on before they attend this talk?

A basic knowledge of mathematics and programming are helpful, though not necessary.

### Relevant Links
Silas's in-depth summary of [lambda calculus](https://silaspe.github.io/maths/lcr.html)
[Lambda Calculus Basics](https://en.wikipedia.org/wiki/Lambda_calculus)
Simplicity [White Paper](https://blockstream.com/simplicity.pdf)
[Miniscript Overview](https://github.com/bitcoin/bitcoin/tree/master/doc/miniscript.md)

# About the Speaker

Silas is a 10 year old mathematician with a passion for computer science. He has spent the last four months studying the lambda calculus in a formal setting and is excited to share what he's learned.

### Social Links

[Website ](https://silaspe.github.io/maths/)

[Github](https://github.com/silaspe)

# Talk Details
### Length of Talk

45m

### Preferred Day/Time Slot 

Day 4

**Comment by iglesiasbrandon** [comment]
thank you for conducting this talk!
