### ISSUE TITLE
Explainer Contest - Name TBD

### ISSUE THREAD

**Issue by miketwenty1** [TABConf/6.tabconf.com#171]
# Description
The contest at the tech conference will focus on explaining complex ideas clearly. Participants will have a maximum of 6 minutes to present a topic that many people struggle to understand. Three audience members, who know little or nothing about the topic, will be chosen to listen to the presentation.

An expert judge will prepare at least 7 questions on the subject, which the presenter will see beforehand. This allows the presenter to clarify important points. The presenter will also be able to briefly assess the technical background of the audience members to adjust the presentation level accordingly.

During the talk, a secondary person (the "question picker") will choose 3 of the pre-prepared questions to ask the panelists. The choice is at the question picker's discretion, possibly aiming to highlight gaps or opportunities for learning.

After the presentation, the judge will ask Panelist A one of the selected questions, and they will have 30 seconds to answer. If incorrect, the question moves to the next panelist, and if all fail, the judge provides the correct answer. The next questions start with Panelists B and C respectively.

Points will be awarded to both the presenter and panelists, with possible additional scoring criteria. Tie-breakers may be resolved by audience applause. The best-performing panelist may stay for the next round. Awards and criteria for winning awards for both the best explainer and best understander is still TBD. 

The goal will be to get 4 topics covered within 1 hour.
 

Dustin has offered to make one of the topics "splicing" he is also helping flush this idea out with me and is helping come up with a name for this type of event.

|Topic|Presenter|Judge|
|-----|-----|-----|
|Splicing|Dusty|Tidwell|
|zkCoins|Ronin Linus|Jonas Nick|
|Stratum v2|Matt Corallo|Average Gary|
|Payjoin|Dan Gould|Jad|

Condensed Summary:
- A presenters gives a quick 6 minute talks on this interesting but confusing topic.
- 3 questions then picked for a judge.
- Audience panelist participation opportunities for fun engagement to see how well topic was explained.
- Judging done to evaluate presenter and panelist.
- Scoring and prizes and be light hearted. 
- Knowledge and education on tough concepts is the goal.

### Length of the panel discussion
- 1 hour
### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by miketwenty1** [comment]
I think Ark and BitVM might be good topics here as well.

**Comment by RobinLinus** [comment]
zkCoins might be an interesting topic. 


------ 
I probably won't be there on Wednesday.

**Comment by miketwenty1** [comment]
> zkCoins might be an interesting topic. Maybe Jonas Nick could be a judge
> 
> I probably won't be there on Wednesday.

@RobinLinus this will be on friday at 5pm

**Comment by average-gary** [comment]
Stratum v2
@TheBlueMatt presenting.
I'll judge.

**Comment by iglesiasbrandon** [comment]
Thank you for hosting this gameshow!
