### ISSUE TITLE
Freedom Tech for Disaster Relief

### ISSUE THREAD

**Issue by average-gary** [TABConf/6.tabconf.com#176]
# Description
### What is this talk about? Give us as many details as possible. 
Bitcoin Veterans use of Bitcoin and Meshtastic in WNC to help with disaster relief.
Freedom tech working in
### What would an attendee learn from this talk?
How Meshtastic was used practically in the real world to save lives and restore comms for a community.
### Is there anything folks should read up on before they attend this talk?
There 
https://x.com/BitcoinVeterans
https://meshtastic.org
### Relevant Links

# About the Speaker
Shane Hazel
Unapologetic Freedom Maximalist / Producer & host of The Shane Hazel Show & Bitcoin Veterans Podcasts / USMC Veteran 🍄 Open Your Mind

https://x.com/ShaneTHazel

### Social Links
Github 
Twitter
Website

# Talk Details
### Length of Talk
30min
### Preferred Day/Time Slot 
Friday or Saturday

**Comment by iglesiasbrandon** [comment]
thank you for conducting this talk!
