### ISSUE TITLE
HODLween - Satellite After Party Oct 26th!

### ISSUE THREAD

**Issue by lizmparrish** [TABConf/6.tabconf.com#18]
# Description
HODLween  - Satellite After Party, SATurday, Oct 26th!

### Event Description
HODLween is a bitcoin themed halloween costume party, and is the longest running one in the world! Join us on October 26th, 2024, for the 4th annual celebration of HODLween, where we’ll also be marking Bitcoin’s 16th birthday (October 31st, 2008).

🍸OPEN BAR
₿ $1,000 COSTUME CONTEST
🕺LIVE MUSIC
🔮TAROT CARD READINGS
🪄MAGIC PERFORMANCES
₿ HIDDEN BITCOIN
🏓CORN HOLE, PING PONG, AND MORE!

### Date and time
Saturday, Oct 26th ~ 8PM-2AM

### Location
[Ambient+ Studio, 585 Wells St SW Unit A Atlanta, GA 30312](https://www.ambientplusstudio.com/map-1)

### Anything people should know before coming?
Attendees are encouraged to dress up in their best costumes, with the suggestion of Satoshi Nakamoto-themed attire!
More info here https://hodlween.party/#faq

### Relevant Links
https://hodlween.party/  
![hodlween-btcmedia-1200x600 (1)](https://github.com/TABConf/6.tabconf.com/assets/66025210/89c10158-78db-4280-be65-cd6230aba0f0)

**Comment by miketwenty1** [comment]
We'll try to get back soon on availability for Oct 26th. Thanks for the submission!

**Comment by partyp** [comment]
Excited to see HODLween at TAB!

**Comment by lizmparrish** [comment]
@miketwenty1 any updates for Oct 26th HODLween? Want to get the planning started 🎃

**Comment by iglesiasbrandon** [comment]
Hey @lizmparrishwe, we do not have any plans on Saturday, Oct 26th, from 7 PM to 12 AM. It's likely the conference itself will end between 5:00 and 5:30 PM. I think this can be the thing to do! What do you need from us to start planning?

**Comment by lizmparrish** [comment]
Thanks @iglesiasbrandon ! An idea of what rooms and/or rooms we could take over. Will this be in conjunction with another village? Will need to have space for musicians and AV

**Comment by delgajh** [comment]
Hodlween going on the road. Let's do this!

**Comment by Tselly** [comment]
Finally got GitHub, what's up fam?

**Comment by briimhd** [comment]
hey @lizmparrish can you message me on tg about this event? We are adding all side events and main events on Evento, and I'd like to add Hodlween as an Evento. 

Check out the tabconf page - we will be adding more events this week.
https://evento.so/tabconf

my tg is theoriginalbhd

**Comment by bnonni** [comment]
Hey, @lizmparrish we have accepted this issue as a satellite event TABConf 6! Thanks for submitting!

**Comment by partyp** [comment]
Very excited for this years HODLween! How can we update the "length" and "time slot" @miketwenty1 ?

**Comment by iglesiasbrandon** [comment]
hey @partyp those fields have been updated

**Comment by marumover** [comment]
I am so looking forward to this party! I went last year to it in Charlotte and it was so cool to see all the creative Bitcoin related costumes! and I absolutely love the privacy theme!

**Comment by partyp** [comment]
Costumes are definitely my favorite too and the hidden bitcoin is a close second. Excited to see how the hidden bitcoin is executed. What service is being used to redeem sats when guests find bitcoin this year?

**Comment by delgajh** [comment]
I'm not sure but word on the streets is that Satoshi Nakamoto himself went
to the 2nd Hodlween and lost the "Dress like Satoshi Nakamoto" costume
contest.
