### ISSUE TITLE
tabconf hackathon project: dlchess

### ISSUE THREAD

**Issue by stutxo** [TABConf/6.tabconf.com#181]
![ZBD x PlebLab Hackathon Image](https://pbs.twimg.com/media/GW2IHa2WYAE71ca?format=jpg&name=large)

# 🚀 TABConf 6 Hackathon Submission

### Team Members 👥

- @stutxo

### Project Description 📝

Betting on chess games with DLC's. I have an oracle server that provides the adaptor signatures to use in the bitcoin scripts which players will be able to spend depending on the outcome of a game using the lichess.com api.

There is a taproot script leaf spend for:

white win, black win, draw and game timeout (if the attestation server dies) 

Players can also use their combined keys to key spend the transaction if they collaborate

### Technical Implementation 💻

adaptor signatures with taproot spends.

I am using the `schnorr_fun` library to create adaptor signatures to sign messages for the outcomes of a chess game via the lichess api. 

I create a taproot address that locks the funds and only allows white or black player to withdraw winnings if the oracle sends the signature for a white or black win. 

both plays sign a draw transaction that returns their funds if the draw signature is returned

There is also a timeout script that the players can use to return funds if the oracle server dies

### User Experience & Design 🎨

For the hackathon, i created a script to simulate a game and test all spending paths, this could easily be made in to a frontend later

### Innovation & Creativity 💡

using taproot and adaptor sigs to create dlc's 

### Potential Impact 🌍

can be used for any oracle style bitcoin contract, as long as you trust the oracle server 

### Business Model 💼

Its peer to peer gambling so no real business model, its just for fun. 

### Demo Video 🎥

https://www.loom.com/share/81e9b1ea378748848bd76f47c08129e9?sid=7a806031-d7c5-4144-a298-a84ef6bf6af8

### GitHub Repository 📂

https://github.com/stutxo/dlchess

### Future Plans 🔮

I plan to run the attestation server so it can be used by anyone as a nostr hidden service. Also plan to make a web frontend at some point so it can be played on the web

**Comment by zantoshi** [comment]
Accepted @stutxo
