### ISSUE TITLE
tabconf hackathon project: pepe.vote

### ISSUE THREAD

**Issue by bitcoin-coder-bob** [TABConf/6.tabconf.com#183]
---
name: TABConf 6 Hackathon Submission
about: Submit your Hackathon project for TABConf 6!
title: 'pepe.vote'
labels: 'TABConf 6 Hackathon Submission'
assignees: ''

---

![ZBD x PlebLab Hackathon Image](https://pbs.twimg.com/media/GW2IHa2WYAE71ca?format=jpg&name=large)

# 🚀 TABConf 6 Hackathon Submission

### Team Members 👥

- Vic - Jr. Senior Javascript Dev
- Tee8z - Alpha Prompt Engineer
- BitcoinCoderBob - Chief Pepe Officer

### Project Description 📝

A musuem of the finest Pepe portraits featured in order by community driven votes, facilitated by nostr events.

### Technical Implementation 💻

Images stored in nostr.build and images and votes relayed by nostr events. Votes counted by polling for relevant vote-kind nostr events and tallying.

### User Experience & Design 🎨

Users are prompted with 2 pepe images and to vote for their favorite of the 2. Users can then view the global leaderboard to see popular Pepe images ranked from highest to lowest vote count.

### Innovation & Creativity 💡

A new way to conduct polls on nostr, without zaps.

### Potential Impact 🌍

Polls on nostr tradtionally relied on users sending a zap along with their vote selection. By creating 2 new nostr "kind" with special tags we have events that can be aggregated to count vote totals. This kind of voting can be used to tally votes for any type of election (popular images, election candidates, best hackathon project, etc.)

### Business Model 💼

Each image can be selected and zapped to pay the creator of each image.

### Demo Video 🎥

https://www.loom.com/share/50f1363292d7413788e1e869da5e439d?sid=619b41c8-eec5-457c-b3eb-51eab73a393b

### GitHub Repository 📂

https://github.com/pepe-vote/pepe.vote

### Additional Resources (Optional) 📚

- [https://pepe.vote](https://pepe.vote)
- [nostr.build](nostr.build)

### Future Plans 🔮

Ability to zap creators of each image, ELO scoring for ranking instead of a simple total vote count.

### Feedback for Organizers (Optional) 📣

This project inspired by HotOrNot.com but with a modern nostr twist. Sign into the site with a nostr extension in order to vote. The leaderboard can be viewed without signing in. All votes stored as nostr events, no server nor database! Works on browser or mobile! Check it out at [https://pepe.vote](https://pepe.vote)

**Comment by zantoshi** [comment]
Accepted @bitcoin-coder-bob
