### ISSUE TITLE
DRAFT: PANEL - Consensus Change Queue, The good, the bad, and the bias. (~probably not recorded).

### ISSUE THREAD

**Issue by miketwenty1** [TABConf/6.tabconf.com#19]
# Description
### What is this panel discussion about? Please give us as many details as possible. 
- If any of the panelist don't want to be recorded, we'll just opt-out of the recording if we feel that person would benefit the panel.
- There are many proposals, BIPS, ideas, etc, that are interesting and could potential bring benefit to bitcoin.
- What will the next fork be? Is it possible to plan what it will be? ~~What is the latest with BIP 8/9/ST (Speedy Trial) in terms to activation method?~~
- What implicit biases are there that could make this process not work as intended? Since usually only 1 major change happens at a time or is being actively voted on, (via activation methods), some champions of various ideas may be less enthused to be collaborative.
### What would an attendee learn from this talk?
- Insight into the Bitcoin consensus process.
### Is there anything folks should read up on before they attend this talk?
- Reading up on How Segwit v0 and Taproot was activated would be a good pre-reading.
### Relevant Links

# About the panelist (Looking for panelist)
### Social Links
- Some ideal candidates would be some of the people on this thread: https://gist.github.com/michaelfolkson/92899f27f1ab30aa2ebee82314f8fe7f, Luke-Jr, achow101, would also be good, and really anyone who is actively looking to get a change into Bitcoin would be a good candidate for this panel. 
- Moderator, honestly could be many people, I preferably would like a technical person as moderator who isn't actively trying to get a change into bitcoin and also isn't dogmatic about ossification.

# Panel Discussion Details
### Length of the panel discussion
- 1 hr
### Preferred Day/Time Slot 
- None
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by miketwenty1** [comment]
After discussing with a few people removing activation as a topic as it's big enough to be a panel of it's own. https://github.com/TABConf/6.tabconf.com/issues/23

**Comment by iglesiasbrandon** [comment]
closing this issue, there does not seem to be interest in the topic at this time.
