### ISSUE TITLE
ZBD x PlebLab TABconf Hackathon - Season 2

### ISSUE THREAD

**Issue by zantoshi** [TABConf/6.tabconf.com#21]
![image](https://github.com/TABConf/6.tabconf.com/assets/127369669/d7881b11-caee-496a-9064-744352d56ae8)

# Description
### What is this workshop about? Provide as many details as possible. 

I want to organize and host a TABconf hackathon similar to last year on Lightning & Nostr. 

### What would an attendee learn from this workshop?
They'd get to collaborate and build extremely innovative products with the very best builders in the industry.

### Is there anything attendees should read up on before they attend this talk?
[TABconf Hackathon Pitches](https://www.youtube.com/watch?v=Mwf7TF2PB7o&list=PLaMJnpgudSADahelMCf1mjcm6VFRAO5ux)
[Landing page](https://tabconf.zbd.gg/)

### Is there anything attendees should set up before the workshop?
We will run the hackathon 2 weeks before TABconf and then semifinalists will pitch their project at the conference itself.

### Relevant Links
[emeralize.app](emeralize.app) for education
[ghl.gg](www.ghl.gg) - WIP hackathon platform. Should be ready for next week.

# About the Speaker
### Social Links
[santos.lol](santos.lol) for my portfolio and social links.

# Workshop Details
### Length of workshop & Preferred Day/Time Slot 
2-4 Hours for one day. Perhaps Pitches could take place on Builder's Day and then we could announce the winners at the Closing Ceremony but could also potentially take place in the Lightning Village.

**Comment by thrillerxx** [comment]
Pleblab totally down to help out with this again! I think now with GHL we can take it to the next level.

**Comment by zantoshi** [comment]
LFG 🚀

**Comment by iglesiasbrandon** [comment]
I'm looking forward to another TABConf Hackathon :) This issue has been accepted for TABConf 6. I think we should set this up in the builder days area! let me know what your thinking.

**Comment by aassoiants** [comment]
Will y'all want any help coaching and supporting participants with product research, customer profiling, strategy, rapid prototyping, or other aspects of building product? 

Happy to support buidlers!

**Comment by iglesiasbrandon** [comment]
Thank you for conducting another amazing hackathon!
