### ISSUE TITLE
Last year's Tabconf dates in volunteer form

### ISSUE THREAD

**Issue by micriver** [TABConf/6.tabconf.com#22]
**Describe the bug**
The Volunteer Google Form linked on the website points to the 2023 version, causing users to see outdated information and potentially impacting submissions.

**To Reproduce (if applicable)**
1. Visit the website, check the nav bar on the left and click on the volunteer link.
2. The form that opens will have information and dates specific to 2023.

**Expected behavior**
Link to the 2024 Volunteer Sign-Up Form, displaying Tabconf 2024 dates.

**Screenshots**
NA

**Additional context**
The line to change the link in the code can be found on line 126:
https://github.com/TABConf/6.tabconf.com/blob/75f22a7492c61c9d254c5c304734e9de5048dde4/_layouts/default.html#L126

I wanted to bring it to your attention to ensure a smooth volunteer sign-up process. I'm happy to help further if needed!

**Comment by miketwenty1** [comment]
@micriver did you want to try to open a PR to fix this? Let me know. Thanks for identifying the issue.

**Comment by miketwenty1** [comment]
@micriver I'm understanding this isn't something you could of made a PR for, and we've fixed it since you opened this issue. I'm closing this, thank you so much for flagging. Clicking Volunteering signup will take you to TABConf 6.
