### ISSUE TITLE
DRAFT: Activation Methods 

### ISSUE THREAD

**Issue by miketwenty1** [TABConf/6.tabconf.com#23]
# Description
### Relevant Links

# About the panelist
### Social Links
GitHub 
Twitter
Website

# Panel Discussion Details
### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by iglesiasbrandon** [comment]
closing this issue.
