### ISSUE TITLE
Branta Builder Day Table

### ISSUE THREAD

**Issue by keith-gardner** [TABConf/6.tabconf.com#24]
# Description
[Branta](https://branta.pro/) - Guardrails for Bitcoin & Lightning

### What is this project about? Please give us as many details as possible.
Branta offers instant address verification for bitcoin and lightning

We are platform agnostic - on Linux/Mac/Windows

### Is it a FOSS or Open Source project?

Branta Core is FOSS

### What would an attendee learn from visiting this projects table at Builder Days?
The ins & outs of Bitcoin Security, PGP, integrity checking, Mac/Xcode, Windows/.NET, our build process, and general malware

### Is there anything people should read up on before finding the table at Builder Day?
Looking at our [website](https://branta.pro/) or [github](https://github.com/BrantaOps) would be great, but isn't necessary :) 
### Relevant Links
GitHub Repo: https://github.com/BrantaOps

# Project Details
### Who will run the table? Are those people current contributors or maintainers who can answer questions and get people onboarded?
Keith is the Founder of Branta and will run the table. He authored the Mac version and came up with the idea (can onboard anyone to any of the repos).
Another maintainer (Kyle for Windows) may be able to attend. 

# The Software

<img width="1440" alt="clipboard view" src="https://github.com/user-attachments/assets/71738778-1d57-409a-b2f0-9428a0b60da4">

<img width="1440" alt="m of n" src="https://github.com/user-attachments/assets/aa0e62ae-ce14-468f-946c-9d16ab1bc240">

<img width="1440" alt="vaults" src="https://github.com/user-attachments/assets/a59c36bf-0e38-4e9a-b868-59156cf68fc6">

**Comment by bnonni** [comment]
Hey @keith-gardner, thank you for submitting this issue! It's been accepted for builder days 1 & 2!

**Comment by miketwenty1** [comment]
@keith-gardner help me understand, what of this is a product for sale and what is open source?
Also can you link to the actual open source repo for the project?

**Comment by keith-gardner** [comment]
Hi @bnonni and @miketwenty1 ! Thanks for the reply.

Since posting in February, we pivoted Branta. The new product isn't open source yet.

Totally understand if it makes more sense to give the table to a more active team right now.

We'll be back open source, but the timing may not be right for Tab this year.

**Comment by iglesiasbrandon** [comment]
ok that makes sense @keith-gardner. I am going to close this issue then and if the new product is launched and open source before the conf we can open another builder days project and add it.

**Comment by keith-gardner** [comment]
Hi @iglesiasbrandon and @miketwenty1 -

Our Code is back [open source,](https://github.com/BrantaOps/branta-core) possible to reopen this?
