### ISSUE TITLE
k-12 bitcoin education Brainstorming Session

### ISSUE THREAD

**Issue by SkyExile** [TABConf/6.tabconf.com#28]
Bitcoin should be taught to future generations the way math, reading, history, etc. are. Starting in kindergarten, and advancing up through high school graduation. We always talk about making bitcoin simpler for the boomers and the grandmas, but if kids are taught it from an early age, with the courses getting more and more advanced as the years progress, they'd be better at it than any of us, and would not need the tradeoffs of simplification. 

Is anyone creating a bitcoin educational course for k-12, public, private, and homeschool. I know I've seen stuff for little kids, but what about the AP courses for highschoolers?

I'm unfortuantely not the one knowledgeable enough to teach this or create it. I just think it should be done, so my kids can school me. I think people should start discussing, brainstorming, planning, and creating it.

What if we don't need to simplify things as much as we think, we just need it taught at an early age like math and physics and science, which do not get simpler as time goes on?

**Comment by bnonni** [comment]
@SkyExile thanks for submitting an issue for consideration! While this issue isn't a structured talk, workshop, etc., this is exactly what we use Github for: discussing, brainstorming, planning, and creating.

That said, I know some ppl that come to mind that might be willing and able to do this. Stand by!

**Comment by EllyPembroke** [comment]
This could be a great panel discussion at Next Gen Village. We had a panel discussion on homeschooling last year, including teaching our children about bitcoin. I like the idea of a more focused discussion on curriculum and making bitcoin both accessible and interesting for kids and teens. Jesse and SkyExile, would you two be open to speaking on the panel? If anyone else is interested, let me know below or contact me on X or telegram

**Comment by iglesiasbrandon** [comment]
hey @EllyPembroke do you want to assign this issue to the NextGen Village?

**Comment by SkyExile** [comment]
I promise you Elly I am not qualified to speak on this. Not a programmer, not a curriculum writer. I just think it's a damn good idea. But other than the suggestion of it.... not sure I have a lot more to offer. I'm not even sure what a 12th grader is capable of, other than that it's more than me currently if they've studied since kindergarten. I mean... I'm not even sure what all would be included. I think the technical side of it is the main thing that everyone will agree on to a certain point. All the philosophy can get less consensus. I just would want a 12th grader to have the technical knowledge to then go to college and work on the programming stuff that is new and not yet consensus. Maybe that's a good goal for it all. I'd think a sixth grader could understand UTXOs.

**Comment by SkyExile** [comment]
Instead of a panel..... could there be some kind of brainstorming session?

**Comment by SkyExile** [comment]
yeah, that sounds fun, and it is kind of at that stage

**Comment by EllyPembroke** [comment]
Okay, a brainstorming session it is! @JesseMarkowitz can I assign you to this issue, would you lead the session and maybe prepare a couple of questions/topics to organize our discussion?

**Comment by EllyPembroke** [comment]
@SkyExile can you put 'brainstorming session" in the title so people know instantly what to expect?

**Comment by SkyExile** [comment]
@JesseMarkowitz I will!
@EllyPembroke Done.

:)

**Comment by BitstorianOfficial** [comment]
Very excited for this brainstorming session! Okay, I'm in higher ed not k-12, but I think that we - professors, school teachers, and home educators - should collaborate more on building out curricula and pedagogies. At my university, I run a comprehensive Bitcoin instruction program (BIP) and am looking forward to learning and sharing with you all.

**Comment by iglesiasbrandon** [comment]
thank you for hosting this!
