### ISSUE TITLE
Nostr Village!

### ISSUE THREAD

**Issue by zantoshi** [TABConf/6.tabconf.com#29]
# Description
### What is this idea? Give us as many details as possible. 

Just like we have the Lightning Village, etc. I want to request that we have a Nostr Village! 

### What would an attendee gain from this?

Immense value learning about nostr, building in nostr, and contributing to the nostr space.

### Relevant Links

I recently did the workshop day for BitBlockBoom and the content was a hit! Check out the schedule: 
![GKSGwa5XkAArmJk](https://github.com/TABConf/6.tabconf.com/assets/127369669/099c2384-b133-4781-88e9-8b8cb67d68f4)

**Comment by murchandamus** [comment]
Are you proposing that you will organize both the Lightning and the Nostr village? That seems like a lot for one person.

**Comment by shreyav** [comment]
Hi! I was wondering if the Nostr Village is confirmed to take place at TABConf this year. If it is, we would love the opportunity to talk about some of the work we've been doing with NWC and Client App Registration via Nostr.

**Comment by zantoshi** [comment]
@murchandamus I think you are right, I am going to close this issue

**Comment by miketwenty1** [comment]
For anyone looking at this closed issue, if you want to propose another Nostr village, open a new issue with relevant details.
