### ISSUE TITLE
Lightning Village

### ISSUE THREAD

**Issue by zantoshi** [TABConf/6.tabconf.com#30]
# Description
### What is this idea? Give us as many details as possible. 

I want a Lightning Village! Nothing different than what we did last year and the time before that, etc.

### What would an attendee gain from this?

Action packed content filled with amazing builders in the space, the basics, and what's new!

### Relevant Links

https://github.com/orgs/TABConf/projects/1/views/8

**Comment by beeforbacon** [comment]
I want the lightning powered beer tap back!

**Comment by miketwenty1** [comment]
> I want the lightning powered beer tap back!

Who's doing this the best right now?

**Comment by miketwenty1** [comment]
@zantoshi bump here, not sure if this is still being planned.

**Comment by zantoshi** [comment]
I think focusing on a great hackathon will be a task in of itself. Closing this out.
