### ISSUE TITLE
Learn how to be a sovereign Nostritch! Get zaps to and from your own LND node fast and easy. 

### ISSUE THREAD

**Issue by beeforbacon** [TABConf/6.tabconf.com#31]
# Description 

Have you been using nostr for a while? Are you feeling dirty getting zaps to and from some custodial wallet? Wouldn't you rather be a sovereign zapper? If so, then this workshop is for you! 

In this workshop we will take a normal LND lightning node and use LNC to easily connect it to an Alby extension to zap others straight from our own node.

We will then learn how to use the free nostr toolkit (provided by Voltage) to enable zaps directly to our Lightning Node. In the workshop, the lightning node being used will be on Voltage for easy demonstration, but if you have a LND node at home on your own server, the steps are the same. 

If time allows, we will talk briefly about the bare minimum strategy needed for basically hands-off node management. 

### Is there anything attendees should read up on before they attend this talk?
It helps if you already have a nostr private key to hook up to the Alby extension and access to Lightning Terminal in some way (although you can just use Voltage and follow along as well). 

### Is there anything attendees should set up before the workshop?
If you are looking to follow along, setting up a Voltage account beforehand at voltage.cloud would be ideal. Either that or have access to Lightning Terminal from your own server in some way is fine too. 

**Note**: We will NOT be setting up an LNURL service or anything super technical. No coding or command line required. 

# Relevant Links
voltage.cloud

**About the Speaker**
Nate (aka beeforbacon) is a Support Engineer at Voltage and has been a lightning network nerd since the beginning. 

### Social Links
nostr: bluegoat@vlt.ge

# Workshop Details

**Comment by iglesiasbrandon** [comment]
Hey, @beeforbacon , this issue has been accepted for TABConf 6! We are looking forward to it!

**Comment by miketwenty1** [comment]
@beeforbacon  

We are collecting an additional attribute for the workshops. Please update your issue and include a line item on the difficulty level of the workshop with either "Beginner", "Intermediate", or "Advanced".

- Beginner: would be no prior knowledge needed, very few technical skills required for workshop
- Intermediate: At least some knowledge needed to not be lost, technical skills, Comp Sci, IT related experience is greatly beneficial
- Advanced: Potentially a strong working knowledge of certain technologies, libraries, fundamentals, Comp Sci, and related protocols.

Error on the side of more advanced than less advanced as we want to set strong expectations. Depending on what you pick please gauge your workshop accordingly.

**Comment by miketwenty1** [comment]
closed this based on conversation. @beeforbacon
