### ISSUE TITLE
What does scaling actually mean?

### ISSUE THREAD

**Issue by niteshbalusu11** [TABConf/6.tabconf.com#32]
# Description
Me and Alex Lewin were talking about this couple of days ago and I found our conversation very interesting. What actually is scaling from consensus changes? When we talk about scaling with soft forks like covenants or drivechains or the 1million other ideas, are we really getting the true non custodial nature of Bitcoin like owning keys to a UTXO or are we just trying to get to a world where we come as close as possible to it? The base chain is always going to be limited by block size and how much the utxo set can grow. In spectrum of 0-100 where 0 being holding your own keys to utxos to 100 being Bitcoin ETFs, where would all these consensus changes actually land you?

### What would an attendee learn from this talk?

- what does scaling truly mean. 
- are we actually scaling and can everyone really own keys to utxos on chain. 
- what are the trade offs. 

### Relevant Links

# About the Speaker
### Social Links
Github 
Twitter
Website

# Talk Details
### Length of Talk
30 mins (maybe)

### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by bnonni** [comment]
@niteshbalusu11 we've moved this talk into "Under Consideration" because we think its a great idea, but we need some more information, and we need clarity on who you think should speak. If you can help us refine the details and find a speaker, we'll accept it.

**Comment by murchandamus** [comment]
Possibly interesting for whomever will speak: https://bitcoin.stackexchange.com/a/66534/5406

**Comment by iglesiasbrandon** [comment]
Hey @niteshbalusu11 what do you think about converting this issue to a panel instead of a talk? it might be interesting to hear different perspectives on the definition of scaling.

**Comment by niteshbalusu11** [comment]
Sure, I don't mind it being a panel. Idk, if we found speakers for this so far though.

**Comment by murchandamus** [comment]
I’m not following the introspection debate closely enough to give a talk on this, but I could perhaps join a panel

**Comment by bnonni** [comment]
@murchandamus any suggestions for panel speakers?

**Comment by bnonni** [comment]
@niteshbalusu11 have you been able to find any panelists?

**Comment by niteshbalusu11** [comment]
> @niteshbalusu11 have you been able to find any panelists?

No luck.

**Comment by adiabat** [comment]
Hi - I'd be interested in joining this panel if it's happening.  I think about scaling in Bitcoin a lot and think this is a huge question / topic right now.

**Comment by niteshbalusu11** [comment]
@bnonni and @iglesiasbrandon looks like we have 2 people ready. Need one more person I suppose?

**Comment by murchandamus** [comment]
Are you counting me or not? ;)

**Comment by niteshbalusu11** [comment]
> Are you counting me or not? ;)

2 including you.
