### ISSUE TITLE
Ocean Mining Pool, ~1 year insight and misconceptions

### ISSUE THREAD

**Issue by miketwenty1** [TABConf/6.tabconf.com#33]
# Description
### What is this talk about? Give us as many details as possible. 

I would ideally like Bitcoin Mechanic [GrassFedBitcoin](https://x.com/GrassFedBitcoin)  to give a talk on the most interesting aspects of building and working at Ocean. Ocean has done many things differently from other mining pools. I think covering the top interesting facts and stats, as well as common misconceptions, would make for a great talk. A final idea could be sharing thoughts on the future of mining and theories on how things might change.

### What would an attendee learn from this talk?
People interested in what Ocean is doing from a business or technical perspective, or miners that may want to use Ocean's services.

### Is there anything folks should read up on before they attend this talk?
https://ocean.xyz/ is probably a good place to start

### Relevant Links

# About the Speaker
- No speaker verified for the talk as of now.
### Social Links
Github 
Twitter
Website

# Talk Details
### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by iglesiasbrandon** [comment]
Ocean is a lost fish... Just keep swimming
