### ISSUE TITLE
Legal Panel - Coinjoins, Federations, Custodians - Bitcoin without jail time

### ISSUE THREAD

**Issue by miketwenty1** [TABConf/6.tabconf.com#34]
# Description
### What is this panel discussion about? Please give us as many details as possible. 
Look for either technical or legal individuals for the panel.

I would like a talk stacked with legal and technical experts that can discuss the nuance of what is and isn't legal and what is in the "grey space".

- Open to keeping this unrecorded if participants prefer.

Some potential panel topics:
- What did Samourai and Tornado Cash do "wrong"?
- What should people founding Bitcoin companies understand to avoid legal trouble?
- What is the grey space that is undefined and what should we pay attention to?
- Are some federations immune to these issues based on their design?

### Relevant Links

# About the panelist
### Social Links
GitHub 
Twitter
Website

# Panel Discussion Details
### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by russeree** [comment]
[Joe Calisari ](https://twitter.com/JoeCarlasare) Has done talks at various conferences about the US judicial system and it's interactions with Bitcoin.

**Comment by BitcoinBrief** [comment]
I'm happy to speak on this topic. Career long appellate attorney and founder of [Open Source Justice Foundation](https://OSJF.org). 

Aaron Daniel
[Newsletter/blog](https://bitcoinbrief.io)
@wadaniel (Twitter)
[Nostr](https://snort.social/nprofile1qqsdprynz204esjj4yqhhaf0jzzsvzcswe3q5kxddy3fkv0rw0hue8cfmcgwp)

**Comment by BitcoinBrief** [comment]
I'm still interested in presenting on state of the law and pending court cases.  Happy to do this as a solo presentation.

**Comment by asherp** [comment]
@BitcoinBrief If you're still available, how much time would you need to do a solo presentation?

**Comment by andrewlunde** [comment]
Just adding my upvote to this one.  I think a legal debriefing would be helpful and if not, I'll take BB out for beers.  -Andrew

**Comment by EllyPembroke** [comment]
@BitcoinBrief @andrewlunde we agree! Does Saturday at 10:30 work for you? Can you update the title and description to reflect that this is a solo talk and some details about your talk? Thanks!

**Comment by BitcoinBrief** [comment]
> @BitcoinBrief @andrewlunde we agree! Does Saturday at 10:30 work for you? Can you update the title and description to reflect that this is a solo talk and some details about your talk? Thanks!

Thanks for the interest, everyone.  Unfortunately I'll be leaving Saturday.  Let's spike this one for next year and I'll make sure to do a full presentation with more updates and hopefully some additional speakers.

I'll be around the conference, though, so more than happy to share my thoughts on the Samourai, Tornado Cash, and Bitcoin Fog prosecutions.  

See everyone soon!

**Comment by EllyPembroke** [comment]
@BitcoinBrief We can adjust the schedule for you if you prefer a Friday 10:30 time slot. Or did you change your mind about presenting?

**Comment by BitcoinBrief** [comment]
> @BitcoinBrief We can adjust the schedule for you if you prefer a Friday 10:30 time slot. Or did you change your mind about presenting?

Thanks for trying to accommodate! This talk came together a bit too late for me to prepare something meaningful, unfortunately. Let's work on putting a full panel together next year further in advance. I know some top notch Bitcoiner attorneys that would participate. 

Next year we should have a lot more clarity on the regulatory/enforcement landscape, too.

**Comment by asherp** [comment]
Closing till next year!
