### ISSUE TITLE
Build Your Own Layer Two

### ISSUE THREAD

**Issue by supertestnet** [TABConf/6.tabconf.com#35]
# Description

There seem to be about 50 fake bitcoin "layer two"s out there, and lightning is the only "real" one. In this workshop you'll "learn by doing." You'll not only learn the differences between real and fake layer twos, but also, by the end of the session, you'll have built your own L2 from scratch -- either a real one or a fake one, your choice!

# About the Speaker

Super is a freelance software developer focused on bitcoin, lightning, nostr, bitvm, and, most recently, hedgehog

### Social Links
Github: [github.com/supertestnet](https://github.com/supertestnet)
Twitter: [twitter.com/super_testnet](https://twitter.com/super_testnet)
Nostr: [Super Testnet](https://njump.me/nprofile1qy88wumn8ghj7mn0wvhxcmmv9uq32amnwvaz7tmwdaehgu3wdau8gu3wv3jhvtcpz4mhxue69uhhyetvv9ujumn0wd68ytnzvuhsqgpps055wkzgr583ynaaj0zkej4ytel9gh8whr2jsj8esfflf9aew5p96hus)
Telegram: [t.me/supertestnet](https://t.me/supertestnet)
Youtube: [youtube.com/@highlevelbitcoin](https://youtube.com/@highlevelbitcoin)
Website: [supertestnet.org](https://supertestnet.org)

# Workshop Details

### Preferred Day/Time Slot: no preference

# Difficulty level
Beginner

**Comment by miketwenty1** [comment]
I can vouch for @supertestnet he has a good track record of delivering and gave a fun interactive demo/workshop at Bitcoin++ recently. He's got my vote, although Around Sept it may be nice to start hammering out details here.

**Comment by bobsummerwill** [comment]
This sounds great!

**Comment by iglesiasbrandon** [comment]
Hey @supertestnet, thank you for proposing this issue! It has been accepted for TABConf 6. As we get closer to the conf, we will assign it a specific time slot, but it will be day 1 or day 2. We are looking forward to this!

**Comment by supertestnet** [comment]
Hi Mike,

I'm not sure what difficulty level to say. Please advise. As with all my workshops, in this one you create an empty html page by copy/pasting some html boilerplate from my slideshow, and you gradually fill it up with content that you *also* copy/paste from my slideshow. It is designed so that you don't actually need to know how to code at all, and you should be fine even if this is your first time coding. Consequently, I *want* to say Beginner. Moreover, I have had a few total beginners follow my workshops, i.e. people who have never coded anything before, never touched a terminal or a text editor, and most of them made it through just fine.

However, since users do the copy/paste motion about 40 times, and some of them are beginners, it is not uncommon that they accidentally make a mistake, such as forgetting to click "copy" so they accidentally paste something twice. These people sometimes get lost as soon as they make a mistake. Sometimes they scramble to correct it, and thus make more mistakes, or they don't notice the error right away until something bad happens later in their code. Usually, they don't raise their hand to ask for help. So at the end of my talk, sometimes someone will approach me afterwards and say "I tried but it stopped working about halfway through so I just watched you the rest of the time."

Does this sound like I should say "Intermediate" or "Beginner"?

**Comment by supertestnet** [comment]
EDIT: I took some advice from another regular workshop presenter (Chris Guida), and he insists that I can call it Beginner as long as I do this:

Before starting my talk, I plan to inform everyone that it is critically important that, after every step, they raise their hand if they get an error or even if they just *aren't sure* they did the most recent step correctly. Chris informed me that the main reason why people opt not to raise their hand when they get an error is due to a guilty feeling: they feel like they'd be wasting everyone else's time due to making what is *probably* just a rookie mistake. So Chris says that you have to tell everyone right at the beginning that if anyone *doesn't* make it all the way through the workshop, the workshop will be a failure. Consequently, their guilt turns around: the workshop will probably be a failure unless they always remember to raise their hand when they're not sure.

I think I can do all that, so I am prepared to say confidently that my workshop is for beginnings.

**Comment by supertestnet** [comment]
In accordance with my comments, I added a line about the difficulty level

**Comment by iglesiasbrandon** [comment]
thank you for hosting this!
