### ISSUE TITLE
BOLT12-Prisms

### ISSUE THREAD

**Issue by farscapian** [TABConf/6.tabconf.com#38]
# BOLT12-Prisms

### Description 

This talk will cover the fascinating world of BOLT12-prisms [a concept first described by gigi](https://dergigi.com/2023/03/12/lightning-prisms/) that forwards sats over the Lightning Network by automatically splitting incoming payments. This talk will review the concept and characteristics of Prisms, specifically those based on [BOLT12](https://bolt12.org/). The bolt12-prism API for [Core Lightning](https://corelightning.org/) will be demonstrated, showcasing its capabilities. Afterwards, a new type of [Value4Value](https://value4value.info/) website based on BOLT12-Prisms will be covered including a description of the features and architecture of the system. Finally, attendees will experience an [LNPlay](https://www.lnplay.guide/) simulation featuring support for BOLT12-Prisms within [Clams Remote](https://clams.tech/remote).

_______________________
~~We can deploy a tabconf-branded LNPlay instance for the conference. We can place unique QR codes in people's conference lanyard, giving them control of their own dedicated lightning node. We can set each person's node ALIAS to their name they've identified during registration. Each conference attendee starts out with 1 BTC (regtest) and can open and balance channels with other participants as they see fit. Workshop presenters can display their BOLT12 offers so listeners can tip the presentation (before, during, and after).

### What would an attendee gain from this?

Attendees will experience a world where everyone around them is operating their own Core Lightning Node equipped to handle BOLT12. All nodes are made BOLT12-prism-capable, and a UI *should* be available for some kind of Lightning Prism workshop. The conference can set other criteria to gameify the experience, though development may be required. I'm open to ideas.~~

### Relevant Links
[lnplay.guide](https://www.lnplay.guide/)
[Clams Remote](https://clams.tech/remote)
[LNPlay Showcase](https://www.lnplay.guide/showcase/)
[BOLT12 Prism](https://www.roygbiv.guide/)

**Comment by bnonni** [comment]
@farscapian big fan of this idea! @iglesiasbrandon @miketwenty1 let's discuss soon

**Comment by miketwenty1** [comment]
@farscapian I'd like to chat offline about this with you. hello @ tabconf dot com is our email, look forward to chatting!

**Comment by miketwenty1** [comment]
This workshop/larp/demo currently looking for a champion. @farscapian will help onboard/train people interested in facilitating this.

**Comment by farscapian** [comment]
@gudnuf has agreed to be our champion and do a presentation on BOLT12-prisms. We are still assessing whether LNPlay can be used for the demonstration. @gudnuf, please ACK.

**Comment by gudnuf** [comment]
ACK!

**Comment by gudnuf** [comment]
apologies for the hassle, but I will not be able to give this presentation because I'm not going to make it to TabConf this year.

@farscapian can you confirm that you will able to do the presentation in my place?

**Comment by farscapian** [comment]
Yes, I can do the presentation. Thanks for the opportunity. But you better help me with the content!

@miketwenty1 I received word from the Clams guys that they expect to have the BOLT12-Prism UI added to Clams Remote in time for the presentation. Thus, we will use LNPlay for a useful demonstration of BOLT12-Prisms! Please let me know the layout of the room as this will help structure the demo. Best case scenario: people sit at tables of 5-10 people.

Here is the prompt for the presentation:

This talk will cover the fascinating world of BOLT12-prisms [a concept first described by gigi](https://dergigi.com/2023/03/12/lightning-prisms/) that routes sats over the Lightning Network by automatically splitting incoming payments. This talk will review the concept and characteristics of Prisms, specifically those based on [BOLT12](https://bolt12.org/). The bolt12-prism API will will be demonstrated, showcasing its capabilities. Afterwards, a new type of [Value4Value](https://value4value.info/) website based on BOLT12-Prisms will be covered including a description of the features and architecture of the system. Finally, attendees will experience an [LNPlay](https://www.lnplay.guide/) simulation featuring support for BOLT12-Prisms within [Clams Remote](https://clams.tech/remote).

**Comment by iglesiasbrandon** [comment]
Hey @gudnuf 

would you say this is beginner, intermediate or advance?

We are collecting an additional attribute for each issue. Please update your issue and include a line item on the difficulty level with either "Beginner", "Intermediate", or "Advanced".

Beginner: would be no prior knowledge needed, very few technical skills required for workshop
Intermediate: At least some knowledge needed to not be lost, technical skills, Comp Sci, IT related experience is greatly beneficial
Advanced: Potentially a strong working knowledge of certain technologies, libraries, fundamentals, Comp Sci, and related protocols.

Error on the side of more advanced than less advanced as we want to set strong expectations. Depending on what you pick please gauge your workshop accordingly.

Also how much time will you need for this workshop?

**Comment by farscapian** [comment]
Hi @iglesiasbrandon , I will be doing the presentation, not @gudnuf .

I think intermediate is probably a good choice. 60 minutes should suffice.

**Comment by farscapian** [comment]
I forgot to mention that @sbddesign has agreed to convey his understanding of prisms that are not based on BOLT12. This would probably be a short part of the presentation. But I wanted to mention that in case you want to add him as a co-presenter.

**Comment by farscapian** [comment]
> Hi @iglesiasbrandon , I will be doing the presentation, not @gudnuf .
> 
> I think intermediate is probably a good choice. 60 minutes should suffice.

@miketwenty1 @iglesiasbrandon -- please reassign this issue to me, @farscapian

**Comment by farscapian** [comment]
@miketwenty1 @iglesiasbrandon  Any idea how large "Workshop Room 1" is? I need an idea of max capacity (in terms of people) to size the LNPlay production instance.

**Comment by iglesiasbrandon** [comment]
The max capacity seated in workshop room on day 4 is about 40 people.

**Comment by iglesiasbrandon** [comment]
Thank you for hosting this!
