### ISSUE TITLE
Workshop - flash your own DIY Jade

### ISSUE THREAD

**Issue by epiccurious** [TABConf/6.tabconf.com#39]
# Description

### What is this workshop about? Provide as many details as possible.

Instruct participants on how to flash their own DIY Jade hardware wallet from a fresh copy of Ubuntu 24.

Participants can bring their own compatible DIY Jade or purchase one from me for $12.21. Or perhaps Tabconf might be willing to cover the cost of hardware for participants.

### What would an attendee learn from this workshop?

How to build and flash your own hardware wallet firmware as well as suggestions for hardware wallet security best practices.

### Is there anything attendees should read up on before they attend this talk?

Review the official Jade repo [DIY instructions](https://github.com/Blockstream/Jade/tree/master/diy).

### Is there anything attendees should set up before the workshop?

Required:
- A laptop that can run Ubuntu, ideally not a Macbook
- A bootable Ubuntu 24 USB drive

### Relevant Links

[DIY Jade repo](https://github.com/bitcoin-tools/diyjade)

# About the Speaker

### Social Links
Github: [epiccurious](https://github.com/epiccurious)
Twitter: [epic_curious](https://twitter.com/epic_curious)

# Workshop Details

### Length of workshop

30 minutes

### Preferred Day/Time Slot

Early afternoon would be preferred. Ideally not first thing in the morning, since attendance would probably be lower for this type of workshop.

**Comment by miketwenty1** [comment]
I'm almost wondering instead of a short workshop this should be a short demo where you show how this can easily be done, and then afterwards allow people to follow up with you. If we want to get physical devices and allow people to have a work-session with you in setting things up, this can be done during builder days. (first 2 days of the conf). Let me know what you think @epiccurious

**Comment by iglesiasbrandon** [comment]
This is going to be a part of this builder days project instead! 
https://github.com/TABConf/6.tabconf.com/issues/40
