### ISSUE TITLE
webpage: fix Opennode payment screen post-payment redirect

### ISSUE THREAD

**Issue by notmandatory** [TABConf/6.tabconf.com#4]
After buying a ticket via Opennode the redirect takes you back to the https://2023.tabconf.com page instead of https://6.tabconf.com.

**Comment by bnonni** [comment]
https://github.com/TABConf/6.tabconf.com/pull/11

**Comment by iglesiasbrandon** [comment]
closing this issue because of @bnonni's PR to fix
