### ISSUE TITLE
nodebuilder

### ISSUE THREAD

**Issue by epiccurious** [TABConf/6.tabconf.com#40]
# Description

### What is this project about? Please give us as many details as possible.

The tagline for [nodebuilder](https://github.com/bitcoin-tools/nodebuilder) is "Run a secure Bitcoin Core node with ease."

Copy and paste one line of code into the Terminal, and the script will run with minimal user interaction.

The goal is to balance security and convenience. This project is intended for 99% (2.5-sigma) of users who want to run Bitcoin Core. Compatible with all popular Linux distros and macOS or any system that can run Docker or any system that can run POSIX-compatible shell scripts which is almost every modern computer other than IoT devices.

### Is it a FOSS or Open Source project?

The project is FOSS, licensed under the MIT-0 license.

### What would an attendee learn from visiting this projects table at Builder Days?

An attendee would learn a low-effort way to run a Bitcoin Core node. He can use it to save time when running Bitcoin Core on a new install. He could also recommend noobs run nodebuilder on Ubuntu as an alternative to less-secure options such a umbrel.

The attendee would also learn how to:
- manage dependencies across many Linux distros
- best practices for using `:latest` tags for Dockerfile base images
- set up badass GitHub Actions CI checks, including linters and automated console output testing, to your repo.
- automatically create Docker Hub images when tagging new releases 
- ensure your shell script is POSIX-compatible and can run on all popular shells (bash, dash, ash, zsh)
- throw and handle shell runtime errors

### Is there anything people should read up on before finding the table at Builder Day?

Recommended reading:
- best practices for securely running Bitcoin Core nodes.
- the "Verify your download" section from [bitcoincore.org](bitcoincore.org/en/download)

### Relevant Links

GitHub Repo: [nodebuilder](https://github.com/bitcoin-tools/nodebuilder)

# Project Details

### Who will run the table? Are those people current contributors or maintainers who can answer questions and get people onboarded?

Two people - the project's maintainer and another dude to support

**Comment by iglesiasbrandon** [comment]
hey, @epiccurious, thank you for submitting this issue and volunteering to run a builder Days project for the nodebuilder project! Builder Days is on day 1 and 2! as we get closer to the conference we will post more updates! 

This issue has been accepted for TABConf 6.
