### ISSUE TITLE
Nixify Bitcoin-related codebases

### ISSUE THREAD

**Issue by storopoli** [TABConf/6.tabconf.com#41]
# Description

### What is this workshop about? Provide as many details as possible.

This workshop will teach users how to incorporate [Nix](https://nixos.org) into their codebase.
It is especially geared towards Bitcoin developers since running tests and checks against bitcoin core and other dependencies or interaction tooling is not trivial;
both in CI and locally.

### What would an attendee learn from this workshop?

- What are Nix derivations
- What are Nix flakes
- How to add a flake to your codebase
- How to package bitcoin software with Nix derivations, we'll provide examples with bitcoin core
- How to run CI with Nix both locally and in GitHub Actions

### Difficulty Level

Intermediate: At least some knowledge needed to not be lost, technical skills, Comp Sci, IT related experience is greatly beneficial.

### Is there anything attendees should read up on before they attend this talk?

There is an interesting (but opinionated) learning resource: [Zero to Nix](https://zero-to-nix.com/). It's useful for attendees interested in learning and having hands-on before the workshop, with a [good guide](https://zero-to-nix.com/start/install) covering most of the nix ecosystem and explanation pages of [Nix concepts](https://zero-to-nix.com/concepts).

### Is there anything attendees should set up before the workshop?

Please install Nix, we suggest using the
[Determinate Systems' Nix installer](https://github.com/DeterminateSystems/nix-installer)
that already adds `flakes` and `nix-command` extra functionality required for the workshop.
It is a very convenient and robust `curl` to `bash` one liner
(of course, be aware of these "automated internet scripts", don't trust, verify!).

### Relevant Links

- Nix: https://nixos.org
- `nixpkgs` Reference Manual: https://nixos.org/manual/nixpkgs/stable
- Nix Flake Templates: https://github.com/NixOS/templates
- Official documentation for getting things done with Nix: https://nix.dev
- Zero to Nix Guide: https://zero-to-nix.com

# About the Speakers

Not in a specific relevant order:

- Jose Storopoli (@storopoli): PhD in computational stats, recovering ex-academic, Nix and Rust enthusiast,
  contributor to `rust-bitcoin` and BDK, works at @AlpenLabs on Bitcoin-native zero-knowledge rollups.
- Leonardo Lima (@oleonardolima): Sofware Engineer, Rust & Nix enthusiast, contributor at BDK & Fedimint,
  supported by [Vinteum](https://vinteum.org/).
 
### Social Links

Github:

- https://github.com/storopoli
- https://github.com/oleonardolima

Nostr:

- https://primal.net/p/npub1ez8efu9rjxu64g0lalty2ffmr2tgkzjz92rkafyfyz5463wr8ars8zls5t

Website:

- https://storopoli.io

# Workshop Details

Proposed time-table:

- 00:00-00:05 - Why Nix and what it brings differently from other solutions such as Docker containers or VMs
- 00:05-00:10 - Nix language basics, mostly focused on how declarative and lazy-evaluated languages works
- 00:10-00:20 - Anatomy of a Nix derivation
- 00:20-00:30 - Anatomy of a Flake: possible inputs and outputs
- 00:30-00:40 - How to run Nix locally and in CI
- 00:40-00:55 - Hands-on: build your own Flake
- 00:55-01:00 - Wrap-up
 
### Length of workshop

1 hour.

### Preferred Day/Time Slot 

No preference.

**Comment by iglesiasbrandon** [comment]
Hey @storopoli, this sounds like a great workshop! Thank you for submitting it; we are going to start accepting issues very soon so keep an eye out!

**Comment by iglesiasbrandon** [comment]
Hey @storopoli, This issue has been accepted for TABConf 6! As we get closer to the conference we will add a specific time slot; it will be on day 1 or 2. 

We are looking forward to learning how to incorporate Nix!

**Comment by miketwenty1** [comment]
@storopoli  

We are collecting an additional attribute for the workshops. Please update your issue and include a line item on the difficulty level of the workshop with either "Beginner", "Intermediate", or "Advanced".

- Beginner: would be no prior knowledge needed, very few technical skills required for workshop
- Intermediate: At least some knowledge needed to not be lost, technical skills, Comp Sci, IT related experience is greatly beneficial
- Advanced: Potentially a strong working knowledge of certain technologies, libraries, fundamentals, Comp Sci, and related protocols.

Error on the side of more advanced than less advanced as we want to set strong expectations. Depending on what you pick please gauge your workshop accordingly.

**Comment by storopoli** [comment]
@miketwenty1 added "Intermediate". @oleonardolima also agrees with that.

**Comment by storopoli** [comment]
Reduced from 1h to 2h.
Cc @oleonardolima

**Comment by iglesiasbrandon** [comment]
hey @storopoli do you mean from 2h to 1h? if so I will adjust the schedule

**Comment by storopoli** [comment]
Yes my bad "reduced from 2h to 1h"

**Comment by iglesiasbrandon** [comment]
ok thank you @storopoli

**Comment by storopoli** [comment]
@iglesiasbrandon Can we add a pre-requisite (for the hands-on) that attendees install `nix` with the [`DeterministicSystems/nix-installer`](https://github.com/DeterminateSystems/nix-installer)?

It is a simple one-liner installation process.
This is important since it enables by default a bunch of options for running Nix flakes out of the box.
There is even chatter among the Nix developers to make this the default installer option.

(Of course, since this is a `curl foo | sh`, everyone should "DON'T TRUST, VERIFY!")

**Comment by iglesiasbrandon** [comment]
hey @storopoli yes please just edit the description of the issue.

**Comment by iglesiasbrandon** [comment]
Thank you for conducting this workshop!

**Comment by storopoli** [comment]
My pleasure, thanks for the opportunity!
