### ISSUE TITLE
Make Bitcoin Cypherpunk Again!

### ISSUE THREAD

**Issue by RobinLinus** [TABConf/6.tabconf.com#42]
# Description

### What is this talk about? Give us as many details as possible.
This talk is about the BitVM paradigm, our concrete implementation, and the BTC bridge that we are building. Furthermore, we present zkCoins, a second-layer protocol that increases the base layer throughput by more than 10x and enables strong privacy. 

### What would an attendee learn from this talk?
- Basics of BitVM
- Basics of zkCoins

### Is there anything folks should read up on before they attend this talk?
https://www.youtube.com/live/VIg7BjX_lJw
https://gist.github.com/RobinLinus/d036511015caea5a28514259a1bab119

### Relevant Links
https://bitvm.org
https://bitvm.org/bitvm2
https://github.com/bitvm/bitvm

# About the Speaker
### Social Links
Github: https://github.com/robinlinus 
Twitter: https://twitter.com/robin_linus
Website: https://robinlinus.com

# Talk Details
### Length of Talk
30 - 45 mins

### Preferred Day/Time Slot 
any time

**Comment by iglesiasbrandon** [comment]
Hey @RobinLinus, thanks for submitting this issue! we are going to start accepting issues in the coming weeks.

**Comment by iglesiasbrandon** [comment]
Hey @RobinLinus, this issue has been accepted for TABConf 6! We will assign it to a specific time slot as we get closer to the conference but it will be on day 3 or 4. We are looking forward to this!

**Comment by iglesiasbrandon** [comment]
hey @RobinLinus would you say this is intermediate or advance talk? 

We are collecting an additional attribute for the workshops. Please update your issue and include a line item on the difficulty level of the workshop with either "Beginner", "Intermediate", or "Advanced".

- Beginner: would be no prior knowledge needed, very few technical skills required for workshop
- Intermediate: At least some knowledge needed to not be lost, technical skills, Comp Sci, IT related experience is greatly beneficial
- Advanced: Potentially a strong working knowledge of certain technologies, libraries, fundamentals, Comp Sci, and related protocols.

Error on the side of more advanced than less advanced as we want to set strong expectations. Depending on what you pick please gauge your workshop accordingly.

**Comment by RobinLinus** [comment]
I guess more of an advanced talk then.

**Comment by iglesiasbrandon** [comment]
thank you for conducting this talk!
