### ISSUE TITLE
LDK Node: Simplifying development of self custodial Lightning Network Apps

### ISSUE THREAD

**Issue by BitcoinZavior** [TABConf/6.tabconf.com#43]
# Description

### What is this workshop about? Provide as many details as possible.

This workshop is a hands-on session aimed at simplifying the process of building self-custodial, mobile Lightning wallets using the LDK Node package for Flutter and React Native. Our goal is to demonstrate how developers and product teams can leverage this powerful toolset to streamline the integration of Lightning nodes into mobile applications. The package is pre-configured out of the box with all required services, ensuring a seamless setup.

**Pre-configured out-of-the-box features:**

- **Liquidity Service Provider (LSP) Integration:**
  - Ensures smooth and reliable transactions by automatically managing liquidity.
  - Reduces the complexity of handling liquidity issues, making it easier for developers to focus on core functionality.

- **Esplora Server:**
  - Provides enhanced blockchain data retrieval capabilities.
  - Enables more efficient querying of blockchain information, improving the overall user experience.

- **Rapid Gossip Sync Server:**
  - Delivers lightning-fast network updates.
  - Ensures that the mobile wallet stays up-to-date with the latest network topology, enhancing reliability and speed.

- **Channel Data Storage (VSS):**
  - Offers secure and efficient management of channel data.
  - Utilizes verifiable secret sharing to protect sensitive information and ensure data integrity.

**Benefits for Developers and Product Teams:**

- **Ease of Integration:** The LDK Node package provides an out-of-the-box solution that significantly reduces the time and effort required to integrate a complete Lightning node into mobile applications.
- **Enhanced Reliability:** By leveraging these integrated services, developers can ensure their wallets are robust, secure, and capable of handling the demands of real-world use.
- **Improved User Experience:** With streamlined processes and enhanced data retrieval, the end-user experience is markedly improved, making the wallet more attractive and user-friendly.

**Workshop Goals:**

- **Demonstrate Ease of Integration:** Show how the LDK Node package simplifies the integration of a complete Lightning node into mobile applications.
- **Educate Developers:** Provide insights into the challenges and solutions in building mobile Lightning wallets.
- **Hands-On Experience:** Offer practical experience with the LDK Node package through key Lightning Network use cases.

# Level of difficulty 
Intermediate

### What would an attendee learn from this workshop?

After the workshop, attendees will be familiar with the API and capabilities of LDK Node, and will know how to set it up and use it to build a Lightning Network wallet app using Flutter and React Native with the following functionalities:

- Receive on-chain funds
- Open channels
- Request JIT channels from an integrated LSP
- Generate invoices, Make payments, List payments
- Use channel backup via VSS and restore node
- See benefits of using enhanced Lightning Network routing 

### Is there anything attendees should read up on before they attend this talk?

No previous knowledge is required, but programming experience is needed. It is beneficial to have exposure to either Flutter or React Native or mobile app development.

### Is there anything attendees should set up before the workshop?

Attendees should have either Flutter or React Native development environments installed for their operating systems.

- **Flutter:** [Installation Guide](https://flutter.dev/docs/get-started/install)
- **React Native:** [Environment Setup](https://reactnative.dev/docs/environment-setup)

### Relevant Links

- [ldk-node-flutter](https://github.com/LtbLightning/ldk-node-flutter)
- [ldk-node-rn](https://github.com/LtbLightning/ldk-node-rn)
- [ldk-node-flutter-workshop](https://github.com/LtbLightning/ldk-node-flutter-workshop)
- [ldk-node-rn-workshop](https://github.com/LtbLightning/ldk-node-rn-workshop)

# About the Speaker

### **Social Links:**
- [Github](https://github.com/LtbLightning)
- [Twitter](https://x.com/LtbLightning)
- [Website](https://www.ltbl.io/)

# Workshop Details

### Length of workshop

2 to 3 hours

### Preferred Day/Time Slot

Any time and day are OK.

**Comment by iglesiasbrandon** [comment]
Hey @BitcoinZavior, this issue has been accepted to TABConf 6! We are looking forward to this workshop, and we will add a day and timeslot as we get closer to the conference.

**Comment by BitcoinZavior** [comment]
Delighted to hear! Thanks for your support 👍

**Comment by miketwenty1** [comment]
@BitcoinZavior  

We are collecting an additional attribute for the workshops. Please update your issue and include a line item on the difficulty level of the workshop with either "Beginner", "Intermediate", or "Advanced".

- Beginner: would be no prior knowledge needed, very few technical skills required for workshop
- Intermediate: At least some knowledge needed to not be lost, technical skills, Comp Sci, IT related experience is greatly beneficial
- Advanced: Potentially a strong working knowledge of certain technologies, libraries, fundamentals, Comp Sci, and related protocols.

Error on the side of more advanced than less advanced as we want to set strong expectations. Depending on what you pick please gauge your workshop accordingly.

**Comment by BitcoinZavior** [comment]
> @BitcoinZavior
> 
> We are collecting an additional attribute for the workshops. Please update your issue and include a line item on the difficulty level of the workshop with either "Beginner", "Intermediate", or "Advanced".
> 
> * Beginner: would be no prior knowledge needed, very few technical skills required for workshop
> * Intermediate: At least some knowledge needed to not be lost, technical skills, Comp Sci, IT related experience is greatly beneficial
> * Advanced: Potentially a strong working knowledge of certain technologies, libraries, fundamentals, Comp Sci, and related protocols.
> 
> Error on the side of more advanced than less advanced as we want to set strong expectations. Depending on what you pick please gauge your workshop accordingly.

Added difficulty level as **intermediate**

**Comment by notmandatory** [comment]
https://github.com/LtbLightning/ldk-node-flutter-workshop

**Comment by iglesiasbrandon** [comment]
thank you!
