### ISSUE TITLE
Lightning Is Fixed Now

### ISSUE THREAD

**Issue by TheBlueMatt** [TABConf/6.tabconf.com#44]
In 2022 I gave a talk about all the things that are broken about lightning, but since then instead of being bombastically optimistic about lightning, being overly pessimistic about lightning has become cool. Here I'd like to talk about how we've fixed many of the things from my 2022 talk, even if the future isn't evenly distributed here. By this talk, Bitcoin Core 28 should be out, initial implementation(s) of async payments may well be available, channel jamming has a (proposed) solution, and blinded paths/BOLT12 have addressed privacy in a big way...or at least they will once they're broadly available.

**Comment by miketwenty1** [comment]
@TheBlueMatt your talk went very well in 2022 and this would be a nice logical follow up. 

Go ahead and edit this issue, give us a bit more for a high level description and I think that'll be fine. 
as a helper here's the link to previous talk: https://www.youtube.com/watch?v=s9KMRWkcwtE
and high level of the talk:
- Always-Online is Hard
- Watchtowers Aren't Sufficient
- Foundational Security Assumptions...Need Work
- Routing is Actually Hard
- You Don't Really Have Privacy
- Channel Jamming (and other DoS Fun!)

**Comment by iglesiasbrandon** [comment]
Hey, @TheBlueMatt, this issue has been accepted for TABConf 6; we are looking forward to learning about all the improvements!

**Comment by average-gary** [comment]
https://github.com/TABConf/6.tabconf.com/issues/171#issuecomment-2435632498
@TheBlueMatt

**Comment by iglesiasbrandon** [comment]
Thank you for conducting this talk!
