### ISSUE TITLE
Hedging Hashrate: A Market Solution to Miner Variance

### ISSUE THREAD

**Issue by jamespierog** [TABConf/6.tabconf.com#46]
# Description
### What is this talk about?
Variance of winning the block reward has caused miners to aggregate hashrate into pools. Now the top 4 pools control over 75% of the network hashrate. Dominant pools with FPPS payouts are not incentivized to adopt StratumV2, and miners have no economic incentive to switch to small non-FPPS StratumV2 pools with high variance of payouts. Bitcoin mining is broken due to the winner-take-all nature of the mining contest, and something needs to be done to alter the economic incentives for miners to decentralize their hashrate and adopt StratumV2.

This talk will cover the Bitcoin Prediction Market [whitepaper](https://www.bitcoinprediction.info/documents/Hedging_Block_Reward_Variance_with_DLCs.pdf), which proposes a solution to miner payout variance that does not incentivize further centralization of hashrate. It will introduce the piecewise parimutuel market design, and justify how miners and pools can hedge payout risk by betting against themselves or on dominant pools. It will also introduce and de-risk betting strategies for speculators to provide liquidity in the market, and prove under what conditions those strategies have positive expected value.

### What would an attendee learn from this talk?
- How the broken incentives embedded in Bitcoin mining cause the network imbalances we see today
- Why variance is such a big problem for both miners and pool operators
- Why FPPS is not a sustainable pool payout scheme as block rewards diminish with future halving events
- How hedging hashrate can incentivize miners to direct hashrate to smaller StratumV2 pools
- How speculators can benefit by providing liquidity through optimal betting in the market 

### Is there anything folks should read up on before they attend this talk?
Attendees should have a basic understanding of Bitcoin mining and pool payout schemes. Familiarly in elementary probability theory and statistics will also be helpful. 

### Relevant Links
- [Bitcoin Prediction Market Whitepaper](https://www.bitcoinprediction.info/documents/Hedging_Block_Reward_Variance_with_DLCs.pdf)
- [On the Fragility of FPPS](https://upstreamdata.com/the-fragility-of-financialized-bitcoin-mining-pools/)
- [Analysis of Bitcoin Pooled Mining Reward Systems](https://arxiv.org/pdf/1112.4980)
- [Bitcoin Prediction Market Alpha Release](https://www.bitcoinprediction.market/)

# About the Speaker
James Pierog is Co-Founder and CEO of Bitcoin Prediction Market, a Wolf-backed company. He graduated with a degree in Mathematics and Computer Science from Yale-NUS. He studied philosophy under Andrew Bailey, co-author of Resistance Money, and his undergraduate thesis was on applying infinite groups to post-quantum cryptographic protocols. 

### Social Links
Github 
https://github.com/jamespierog
Twitter
https://x.com/BillyHongBeats
https://x.com/BTCPredMrkt
Nostr
npub1u8r69esh5r7jt29nj9ufmz4yvuwp6cwl5xqp4e3d46vl8wla5smsexjcky
Website
https://bitcoinprediction.info/

# Talk Details
### Length of Talk
30 minutes talk
10 minutes Q&A
40 minutes total

### Preferred Day/Time Slot 
Day one of talks early afternoon

**Comment by miketwenty1** [comment]
@jamespierog would you also be live demoing your market website as part of the talk?

**Comment by jamespierog** [comment]
> @jamespierog would you also be live demoing your market website as part of the talk?

Yeah sure. Demoing the prediction market is as simple as sending a lightning payment. I can do it at the beginning of the talk, and most likely by the end of the talk I should receive a reward in my lightning wallet (if I placed a bet correctly).

**Comment by iglesiasbrandon** [comment]
thank you for conducting this talk!
