### ISSUE TITLE
Matt Debates the Audience - MEV, MEVil, and Mining Centralization

### ISSUE THREAD

**Issue by TheBlueMatt** [TABConf/6.tabconf.com#48]
If one talk is good, is two talks better? I'd like to give a talk on Mining Centralization and the risks of MEVil, basically an in-person version of https://bluematt.bitcoin.ninja/2024/04/16/stop-calling-it-mev/ but walking through more detail and getting into the risks to Bitcoin if we screw this up. Will also touch on Sv2 and braidpools/p2pool and why these things are critical to the future of Bitcoin.

**Comment by miketwenty1** [comment]
I've seen MEVil discussed a few times, with opinions ranging from it being a non-issue to it being the worst issue. I'd like to have a structured, civil debate on this. As "L2 stuff" (non-LN) gains traction, I believe some of it also brings opportunities for MEV*il.

Disclaimer: (This could be a terrible idea), I'm theorizing here, How about a ~20-minute presentation to set the premise, followed by a 25+ minute Q&A? If you're comfortable with this format, we could let people on stage, giving them 5 minutes each, from a prequalified queue of those working on relevant projects and possibly holding different views.

Let me know your thoughts @TheBlueMatt.
