### ISSUE TITLE
Coinswap

### ISSUE THREAD

**Issue by Shourya742** [TABConf/6.tabconf.com#49]
# Description

## What is this talk about?

This talk covers [CoinSwap](https://github.com/citadel-tech/coinswap), our implementation, and its future possibilities. 

CoinSwap is an on-chain atomic swap protocol that allows for the non-custodial exchange of one UTXO for another. It is an implementation of Atomic Swaps and shares similarities with the Lightning Network, by using HTLCs as contract between the swap partners. The effect of an Atomic Swap is a change of UTXO ownership without an on-chain footprint. 

While single transaction, single hop swap isn't very interesting. Multi-hop multi-path swaps have both fungibility and utility impact on the Bitcoin ecosystem. Peers can split and merge their UTXOs via swaps, while disjointing the onchain ownership relation of these UTXOs. Read more on the design details of Coinswap [here](https://github.com/citadel-tech/coinswap/blob/master/docs/dev-book.md).

Various swap params, like `hop count`, `split count`, `fixed amount`, `random amount` etc are configurable by the user at per-swap-basis.

While on-chain swaps disjoint the graph of UTXO ownership, hence improving Bitcoin's fungibility. The same mechanism can be extended between Bitcoin and other UTXO-based chains to create a P2P cross-chain swap market. For chains like Liquid, this can potentially remove the peg-in/peg-out bottlenecks and allow more liquidity to spread between Bitcoin and Liquid via the swap markets.

One can imagine a highly liquid swap market, at a high fee environment, where users can quickly swap out of BTC, make their payments in low-fee chains, swap back to BTC, and store the remaining in cold storage.

The swaps are regular p2wsh transactions (AnonSet = All LN channels), so a widely distributed swap activity will increase fungibility for non-swap users also, providing "Passive Privacy". 

This unique property of Coinwaps makes them an interesting approach for both Scalability and Fungibility improvement simultaneously.

## What would an attendee learn from this talk?

- An introduction to CoinSwap technology.
- The project's current status.
- Enhancements to the protocol using Taproot and MuSig2.
- Guidelines for getting started with contributions.

## Is there anything folks should read up on before they attend this talk? 

CoinSwap is a rust implementation of a variant of atomic-swap protocol, using HTLCs on Bitcoin. Read more at:

* [Mailing list post](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2020-October/018221.html)
* You can access the project's code and additional documentation in this [GitHub repository](https://github.com/citadel-tech/coinswap). The repository contains the source code, instructions for setup, and other relevant resources for CoinSwap.
### Social links

* GitHub: [bit-aloo](https://github.com/Shourya742) Contributor
* Twitter: [bit-aloo](https://x.com/shourya742)

### Length of talk

30 - 45 mins

### Preferred Day/Time Slot

Any time

**Comment by miketwenty1** [comment]
@Shourya742 this looks really neat. 
Question:
Is this implemented anywhere for testing? like on a signet or testnet?

**Comment by Shourya742** [comment]
Hey @miketwenty1, we're implementing the protocol: https://github.com/citadel-tech/coinswap. Right now, you can test it using our integration test suite. We'll soon be releasing a command-line application on signet for community testing.

**Comment by vnprc** [comment]
I've been a big fan of teleport transactions since I first learned about them. I think this would be a great talk to see!
