### ISSUE TITLE
Beyond the Base Layer: A Discussion on Scaling Bitcoin 

### ISSUE THREAD

**Issue by 0xcoolgirl** [TABConf/6.tabconf.com#51]
Willem Schroe, CEO & Co-Founder, Botanix Labs

# Description
### What is this panel discussion about? Please give us as many details as possible. 
The past 18 months of Bitcoin has been full of new “Layer 2” projects. Some serious ideas and many other scams have propelled this sector to the fore of the Bitcoin industry. Founders and engineers from credible, cutting-edge Bitcoin teams working to scale Bitcoin will discuss and debate the most pressing cultural and technical topics of this new renaissance in Bitcoin protocols, including payment channels, EVM equivalence, rollups, and more.

### What would an attendee learn from this talk?
Review of Bitcoin Scaling (Past & Present)
Tradeoffs and Design Decisions for Bitcoin L2s
Innovative Bitcoin Scaling Technologies
How to Scale Bitcoin without Building Scams
Discuss the question: “What really is an ‘L2’?”
Discuss the question: “Are most new ‘L2s’ just scams?”

### Is there anything folks should read up on before they attend this talk?
Lightning Network Whitepaper: https://lightning.network/lightning-network-paper.pdf 
Botanix Labs Whitepaper: https://a-us.storyblok.com/f/1014909/x/8bdb3e5611/botanix-protocol-whitepaper.pdf 
Citrea Docs: https://github.com/chainwayxyz/citrea-docs 
Thesis (Mezo) Docs: https://info.mezo.org/ 
Alpen Labs Whitepaper: https://github.com/alpenlabs/Technical-Whitepaper/blob/main/whitepaper_v085.pdf 
### Panelist: Willem Schroé (Botanix Labs), Neha Narula, Alex B (Ark), Ekrem (Citrea)

- Willem, Twitter: @WillemSchroe, Website: https://botanixlabs.xyz/en/about 
- Neha Narula, Twitter: @neha,  Website: https://www.media.mit.edu/ 
- Alex B. (Ark), Twitter: @bergealex4, Website: https://arklabs.to/
- Ekrem (Citrea), Twitter: @ekrembal_, https://citrea.xyz/ 

### Who will be helping organize this panel?
Michael Tidwell

# Panel Discussion Details
### Preferred Day/Time Slot: October 23, midday 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by orkunkilic** [comment]
We (Citrea team) would like to be a part of the panel if accepted.

**Comment by theblackmarble** [comment]
I'd love to be on this panel.  I am the architect of the Anduro Platform (Coordinate & Alys sidechains currently in open beta) and Director of Engineering for Mara.

**Comment by 0xcoolgirl** [comment]
Hey @miketwenty1 are you able to take ownership here and project manage this panel? Many thanks.

**Comment by narula** [comment]
hi, i've been doing a deep dive/overview of the components needed for Bitcoin rollups and the trade-offs behind different types of scaling solutions (Lightning, Ark, e-cash, client-side validated protocols, and sidechains). I'd be interested in participating in this panel if you're looking for someone not coming from a specific project. However, I have a timing constraint in that I can only do Friday, October 25th or Saturday October 26th.

**Comment by narula** [comment]
Hi @miketwenty1, have you determined the final panel yet?

(no worries either way)

**Comment by iglesiasbrandon** [comment]
thank you for hosting this!
