### ISSUE TITLE
SeedSigner New Developer Onboarding Workshop

### ISSUE THREAD

**Issue by SeedSigner** [TABConf/6.tabconf.com#52]
# Description
Learn about SeedSigner development for fun and mayhem

### What is this workshop about? Provide as many details as possible.
SeedSignerOS (our linux distro) and the SeedSigner python app

### What is the difficulty of this workshop?
Intermediate: At least some knowledge needed to not be lost, technical skills, Comp Sci, IT related experience is greatly beneficial

### What would an attendee learn from this workshop?
Learn the basics of modifying and compiling SeedSignerOS, and learn about the SeedSigner app to be able to modify existing features and add new functionality

### Is there anything attendees should read up on before they attend this talk?
Familiarity with Linux, Buildroot and Python will be helpful

### Is there anything attendees should set up before the workshop?
You'll definitely want to have a SeedSigner with you -- bring your own, or they will be made available (details forthcoming)

### Relevant Links
https://github.com/SeedSigner/seedsigner

# About the Speakers
Keith and Nick 
### Social Links
Github:
Keith: https://github.com/kdmukai
Nick: https://github.com/newtonick

Twitter:
Keith: https://x.com/KeithMukai
Nick: https://x.com/newtonick

Nostr:
Keith: npub1tv8gmfhalwnxxquxjzeh6gtdsdz6vg7vx0s3rt7s7uuw6aujh32qn77wn2
Nick: npub1rfd0hxdzcze6pzj29thuz34vur57wm9quje7w3edxjgusq6m47csnl7wrt

# Workshop Details
### Length of workshop
120 mins
### Preferred Day/Time Slot 
N/A

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by kdmukai** [comment]
Note: I also submitted an entry just for a Builder Day table. I think it makes sense to have the open, informal Builder Day table where people can just wander over whenever throughout that day AND the more structured specific workshop time proposed above.

@SeedSigner I recommend updating this title to something like "SeedSigner New Dev Onboarding Workshop".

**Comment by iglesiasbrandon** [comment]
Hey @kdmukai this issue has been accepted for TABConf 6!

**Comment by miketwenty1** [comment]
@SeedSigner 

We are collecting an additional attribute for the workshops. Please update your issue and include a line item on the difficulty level of the workshop with either "Beginner", "Intermediate", or "Advanced".

- Beginner: would be no prior knowledge needed, very few technical skills required for workshop
- Intermediate: At least some knowledge needed to not be lost, technical skills, Comp Sci, IT related experience is greatly beneficial
- Advanced: Potentially a strong working knowledge of certain technologies, libraries, fundamentals, Comp Sci, and related protocols.

Error on the side of more advanced than less advanced as we want to set strong expectations. Depending on what you pick please gauge your workshop accordingly.

**Comment by SeedSigner** [comment]
> @SeedSigner I recommend updating this title to something like "SeedSigner New Dev Onboarding Workshop".

Done, good suggestion.

**Comment by iglesiasbrandon** [comment]
Thank you for conducting this workshop!
