### ISSUE TITLE
Build a web wallet with BDK 1.0

### ISSUE THREAD

**Issue by notmandatory** [TABConf/6.tabconf.com#54]
# Description

### What is this project about? Please give us as many details as possible.

The [BDK](https://github.com/bitcoindevkit/bdk) project has been working hard this year to finish a new stable 1.0 `bdk_wallet` module API. One of the highlights of the new `Wallet` struct is that it decouples the persistence (ie. bdk_sqlite) and blockchain clients (ie. bdk_esplora, bdk_electrum, bdk_bitcoind_rpc) allowing you to build apps using Rust's async IO runtimes. 

For this workshop we will build a simple descriptor based based web wallet using BDK 1.0, axum, an esplora client, and SQLite database. 

### Is it a FOSS or Open Source project?

Yes. [LICENSE](https://github.com/bitcoindevkit/bdk/blob/master/LICENSE)

### What would an attendee learn from visiting this projects table at Builder Days?

You will learn the basic steps required to:

1. create a new on-chain wallet from a random mnemonic derived private key and pay to taproot (P2TR) descriptor.
2. read/write wallet state data to a SQLite database
3. synchronize the wallet's tx history via the Esplora protocol
4. view the wallet's balance and transaction history

### Is there anything people should read up on before finding the table at Builder Day?

* The latest [`bdk_wallet`](https://docs.rs/bdk_wallet/latest/bdk_wallet/) rust docs
* Understand the basics of bitcoin [descriptors](https://github.com/bitcoin/bips/blob/master/bip-0380.mediawiki) and [miniscript](https://github.com/bitcoin/bips/blob/master/bip-0379.md)
* Generally know your way around [Rust](https://doc.rust-lang.org/stable/book/) and [Axum](https://docs.rs/axum/latest/axum/)

### Relevant Links

GitHub Repo: https://github.com/bitcoindevkit/bdk

# Project Details

BDK website: https://bitcoindevkit.org/
nostr: https://njump.me/npub13dk3dke4zm9vdkucm7f6vv7vhqgkevgg3gju9kr2wzumz7nrykdq0dgnvc

### Who will run the table? Are those people current contributors or maintainers who can answer questions and get people onboarded?

Running the table: @notmandatory (+ others TBD)
Current contributors/maintainers: Yes

**Comment by bnonni** [comment]
Hey @notmandatory, thank you for submitting this issue! It's been accepted for Builder Days!

**Comment by iglesiasbrandon** [comment]
hey @notmandatory this issue uses the builder days project template but reads like a workshop you would like to host. Do you intend for this issue to be a workshop or a builder days project or do you want 1 for each?

**Comment by notmandatory** [comment]
Sorry for the delay, I would like to do this as a workshop if possible.

**Comment by bnonni** [comment]
Thanks @notmandatory! We updated the label for you!

**Comment by bnonni** [comment]
@notmandatory we also added a label of "Intermediate" to this talk. If you think that's not reflective of the content, please let us know!

**Comment by bnonni** [comment]
Oh also @notmandatory how long will this workshop be?

**Comment by notmandatory** [comment]
I should be able to do this in a 1hr slot.

**Comment by notmandatory** [comment]
For anyone who want's to read ahead here's the repo for this workshop:

https://github.com/notmandatory/tabconf24_bdk_workshop/

**Comment by iglesiasbrandon** [comment]
hey @notmandatory thank you for conducting the workshop!
