### ISSUE TITLE
Covenants and STARK proof verification with OP_CAT

### ISSUE THREAD

**Issue by weikengchen** [TABConf/6.tabconf.com#55]
# Description
### What is this talk about? Give us as many details as possible. 

This talk will be a summary of the progress of covenants and verifying STARK on Bitcoin, using the OP_CAT opcode. This includes its applications and the implementation that is currently open-source on GitHub.

A toy example, which verifies Fibonacci sequence, has already been executed on signet.
https://mempool.space/signet/address/tb1p2jczsavv377s46epv9ry6uydy67fqew0ghdhxtz2xp5f56ghj5wqlexrvn
(these 10 txs, each within the standard relay policy limit, use covenants to join together)

### What would an attendee learn from this talk?

Developers who want to know the latest status of the open-source development regarding covenants and STARK on Bitcoin.

### Is there anything folks should read up on before they attend this talk?

No. But we expect the audience to have some experience with Bitcoin opcodes.

### Relevant Links

All the open-source implementations have been released:
https://github.com/Bitcoin-Wildlife-Sanctuary

Code to reproduce the signet experiment:
https://github.com/Bitcoin-Wildlife-Sanctuary/bitcoin-circle-stark/blob/main/demo/script.txt
https://github.com/Bitcoin-Wildlife-Sanctuary/bitcoin-circle-stark/blob/main/src/bin/demo.rs

# About the Speaker
### Social Links
Github: https://github.com/weikengchen
Twitter: https://x.com/weikengchen
Website: not actively maintained

# Talk Details
### Preferred Day/Time Slot: no specific preference
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by iglesiasbrandon** [comment]
hey @weikengchen we have accepted this issue for TABConf 6! we are looking forward to learning about this topic.

**Comment by bnonni** [comment]
Hey, @weikengchen looking forward to having you at TAB6! Just want to draw your attention to the fact that we also added a label of "Advanced" for this talk. If you think that's not reflective of the content, please let us know!

**Comment by rot13maxi** [comment]
cant wait for this

**Comment by iglesiasbrandon** [comment]
Thank you for hosting this!
