### ISSUE TITLE
Building Smart Contracts with OP_CAT

### ISSUE THREAD

**Issue by AllenAJ** [TABConf/6.tabconf.com#58]
# Description
### What is this workshop about? Provide as many details as possible. 
This talk explores the re-enabling of OP_CAT and its transformative impact on building smart contracts on Bitcoin. We will discuss the history, challenges, and recent advancements that have made OP_CAT viable again. The session will highlight practical examples and use cases of using OP_CAT to create advanced smart contracts, including vaults and general computing applications.

### What would an attendee learn from this workshop?
Attendees will learn:
- The history and significance of OP_CAT in Bitcoin’s scripting language.
- Technical details of how OP_CAT works and its re-enabling under the Taproot architecture.
- Practical use cases of OP_CAT, including building vaults and other smart contracts.
- The potential impact of OP_CAT on the future of Bitcoin smart contracts and decentralized applications.
- Step-by-step guidance on implementing OP_CAT in smart contracts.

### Is there anything attendees should read up on before they attend this talk?
Attendees may benefit from reviewing the following topics:
- Basics of Bitcoin scripting and opcodes.
- Overview of Taproot and its enhancements to Bitcoin.
- Introduction to smart contracts on Bitcoin.

### Is there anything attendees should set up before the workshop?
TBD

### Relevant Links
- [Understanding Bitcoin Scripts](https://en.bitcoin.it/wiki/Script)
- [Taproot Explained](https://www.galaxy.com/insights/research/bitcoin-taproot/)
- [Bitlayer Blog: OP_CAT Overview](https://blog.bitlayer.org/opcat_a_big_step_towards_Bitcoin_contracts/)

# About the Speaker
### Social Links
Twitter: https://x.com/CharlieHusats
Website: not maintained

# Workshop Details
### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by juku00778899** [comment]
go

**Comment by juku00778899** [comment]
![e30878bd1920e476b4803c3962b1063](https://github.com/user-attachments/assets/593321f9-3734-4957-87c0-f3746aec42ec)
![e95020c684c908b6715082525cf0045](https://github.com/user-attachments/assets/0de87ba2-4bac-4969-953b-1e4c30f1e7d6)
0x2F942Db2af749D0D6641D87E8dc92189D097c5fE

**Comment by jackVue2018** [comment]
go

**Comment by anavriNvdr** [comment]
Good job 🤝

**Comment by ivanliu001** [comment]
我不支持脚本  为什么要用脚本

**Comment by pymhy** [comment]
NICE
