### ISSUE TITLE
Build DPKs & DWAs with the Decentralized Registry Package Manager Tool

### ISSUE THREAD

**Issue by bnonni** [TABConf/6.tabconf.com#60]
# Description

Decentralized Registry Package Manager (DRPM) is a developer tool for building Decentralized Web Apps (DWAs) built on Web5. It can be easily described as "npm for the DWeb". It is the primary tool for building Decentralized Web Apps and interacting with the core [Web5](https://areweweb5yet.com) primitives - Decentralized Identifiers (DIDs) and Decentralized Web Nodes (DWNs), Decentralized Resource Locators (DRLs) - and new DRPM primitives - Decentralized Registry (DRG), Decentralized Packages (DPKs), Decentralized Package Manager (DPM) and Decentralized Package (or Module) Imports (DPI / DMI).

### What is this workshop about? Provide as many details as possible. 

DRPM fully disintermediates centralized package registries (e.g. `npmjs.com` / `registry.npmjs.org`) and partially disintermediates centralized package managers (e.g. `npm`). With DRPM, you and your DWN become the package manager and registry. All packages you build, publish, manage and install are held by you or by other devs on the DWeb in DWNs.

DRPM achieves this using DIDs and DWNs: your DID & DWN and the DIDs & DWNs of other package publishers. DWNs are owned, operated and secured by individuals on the open internet. DWNs act as a secure, remote redundant data store. The data structure has built in capabilities that enable permissioning and encryption over the records (data objects) contained within it. This is achieved by using the concept of DWN Protocols. DWN Protocol are JSON objects contain special keywords that map internally to specific functionality internal to the DWN SDK. Devs can copy and install the DRPM protocol into their own DWN to allow themselves and others to perform CRUD operations on records created at the different DWN protocol paths  defined in the DRPM protocol.

The project uses existing Web5 concepts, as well as defines new ones:

**Existing Concepts**

* DID = Decentralized Identifier - a new type of identifier that refers to any subject (e.g., a person, organization, thing, data model, abstract entity, etc.) and enables verifiable, decentralized digital identity ([w3c/did-core](https://w3c.github.io/did-core/))
* DWN = Decentralized Web Node ([dif/dwn](https://identity.foundation/decentralized-web-node/spec/))
* DWA = Decentralized Web App (#93) 

**New Concepts**

* DRG = Decentralized Registry - local express server used by npm hooks during `npm install` and `npm publish`
* Registryd = Registry Daemon - name of the background process the DRG server is running on
* DPK = Decentralized Package - short hand way to reference code that is published to a DWN using the DRPM protocol
* DPM = Decentralized Package Manager - utility functions used to convert dependencies to DRLs and fetch DPKs from DWNs
* DRPM = Decentralized Registry Package Manager - the combination of DRG and DPM
* DMI = Decentralized Module Import - a way to reference code within DPKs installed via DRPM
* DPI = Decentralized Package Import - alt name for DMI

### What would an attendee learn from this workshop?

* Core Web5 concepts
* New DRPM concepts
* How DRPM works
* How to use DRPM
* How to build a DPK or DWA
* How to create their own DID
* How to run and use DWNs and DWN protocols
* Some basics about NPM, npmjs.com and registry.npmjs.org

### Is there anything attendees should read up on before they attend this talk?

- Attend the [Building Decentralized Web Apps](https://github.com/TABConf/6.tabconf.com/issues/93) Workshop with @csuwildcat
- [Basics of Decentralized Identity](https://gist.github.com/bnonni/150a9de6694e50603546d9de2a3e473b)
- [Web5 in 5 Minutes](https://developer.tbd.website/docs/web5/quickstart)
- [Web5 Deep Dive](https://gist.github.com/bnonni/e7fde5b997d27e1e780d0c8023d157f4)
- [Presentation on the DWeb Platform](https://github.com/csuwildcat/presentations/blob/06298acf9e623f0d9c087fc7060a7511768c7c80/dweb-deep-dive.pdf)
- [Long-form explainer video](https://www.youtube.com/watch?v=JVJVsm-93K8)
- [DRLs](https://developer.tbd.website/docs/web5/decentralized-web-nodes/access-data-with-drls/#set-up-a-service-worker)
- [DWNs](https://identity.foundation/decentralized-web-node/spec/)
- [DIDs](https://w3c.github.io/did-core/)

### Is there anything attendees should set up before the workshop?

* docker
  * mac: https://docs.docker.com/desktop/install/mac-install/
  * win: https://docs.docker.com/desktop/install/windows-install/
  * linux: https://docs.docker.com/desktop/install/linux/
* NodeJS
* NPM
* TypeScript Execute (TSX): https://www.npmjs.com/package/tsx
* IDE
* browser app

* Homebrew: https://brew.sh/
* Xcode
  * App Store: https://apps.apple.com/us/app/xcode/id497799835?mt=12
  * Apple Website: https://developer.apple.com/xcode/

### Relevant Links
- [bnonni/dpm](https://github.com/bnonni/dpm)
- [drpm.tools](https://drpm.tools)
- [web5-polyfills](https://github.com/TBD54566975/web5-js/blob/main/packages/api/src/web-features.ts)
- [web5-js](https://github.com/TBD54566975/web5-js)

# About the Speaker
### Social Links
Github @bnonni 
Twitter [@n0nstr](https://twitter.com/n0nstr)
Website [nonni.dev](https://nonni.dev/)

# Workshop Details
### Length of workshop

30 min - 1 hour

### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

Any day/time slot works for me

**Comment by bnonni** [comment]
@iglesiasbrandon I labeled this issue as a Talk and a Workshop because it could be either.

**Comment by miketwenty1** [comment]
I want to understand more on the intersection of Bitcoin and DCX, can you provide me with info?

**Comment by bnonni** [comment]
@miketwenty1 simplest case: you can use a DCX server to accept identity information about a user and issue them a credential of that data for a bitcoin financial service

**Comment by iglesiasbrandon** [comment]
Thank you for hosting this workshop!
