### ISSUE TITLE
Demystifying Bitcoin Tax: A Guide to the Current Regulatory Landscape

### ISSUE THREAD

**Issue by PatrickCamusoCPA** [TABConf/6.tabconf.com#62]
# Description
### What would an attendee learn from this talk?

Tax Implications of Common Crypto Activities: Gain clarity on how buying, selling, staking, mining, and using crypto for payments are taxed.
Reporting Requirements: Learn about the current reporting obligations for individuals and businesses dealing with crypto.
Future of Crypto Tax Regulations: Explore potential upcoming changes and how they might affect your crypto tax strategy.**

### Is there anything folks should read up on before they attend this talk?

No prior knowledge of crypto is required. However, attendees with a basic understanding of cryptocurrencies and tax concepts will benefit the most.

### Relevant Links

# About the Speaker

### Social Links
(https://www.linkedin.com/in/patrickcamuso/)
[Twitter](https://x.com/PatrickCamuso)
[Website](https://camusocpa.com/)

# Talk Details
### Preferred Day/Time Slot   Flexible
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by miketwenty1** [comment]
@PatrickCamusoCPA I'm unsure if this talk will be accepted or not, but are you planning on coming to TABConf regardless? There may be some people that would like to talk with you.

**Comment by asherp** [comment]
@PatrickCamusoCPA This sounds like a great talk. We'd be happy to host it in the NextGen village. As this is a Bitcoin-only conference, I was wondering if you could focus on Bitcoin-related regulatory environment and perhaps change the title to reflect?

**Comment by PatrickCamusoCPA** [comment]
Thanks for following up.

Absolutely we can make it Bitcoin only.

Let me know if this works:

Demystifying Bitcoin Tax: A Guide to the Current Regulatory Landscape

**Comment by PatrickCamusoCPA** [comment]
@miketwenty1 I may come regardless but still up in the air.

**Comment by asherp** [comment]
@PatrickCamusoCPA what day/time do you prefer? Friday/Saturday?

**Comment by PatrickCamusoCPA** [comment]
> @PatrickCamusoCPA what day/time do you prefer? Friday/Saturday?

@asherp Saturday morning would be best for me but I can also be flexible depending on your schedule on your side.

**Comment by PatrickCamusoCPA** [comment]
> > @PatrickCamusoCPA what day/time do you prefer? Friday/Saturday?
> 
> @asherp Saturday morning would be best for me but I can also be flexible depending on your schedule on your side.

@asherp I expect that you're very busy with all these comments so just a friendly reminder on this. Thanks a lot.

**Comment by asherp** [comment]
@PatrickCamusoCPA thanks for the reminder. you're on the schedule 9:45-10:15 am Saturday. Looking forward to hearing you speak!

**Comment by PatrickCamusoCPA** [comment]
Thanks a lot @asherp .

I updated the title and applied for the grant.

Looking forward to meeting you!

**Comment by iglesiasbrandon** [comment]
thank you for conducting this talk!

**Comment by PatrickCamusoCPA** [comment]
Sure thing, thanks for having me. Happy to do a similar talk next year!

Patrick Camuso, CPA
Camuso CPA
CamusoCPA.com
***@***.******@***.***>
Office: 704-249-3179

***@***.***

Follow Me:  Linkedin<linkedin.com/in/patrickcamuso>,Youtube<https://www.youtube.com/channel/UCNrEvBlhb9SRqGrSOZGfzbQ>, Facebook<https://www.facebook.com/CamusoCPA/?hc_ref=SEARCH&fref=nf>, Blog<https://www.camusocpa.com/blog/#/>, Twitter<https://twitter.com/PatrickCamuso?lang=en>

Our firm is built upon referrals and working with people like you. Every referral is greatly appreciated


****Any tax advice included in this communication may not contain a full description of all relevant facts or a complete analysis of all relevant tax issues or authorities.  This communication is solely for the intended recipient’s benefit and may not be relied upon by any other person or entity. *****
