### ISSUE TITLE
Intro to Rust Workshop

### ISSUE THREAD

**Issue by sb1752** [TABConf/6.tabconf.com#63]
# Description
Based on a [course](https://github.com/sb1752/bitcoiner-intro-to-rust) I've created and a cohort I ran with Chaincode Labs, I'd like to offer an Introduction to Rust workshop.

### What is this workshop about? Provide as many details as possible. 
This is a beginner introduction to the Rust programming language. We will learn how the Rust language works by building a Bitcoin raw transaction decoder, similar to `bitcoin-cli decoderawtransaction`. Given time constraints, we will only partially get through this project.

### What would an attendee learn from this workshop?
Basic Rust concepts: types, data structures, ownership model, references, and review of computer science fundamentals such as the stack vs the heap

### Is there anything attendees should read up on before they attend this talk?
Chapter 6 of Mastering Bitcoin, 3rd Edition

### Is there anything attendees should set up before the workshop?
Yes, attendees should have Rust and Cargo already set up on their machine as we won't spend time with setup.

### Relevant Links
https://github.com/sb1752/bitcoiner-intro-to-rust

# Level of difficulty 
### Intermediate
Some background with programming is expected

# About the Speaker
### Social Links
Github: https://github.com/sb1752
Twitter: https://x.com/shaanbatra

# Workshop Details
### Length of workshop
2 hours

### Preferred Day/Time Slot 
Would prefer 24th or 25th in a morning slot.

**Comment by iglesiasbrandon** [comment]
hey @sb1752 thank you for submitting this issue, It has been accepted for TABConf 6! This workshop looks great we are looking forward to it.

**Comment by sb1752** [comment]
Thanks!

**Comment by miketwenty1** [comment]
@sb1752  

We are collecting an additional attribute for the workshops. Please update your issue and include a line item on the difficulty level of the workshop with either "Beginner", "Intermediate", or "Advanced".

- Beginner: would be no prior knowledge needed, very few technical skills required for workshop
- Intermediate: At least some knowledge needed to not be lost, technical skills, Comp Sci, IT related experience is greatly beneficial
- Advanced: Potentially a strong working knowledge of certain technologies, libraries, fundamentals, Comp Sci, and related protocols.

Error on the side of more advanced than less advanced as we want to set strong expectations. Depending on what you pick please gauge your workshop accordingly.

**Comment by sb1752** [comment]
Sounds good, updated 👍

**Comment by iglesiasbrandon** [comment]
thank you for conducting this workshop
