### ISSUE TITLE
Let's Save Satoshi!

### ISSUE THREAD

**Issue by satsie** [TABConf/6.tabconf.com#67]
# Description

Fire up your laptop, crank up the Ace of Base58, and charge your Budgetcopter (just in case) because we are going to Save Satoshi! 

Save Satoshi? Yes. It’s 2139 and the Bitcoin network has suddenly come to a halt. There hasn’t been a new block for days. Join us as we get to the bottom of this by playing a new Bitcoin themed coding game called Saving Satoshi (https://savingsatoshi.com/). 

With a mix of technical text and code-based challenges, and exercises available in JavaScript or Python, Saving Satoshi is designed for anyone with basic coding skills. Players will complete test-driven, REPL-based lessons, while learning some Bitcoin history and culture along the way.

You can think of this workshop like a modern day LAN party, minus the LAN, and with prizes. Bitcoin is serious, but this game is designed to be fun. We hope you’ll join us on this exciting adventure.

Now be quick, Satoshi needs you!

### What is this workshop about? Provide as many details as possible. 

In this workshop we’ll be getting together to play through Saving Satoshi (https://savingsatoshi.com/), a game we created to inspire a new generation of Bitcoin developers. We believe that learning Bitcoin should be just as cool as the technology so many of the activities are code based and cover topics like mining, cryptographic signatures, transaction construction, Bitcoin Script, Lightning, and more.

Prizes will be awarded to participants that finish first or get the furthest, and we’ll have additional swag for each chapter of the game that players complete. Saving Satoshi contributors will be present to answer questions and accept feedback.

### What would an attendee learn from this workshop?

In order of appearance, here are some of the topics that the game covers:
- Decoding the hidden message in the genesis block
- Hashing to find the next block and basic dynamics of pooled mining
- Elliptic curve cryptography and public-private keypairs
- Message signing and verification
- Parts of a transaction and constructing one
- Assembling transactions for a block template
- Using the Bitcoin Core RPC API and calculating the block subsidy
- Bitcoin Script
- How the Lightning Network works

### Is there anything attendees should read up on before they attend this talk?

No. Saving Satoshi is designed to be a gentle and welcoming entry point to Bitcoin development. The only thing required is a basic level of coding. Familiarity with JavasScript or Python is helpful. 

While this game was developed as a complement to existing educational resources, it may be of particular interest to those seeking a break from more passive material like books and talks, or to those where that style of learning does not resonate as well.

### Is there anything attendees should set up before the workshop?

Bring a laptop with a web browser like Chrome or Firefox.

### Relevant Links

None

# About the Speaker

Satsie

### Social Links
- Personal website: https://satsie.dev/ 
- GitHub: https://github.com/satsie
- Nostr: https://njump.me/npub1fhmmgwe6fk6tn83ahttt6ruyyfnjdm7k8tn7qflert9ajx6dhfyqf3nzcu
- Twitter: https://twitter.com/satsie

# Workshop Details

### Length of workshop

I’m not sure how long this workshop should be. Anywhere between 2-4 hours seems appropriate. Participants can come and go as they please.

### Preferred Day/Time Slot 

Time: 1-4pm or 2-5pm
Day: Thursday 10/24. **Not** Saturday 10/27.

**Comment by iglesiasbrandon** [comment]
hey @satsie this workshop looks awesome; it has been accepted for TABConf 6!

**Comment by satsie** [comment]
Thanks so much @iglesiasbrandon! Looking forward to it ☺️

**Comment by miketwenty1** [comment]
@satsie  

We are collecting an additional attribute for the workshops. Please update your issue and include a line item on the difficulty level of the workshop with either "Beginner", "Intermediate", or "Advanced".

- Beginner: would be no prior knowledge needed, very few technical skills required for workshop
- Intermediate: At least some knowledge needed to not be lost, technical skills, Comp Sci, IT related experience is greatly beneficial
- Advanced: Potentially a strong working knowledge of certain technologies, libraries, fundamentals, Comp Sci, and related protocols.

Error on the side of more advanced than less advanced as we want to set strong expectations. Depending on what you pick please gauge your workshop accordingly.

**Comment by satsie** [comment]
@miketwenty1 is there an "all levels" option? The first 3 chapters of the game are beginner, and things get progressively harder each chapter after that. I don't know how far people can make it in 2 hours anyway, certainly not through all 10 chapters.

**Comment by miketwenty1** [comment]
@satsie looks like Brandon took liberty of giving you all the difficulty labels, haha can't wait!

**Comment by adamjonas** [comment]
@iglesiasbrandon @miketwenty1 can you please also add @pinheadmz and @benalleng as co-hosts?

**Comment by iglesiasbrandon** [comment]
Hey @adamjonas, to assign them to this issue, they need to ACK it. Can you reach out and ask them to do so?

**Comment by pinheadmz** [comment]
ACK

**Comment by benalleng** [comment]
ACK

**Comment by iglesiasbrandon** [comment]
Thank you for conducting this workshop!
