### ISSUE TITLE
Distributed Charge - BIKE + BitAxe

### ISSUE THREAD

**Issue by AndySchroder** [TABConf/6.tabconf.com#68]
# Description

Last year we had Distributed Charge - BIKE where riders could generate electricity and be paid for the work that they input into the system using lightning (https://github.com/TABConf/2023.tabconf.com/issues/83). Most riders wished that the device would mine bitcoin instead of send the energy back into the electricity grid.

This time we'll have a BitAxe miner attached to use some of that energy. We'll have the BitAxe connected to a lightning enabled mining pool. So, the flows will be like this

**Energy**: Human Energy -> Electrical Energy -> Distributed Charge -> BitAxe

**Sats**:  Human <- Distributed Charge <- Mining Pool

### What would an attendee learn from this workshop?

- Their hash rate
- How hard it is to generate a W*hour of energy and a satoshi
- How the bitcoin lightning network can be used for peer to peer energy trade
- Why LNURL is bad and BOLT12 is good.

# About the Speaker
http://andyschroder.com/

# Workshop Details
### Length of workshop
Would like to be setup all week with a few posters explaining the above more visually.

**Comment by iglesiasbrandon** [comment]
hey @AndySchroder this has been accepted for TABConf 6! We will figure out a good place for you to set it up for the week!

**Comment by asherp** [comment]
@iglesiasbrandon We're happy to have @AndySchroder back in our space if possible.

**Comment by EllyPembroke** [comment]
@iglesiasbrandon does @AndySchroder need to submit a separate issue to park his bike at NextGen for day 3&4?

**Comment by iglesiasbrandon** [comment]
no this one is good!

**Comment by AndySchroder** [comment]
@asherp and @EllyPembroke hosted a great room last year, would love to be placed with them again! Been working with @skot and @bboerst on the BitAxe lately, making some great progress there!

**Comment by AndySchroder** [comment]
Okay, so will I be setup for 2 or 4 days this year?

**Comment by asherp** [comment]
@AndySchroder I think 2 days. I'll double check

**Comment by iglesiasbrandon** [comment]
Thank you for hosting this!

**Comment by AndySchroder** [comment]
Here are some photos from the setup: http://AndySchroder.com/DistributedCharge/news/2024-11-09-BIKE/ .
