### ISSUE TITLE
streaming lightning payments with rolling HOLD invoices

### ISSUE THREAD

**Issue by AndySchroder** [TABConf/6.tabconf.com#69]
# Description

There are many products and services that are continuously delivered by a seller and consumed by the buyer. The quantity of the product and the time duration over which the product is delivered can often times be unknown when the two parties first begin doing business together. Examples included electrical energy at an electric car charging station, gasoline at a fuel station, water, natural gas, or electrical energy delivered to a home, cellular phone service, wireguard tunneling services, video streaming, and more.

In all of these cases, both buyer and seller would like to minimize their risk. In the physical world, we can't eliminate risk completely, but we can make tradeoffs and achieve a practical user experience depending on the buyer's risk tolerance.

Rolling HOLD invoices allows the buyer to put some trust into the seller and make over payments for the unknown amount of product and service that they will consume, but still give the opportunity for the seller be honest and reconcile an exact, lower payment size when the business transaction finally comes to an end, then cancelling any open and non-exact HOLD invoices.

HOLD invoices are preferred over traditional invoices because the buyer does not need to be authenticated, which is typically required in a traditional refund process, and the buyer's privacy is not impacted like it is in a traditional refund process over lightning. BOLT12 may help to resolve these issues, but it is far from being fully adopted into the lightning ecosystem and rolling HOLD invoices can work right now.

Rolling HOLD invoices are expected to enable two use cases:

1. Manual low frequency streaming of large payments.
2. Automated high frequency streaming of small payments when the buyer or seller is expected to have poor quality network connectivity.

# About the Speaker
http://andyschroder.com/

# Talk Details
### Length of Talk:
20 minutes

### Preferred Day/Time Slot 
Would rather not go the first day.

**Comment by asherp** [comment]
@AndySchroder we're happy to have you in the NextGen village!

**Comment by AndySchroder** [comment]
Great!

**Comment by iglesiasbrandon** [comment]
Thank you for hosting this!

**Comment by AndySchroder** [comment]
Slides from the talk: http://AndySchroder.com/static/pdf/DistributedCharge/2024-10-26-rolling_HOLD_invoices.pdf .
