### ISSUE TITLE
Warnet Workshop

### ISSUE THREAD

**Issue by mplsgrant** [TABConf/6.tabconf.com#70]
# Preamble

We have two related submissions featuring [warnet](https://warnet.dev/): a Builder Day (#61) for exploring warnet and a more traditional workshop focused on getting started running a warnet scenario.

# Workshop Submission
## Description
Get going with Warnet.
Warnet is a tool to monitor and analyze the emergent behaviors of Bitcoin networks.

### What is this workshop about? Provide as many details as possible.
Get going quickly with warnet. Spin up a Bitcoin network, and start running your first scenario.

### What would an attendee learn from this workshop?
Attendees can expect to encounter advanced Bitcoin network scenarios ranging from historical attacks to possible future changes

## Is there anything attendees should read up on before they attend this talk?
Familiarize themselves with Bitcoin Functional tests: https://github.com/bitcoin/bitcoin/tree/master/test/functional#functional-tests

### Is there anything attendees should set up before the workshop?
Clone the repo at https://github.com/bitcoin-dev-project/warnet
Follow the [Quick Run instructions](https://github.com/bitcoin-dev-project/warnet/blob/main/docs/quickrun.md).

## Relevant Links
Familiarize themselves with Bitcoin Functional tests: https://github.com/bitcoin/bitcoin/tree/master/test/functional#functional-tests

## About the Speaker
Facilitator - [mplsgrant](https://github.com/mplsgrant)

### Social Links
Github - https://github.com/bitcoin-dev-project/warnet
Website - https://warnet.dev/

## Workshop Details
* Length of workshop: 1 hour
* Preferred Day/Time Slot: 2pm would be ideal but happy to take what’s available!

**Comment by miketwenty1** [comment]
@mplsgrant this sounds really cool, do you have any youtube/video, public demo of this yet?

**Comment by iglesiasbrandon** [comment]
hey @mplsgrant this issue has been accepted for TABConf 6! 

We are collecting an additional attribute for the workshops. Please update your issue and include a line item on the difficulty level of the workshop with either "Beginner", "Intermediate", or "Advanced".

Beginner: would be no prior knowledge needed, very few technical skills required for workshop
Intermediate: At least some knowledge needed to not be lost, technical skills, Comp Sci, IT related experience is greatly beneficial
Advanced: Potentially a strong working knowledge of certain technologies, libraries, fundamentals, Comp Sci, and related protocols.
Error on the side of more advanced than less advanced as we want to set strong expectations. Depending on what you pick please gauge your workshop accordingly.

**Comment by iglesiasbrandon** [comment]
hey @mplsgrant just wanted to bump this issue. can you take a look at the message above ^

**Comment by mplsgrant** [comment]
@iglesiasbrandon This workshop has both Advanced and Intermediate elements. Would it be okay to apply both labels?

**Comment by iglesiasbrandon** [comment]
Hey @mplsgrant thank you for the info! We can only apply 1; I'm going to market as an intermediate.

**Comment by mplsgrant** [comment]
@iglesiasbrandon In that case, could we set this workshop to Advanced? We do want to err on the side of more advanced.

**Comment by mplsgrant** [comment]
@iglesiasbrandon I noticed that this workshop is scheduled for Wednesday. Would it be possible to have it moved to Thursday or Friday? Sorry for having to ask for a schedule change. I didn't realize that there would be workshops that early in the week. We were hoping that participants could check out the Builder Day and then have a chance to check out the Workshop afterwards.

**Comment by iglesiasbrandon** [comment]
Noted. I will slot this into a spot on day 3 later this week when we work on the schedule. If you notice it has moved back, please ping me again! (I'm running out of RAM in my brain :)

**Comment by adamjonas** [comment]
@iglesiasbrandon @miketwenty1 can you also add @pinheadmz, @maxedwards, and @josibake as co-hosts?

**Comment by mplsgrant** [comment]
I will be unavailable during this workshop due to illness.

**Comment by iglesiasbrandon** [comment]
thank you for conducting this workshop!
