### ISSUE TITLE
Verifiable Computation on Bitcoin

### ISSUE THREAD

**Issue by AllenAJ** [TABConf/6.tabconf.com#71]
# Description
### What is this panel discussion about? Please give us as many details as possible. 
This panel is about verifiable computation on Bitcoin, i.e. conducting computation offchain and verifying it onchain. The user cases of verifiable computation on Bitcoin include outsourced computation, state transition of rollup, the peg-in/peg-out in asset bridge etc.

While verifiable computation on Ethereum has been proved feasible, it's challenging to do the same on Bitcoin. Currently, we have a couple of solutions, and they all have pros and cons.

### What would an attendee learn from this talk?
- The history of verifiable computation
- The applications of verifiable computation on Bitcoin and the trending
- The challenges of implementing verifiable computation on Bitcoin
- Possible solutions to such challenges
- The pros and cons of solutions

### Is there anything folks should read up on before they attend this talk?
- https://en.wikipedia.org/wiki/Verifiable_computing
- http://www.contrib.andrew.cmu.edu/~bparno/papers/non-interactive-vc.pdf
- https://project-archive.inf.ed.ac.uk/ug4/20170882/ug4_proj.pdf

### Relevant Links

# About the panelist
- Charlie Hu

### Social Links
Twitter: https://x.com/CharlieHusats
Website: not maintained

# Panel Discussion Details
### Length of the panel discussion
30-60 min

### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by miketwenty1** [comment]
@AllenAJ is this primarily a proposal on Bitlayer? it's unclear.

**Comment by AllenAJ** [comment]
This is not primarily a proposal on Bitlayer. The discussion is centered around the broader topic of verifiable computation on Bitcoin. @miketwenty1
