### ISSUE TITLE
Workshop: Learning Real-World Pinning Attacks on Lightning Nodes

### ISSUE THREAD

**Issue by ariard** [TABConf/6.tabconf.com#75]
This talk is about teaching attendees how to do real-world pinning attacks on lightning nodes.

## The workshop

During this talk, we'll explore the well-known economic based pinning (rule 3 bip125) on
real-world conditions (testnet, signet, mainet) i.e a modified core lightning node with a
custom C2C on top of a bitcoin full node. We'll test some pinning attacks scenarios 
(second-stage HTLC transactions and commitment transactions) which are widely known before
TRUC policy and after TRUC policy (bip 431).

The modified patch constituting the pinning toolkit will be provided by me, the speaker,
and they will be made available at the time of the conference, as it can be a bit sensitive
of ethical infosec software material.

In function of the time slot (1h / 2h), we'll see how we do the demonstration, though the idea
is to have a "hands-on" workshop where attendees exercise pinning attacks on demo lightning nodes.
Format will be seen to match the traditional "black hat / defcon" briefing.

We won't explore the more advanced transaction-relay jamming attacks and stick to the basics.

## Attendees Pre-Requesite

- a burner laptop
- core-lightning installed
- bitcoind installed
- reading the pinning attacks [lightning docs](https://github.com/t-bast/lightning-docs/blob/master/pinning-attacks.md) / [bip431](https://github.com/bitcoin/bips/blob/master/bip-0431.mediawiki)
- smiles and good vibes

_Please note the burner laptop requirement ! That way this avoids some attendee making the
claim they have lost bitcoins while they clearly didn't follow basic security practices and
this avoids wasting everyone time after the fact with interrogation by the FBI, the U.S secret
service or other 3-letters agencies._

**Comment by miketwenty1** [comment]
@ariard  

We are collecting an additional attribute for the workshops. Please update your issue and include a line item on the difficulty level of the workshop with either "Beginner", "Intermediate", or "Advanced".

- Beginner: would be no prior knowledge needed, very few technical skills required for workshop
- Intermediate: At least some knowledge needed to not be lost, technical skills, Comp Sci, IT related experience is greatly beneficial
- Advanced: Potentially a strong working knowledge of certain technologies, libraries, fundamentals, Comp Sci, and related protocols.

Error on the side of more advanced than less advanced as we want to set strong expectations. Depending on what you pick please gauge your workshop accordingly.

**Comment by ariard** [comment]
@miketwenty1 

Thanks you for the feedback.

From my experience of attending workshop at past tab conf (e.g on zk proofs) the level of attendees was quite high technically. Yet with this one as I’m aiming to have attendee be quite hands on the topics, so I think it’s good to say it’s “advanced” rather than “intermediate", people have to be familiar with both full-node fundamentals and lightning.

**Comment by ariard** [comment]
@miketwenty1 

For this talk, as there are some difficulties in releasing offensive software tooling in the hands of an unknown conference audience, we’ll still do something on pinning attacks, though rather consider the defensive viewpoint of affected time-sensitive contracting protocols. So we’ll rather do a walkthrough of BIP431 on “Topology Restrictions for Pinning” (I’m not sure @glozow or another of the BIP author is around at this conf) and then compose groups of people for each type of multi-party applications / contracting protocols (coinswaps, lightning, coinjoin, discreet log contracts, batch payout transactions, bitvm bridge…) and see how BIP431 can be adapted (or not when there are protocol limits) for the fee-bumping flow of each use-case. 

More or less in the lines of the on-chain transaction relay workshops that happened on IRC few years ago:
https://github.com/ariard/L2-zoology/tree/master/protocols

Well-arrived in ATL, and seen the schedule from 3:00 to 5:00 pm Local Time, which is perfect to me. If we go through the protocol funding flow, the unilateral fee-bumping flow and the cooperative closure flow for each protocol with good time for each attendees group to actually do design work, I think we’ll go well over 1h30 of workshop.

**Comment by iglesiasbrandon** [comment]
thanks!
