### ISSUE TITLE
FOSS Malaise: Fighting through motivation black holes & productivity barriers

### ISSUE THREAD

**Issue by kdmukai** [TABConf/6.tabconf.com#76]
# Description
FOSS dev is a different beast than corp dev and is different even from working for a bitcoin company. We're driven by passion and exuberance, but we're often working alone or at least in greater isolation.

Not surprisingly, sometimes circumstances / life / etc knock us off our feet and out of our coding groove. And sometimes it's frustratingly hard as hell to resume. A funk. A malaise. Want to move forward but can't. Or just so emotionally fried that maybe we don't even want to go back.

I just went through some of this earlier this year. It really sucked. I'm sure I'm not the only one who's been through it.

## REVISED PLAN:
I've learned that there's some really exciting work being done to directly address these sorts of issues for FOSS devs. There isn't any kind of organized survival guide for FOSS malaise / burnout YET, but there's some powerful growing momentum that I'm eager to share.

### Basic outline:
* Share my experience: What combo of factors contributed, what challenges did I put in my own way, etc.
* What actually helped? Which specific strategies? What was the pace of improvement?
* Audience "round table": What are YOUR best tips, fixes, life hacks?
* What's the future? Update on the very early initiatives out there.
* Call to action: How you can help make those initiatives reality.

## What would an attendee learn from this talk?
Hopefully everyone will be made more aware of some of these motivation pitfalls and be armed with more strategies for how to recover should they feel a funk cloud gathering over them.

But most importantly, the call to action to support the people and orgs who are trying to address all this directly.

Step 1: We all need to talk more openly about a shitty reality in FOSS dev.
Step 2: Let's start proactively working on solutions.

---

# About the panelist
### Social Links
GitHub: [kdmukai](https://github.com/kdmukai)
Twitter: [KeithMukai](https://twitter.com/KeithMukai)

# Panel Discussion Details

~ 1hr.

Any day / time slot.

**Comment by jdlcdl** [comment]
Few would be courageous enough to want to talk about this.  I suspect many would be interested listeners.

**Comment by miketwenty1** [comment]
@kdmukai this is definitely an interesting idea. Do you have an idea on who potential moderator and panelist would be?

**Comment by kdmukai** [comment]
@miketwenty1 I'm hoping to recruit two more people who've gone through something similar (I'll get started on that hopefully this weekend). I don't think a separate moderator is needed; I can guide us through the phases of the convo easily enough.

**Comment by andrewlunde** [comment]
Keith, we discussed this casually in Nashville at Bitcoin Park on the back deck.

I'd be interested in joining the panel if you'll have me.

-Andrew https://www.linkedin.com/in/andrewlunde/

**Comment by iglesiasbrandon** [comment]
This might be a great way to kick off day 1 or day 2 because those days are centered around open-source contributions!

**Comment by kdmukai** [comment]
I finally put together the call for volunteers to join the panel.

https://twitter.com/KeithMukai/status/1831707222247608619

@andrewlunde you def had some awesome insights. As people start responding (hopefully!) I'll reach out to learn more about everyone's individual experiences and will try to figure out what the optimal mix might be.

**Comment by kdmukai** [comment]
Description updated.

Getting this proposal out in the world has helped spur some really great conversations and there's a lot of awesome positive momentum out there working towards solutions. Excited to talk about these efforts and end on an optimistic note!

Also reworked the structure to have more of the solutions discussion come directly from audience volunteers.

**Comment by kdmukai** [comment]
Pinging @btsea! Duration can be adjusted for any available time slot.

**Comment by iglesiasbrandon** [comment]
Thank you for hosting this talk!
