### ISSUE TITLE
UX Design for FOSS: SeedSigner Case Study

### ISSUE THREAD

**Issue by easyuxd** [TABConf/6.tabconf.com#78]
### What is this talk about?

How UI/UX Design impacted the SeedSigner project and how it can benefit other software developers and projects. In-depth presentation of the project's design process, challenges, insights, and future design plans, including key ideas that developers can take away to enhance their projects.

SeedSigner is an open source Bitcoin signing device that creates and manages private keys to create wallets and sign transactions. The SeedSigner mental model changed the way users think about their cold storage through the lens of education and mass adoption, and much work has gone into refining this model and presenting it within the software UI. It has unique technical constraints including a small 1.3” display that introduced many design challenges.

This talk will give an overview of the device and go into depth on how the user experience has evolved over the life of the project. The primary focus will be on the design and code overhaul that was the massive 0.5.0 redesign, the challenges the team faced, and the design rationale behind our decisions. The talk will also touch on interesting edge cases and problems unique to the project, and unsolved pain points related to both SeedSigner and the larger Bitcoin ecosystem that could be addressed in the future.

### What would an attendee learn from this talk?

The benefits of UX Design in open source Bitcoin projects, and actionable tips that developers can use to enhance their project quality and reach.

Design principles, technical hurdles, and creative solutions that were part of the SeedSigner UI redesign.

UX guidelines and information for SeedSigner contributors and for other Bitcoin projects to improve usability and create more consistency in design language, user flows, and content strategy.

The SeedSigner project has done a lot of work toward making Bitcoin storage technology and process more accessible, and we’re excited to share with others and aid Bitcoin adoption.

# About the Speaker
### Social Links
Github - https://github.com/easyuxd
Twitter - https://x.com/easyuxd

# Talk Details
### Length of Talk

30 minutes

### Preferred Day/Time Slot 

Oct 23-25
12-4pm preferred, flexible anytime

**Comment by kdmukai** [comment]
The amount of thought and care and expertise that @easyuxd has put into our GORGEOUS SeedSigner UI/UX has been just beyond astounding. Easy's work, insights, guidance are a HUGE part of SeedSigner's success.

I've learned a TON by working with him. He's thought deeper about certain things that I've only barely shrugged at.

I'm sure his talk will be a fascinating look behind the scenes into SeedSigner but, more importantly, will be an invaluable eye-opening perspective frame for every dev working in bitcoin. We devs are just such shit at UI/UX; Easy makes us better.

ps - I recommend a longer time slot. Including time for Q&A would be huge. Maybe even game plan out roughly 50/50 to make it more workshop-y.

**Comment by easyuxd** [comment]
@miketwenty1 @iglesiasbrandon 
Is there any update from the team on fitting this into the agenda?

I’m not seeing any other design-related talks this year -- I think it would add a lot to the conference, given it’s aimed toward an audience of engineers.

Appreciate your time and consideration, and excited for the conference!

**Comment by iglesiasbrandon** [comment]
hey @easyuxd no, not yet :( we are doing our best. we will comment on this issue if we are able to squeeze it in.

**Comment by easyuxd** [comment]
@iglesiasbrandon 
Thanks for your help, Brandon. This presentation is complete, and I'm willing to flex to any slot that's available or opens up.

**Comment by asherp** [comment]
@easyuxd how much time do you need for your talk? we might have room on the NextGen stage.

**Comment by easyuxd** [comment]
Thanks @asherp. I had planned for 30 minutes.

**Comment by asherp** [comment]
@easyuxd ok, we got you Saturday after the Fusion 360 talk.

**Comment by easyuxd** [comment]
Big thanks for fitting me in, @asherp! Actually, I won't be at the conference on Saturday. I'm only in town Wed-Fri. Do you have anything available on the other days?

**Comment by EllyPembroke** [comment]
Does Friday at 1pm work for you?

**Comment by easyuxd** [comment]
Hi @EllyPembroke. Yes, Friday at 1pm would be perfect.
