### ISSUE TITLE
Practical and economical considerations for Bitcoin rollups

### ISSUE THREAD

**Issue by ekrembal** [TABConf/6.tabconf.com#79]
# Description

### What is this talk about? Give us as many details as possible.
I would like to discuss practical considerations when building a rollup, including the cost of using Bitcoin as a data availability layer and optimistic verification techniques like BitVM for bridges.

### What would an attendee learn from this talk?
- Trust assumptions for various rollup designs
- TPS calculations for EVM-based rollups
- Capital requirements for BitVM-based bridges
- Attack vectors in optimistic verification
- ...and more (tba)

### Is there anything folks should read up on before they attend this talk?
- [Citrea Documentation](https://docs.citrea.xyz/)
- [Exploring Bitcoin for Data Availability](https://www.galaxy.com/insights/research/exploring-bitcoin-for-data-availability/)
- [BitVM2](https://bitvm.org/bitvm2)

### Relevant Links
- [Understanding Citrea’s Optimistically Verified ZK Proofs presentation](https://docs.google.com/presentation/d/16XjjT_EzYWccnj4HYtOIttlaf3Qg2ZqxZGLF8u9Z9bU)
- [Building a bridge around a SNARK verifier presentation](https://docs.google.com/presentation/d/1a1SLeLGF8UobPErcBubgwweDGahTN3Fx2-e_bXQnzzQ)
- All the source code for our rollup is publicly available:
  - [https://github.com/chainwayxyz/citrea](https://github.com/chainwayxyz/citrea)
  - [https://github.com/chainwayxyz/clementine](https://github.com/chainwayxyz/clementine)
  - [https://github.com/chainwayxyz/BitVM](https://github.com/chainwayxyz/BitVM)

# About the Speaker

### Social Links
- GitHub: [ekrembal](https://github.com/ekrembal)
- Twitter: [ekrembal_](https://twitter.com/ekrembal_)
- Linkedin: [ekrembal](https://linkedin.com/in/ekrembal/)

My Talks:
- [Building a Bitcoin bridge around a SNARK verifier](https://youtu.be/3INbbMoTqAw)

My other talks about Privacy Pools and Proof of Innocence (our previous projects on private transactions on EVM):
- [DappCon 2023: The Future of Privacy and Proof of Innocence](https://www.youtube.com/watch?v=HnIO3oU2eD8)
- [PROGCRYPTO: The Future of Privacy and Proof of Innocence](https://www.youtube.com/watch?v=NoQ5WlcH938)
- [Cryptİst: Proof of Innocence and Privacy in Blockchain](https://www.youtube.com/watch?v=crz_fdxEK54)

# Talk Details

### Length of Talk
20 minutes

### Preferred Day/Time Slot 
i might miss the last day

**Comment by miketwenty1** [comment]
@ekrembal is there currently any working rollups on any signets, testnets, or mainnet using BitVM?

**Comment by ekrembal** [comment]
@miketwenty1 , we currently have a devnet running on our own signet (just faster blocks but no additional soft forks etc.) that uses the signet as DA layer. It has a mock bitvm bridge. By the time of the conference we are planning to make the BitVM bridge work on testnet.
Here is the signet explorer: https://mempool.signet.citrea.xyz/
Here is our batch explorer: https://citrea.xyz/batch-explorer

**Comment by ekrembal** [comment]
Hi @iglesiasbrandon,
Has this proposal been taken into consideration? I need to arrange my flights based on the acceptance.

**Comment by iglesiasbrandon** [comment]
Hey @ekrembal, we are still reviewing issues for TABConf 6. This one has not been accepted for the main stage yet. One of the villages might want to accept it now. @asherp for visibility on this issue.

**Comment by asherp** [comment]
@ekrembal We have space for you in the NextGen village. Accepted

**Comment by ekrembal** [comment]
@asherp, could you elaborate more on the content of NextGen Village? My talk is aimed at an intermediate to advanced audience. I feel that NextGen Village might be more suited for beginners and crafting workshops. I’ll be discussing bridge designs, which requires advanced knowledge of Bitcoin script and UTXOs. It will be similar to this: https://youtu.be/3INbbMoTqAw, but more up to date. Do you think this talk would be appropriate for NextGen Village?

**Comment by asherp** [comment]
Hi @ekrembal Yes, the NextGen village is intended for more general audiences, so I'll revoke for now. By the way, there will be another more introductory bitvm-related talk that we're hosting. See #104

**Comment by btsea** [comment]
@ekrembal @asherp I would say not to let the overall theme of a village detract from you accepting a spot there. Ultimately, folks will see the entire TABConf schedule as a whole, and will pick talks based on their interest. For example, in the Socratic Village we will accept a small number of non-socratic talks that are not able to fit on the main stage as an act of good will, even though they don't fit our theme.

**Comment by ekrembal** [comment]
@btsea @asherp, Ok then, i can go for Socratic Village or NextGen Village. I am buying my tickets. Please approve me to whichever you think fits best. Thanks.

**Comment by btsea** [comment]
@asherp Do you still have room for this talk?

**Comment by asherp** [comment]
@btsea Our schedule is getting pretty tight, so feel free to take it.

**Comment by btsea** [comment]
Sure thing! @ekrembal I have formally accepted the talk. Please let me know once you have arranged your flights and if you will be available on the last day or not. I will then work you into the schedule according to your availability. 

Thanks!

**Comment by ekrembal** [comment]
Hi again @btsea, I arranged my flights and i won't be available on the last day.

**Comment by btsea** [comment]
Thanks for the update @ekrembal. You are scheduled for 2:30PM on Day 3.

**Comment by iglesiasbrandon** [comment]
Thank you for conducting this talk!
