### ISSUE TITLE
safe 24 hour parking lots

### ISSUE THREAD

**Issue by AndySchroder** [TABConf/6.tabconf.com#8]
would like to know the 24 hour parking lot situation for the neighborhood for the 2024 venue. In 2023 the only options were valet parking (i.e. give your car **keys** to a total stranger and then pay them a lot of money) or 1 super dangerous parking lot. there was ample daytime only parking at reasonable prices, but all those parking lots all shut down after dark, likely because the crime was so high.

**Comment by miketwenty1** [comment]
Depending on which hotel you choose, you may want to find parking there. We are at a new venue this year.
https://6.tabconf.com/hotel
Let me know if you have any other questions.

**Comment by iglesiasbrandon** [comment]
we will add this information to the FAQ section of the website; thank you for brining this up @AndySchroder
