### ISSUE TITLE
Crowdfunding your Bitcoin Project

### ISSUE THREAD

**Issue by themuzzman** [TABConf/6.tabconf.com#80]
# Crowdfunding your Bitcoin Project
Thunder Funder is a Regulation Crowdfunding portal focused on funding open-source software and innovative technology companies. Our mission is to provide retail investors access to high-quality early-stage investments while supporting the growth of open-source projects. We provide a platform that democratizes early-stage technology investing, making it accessible to accredited and non-accredited investors.
Attendees will learn about a new (totally radical) option for raising funds for their open-source or Bitcoin startup, project, or business. How do you get funded straight out of the hackathon? Better call Saul.... No! Better call Muzz. Attendees will also learn how they can invest and participate in funding these projects. This is not a donation. These are real investments and give the general public a chance to own a piece of the companies and projects they love. 
Traditional venture capital or investment funds require the investors to be accredited. Under a [RegCF](https://www.sec.gov/resources-small-businesses/exempt-offerings/regulation-crowdfunding) offering, investors can be (pretty much) anyone and still have an opportunity to invest alongside the "suits" and often on nearly the same terms. There is a ton of information on the internet about existing RegCF portals and the history of how this came about with the JOBS Act (2012). There are a number of oversaturated, borderline scammy RegCF portals that focus on quantity and not quality. None of them are focused on open source or Bitcoin.
### [Crowdfunding Benefits](https://www.uschamber.com/co/run/business-financing/equity-crowdfunding-benefits)
# Mike Jarmuz (The Muzz Man).... 
is a pretty rad dude. His goal is to democratize investing for plebs and whales alike. Founder of [Lightning Ventures](https://ltng.ventures), they invested in over 50 Bitcoin startups and operated the world's largest group of Bitcoin-focused investors. [Thunder Funder](https://thunderfunder.com) is the next evolution to bring these opportunities to a whole new gang of peeps.  He tries to put some fun in the funding process and, totally digs educating founders and investors. He tries to do good shit yo. That'd be what life is all about. Chat him up. 
### Social Links
[Github ](https://github.com/themuzzman)
[Muzz's Twitter](https://twitter.com/mikejarmuz)
[Lightning Ventures Twitter](https://twitter.com/ltngventures)
[Thunder Funder Twitter](https://twitter.com/thunderfundercf)

[Thunder Funder Website](https://thunderfunder.com)
[Lightning Ventures Website](https://ltng.ventures)

# WTF is Thunder Funder, and why should you care?
I could do it in 20 minutes, but really, if I get 30, that would be rad. I would rather have less time and maximum exposure than have more time and less exposure. I really want the open-source and technical Bitcoin community to understand what I am trying to do with this platform, how they can use it for their projects, and what this is all about. We're going to have co-founder matching, profiles for builders, and some other cool stuff. I would also even love to spend 5 minutes getting feedback from people in the room. And they can be harsh with me or grill me on this. I ain't got nothing to hide. 
Wheneves... I would really like to try to get a slot on the main stage, but I know you guys are really cool, and I'm just thankful to participate in any way. 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by miketwenty1** [comment]
@themuzzman can rename this talk "Crowd Funding your Bitcoin Project"?

**Comment by themuzzman** [comment]
Done

**Comment by bnonni** [comment]
Hey, @themuzzman, this issue has been accepted for TABConf 6; we are looking forward to having you there!

**Comment by miketwenty1** [comment]
based on conversation with @themuzzman we are closing this issue.
