### ISSUE TITLE
Bitcoin rollups 101

### ISSUE THREAD

**Issue by john-light** [TABConf/6.tabconf.com#81]
# Description
### What is this talk about? Give us as many details as possible. 

Since the [earliest](https://tr3y.io/articles/crypto/bitcoin-zk-rollups.html) [explorations](https://github.com/alpenlabs/Technical-Whitepaper/blob/main/whitepaper_v085.pdf) of [bitcoin rollups](https://bitcoinrollups.org/), we have seen a Cambrian explosion of experimentation with rollups on bitcoin. From sovereign rollups to BitVM rollups to theoretical L2 rollups based on new op codes, the design space for building bitcoin rollups continues to grow.

This talk will cover the basics of what a rollup is, what the benefits, costs, and tradeoffs of rollups are compared to other protocols built on bitcoin, what the options are for building rollups on bitcoin today, and what possibilities may exist in the future given new scripting capabilities such as covenants, stack element concatenation, and arithmetic op codes.

### What would an attendee learn from this talk?

An attendee will learn answers to the questions:
- What is a rollup?
- What are the benefits, costs, and tradeoffs of bitcoin rollups compared to e.g. Lightning, sidechains, Ark, altcoins?
- What types of rollups can be built on bitcoin?
- Why would someone use a bitcoin rollup? Related, what kind of new products can developers build using a bitcoin rollup?
- Do any of the soft fork proposals out there help or hurt bitcoin rollups?

Also open to suggestions for other questions this 101-level talk should answer!

### Is there anything folks should read up on before they attend this talk?

This talk is for people who have never heard of rollups, or have heard about rollups but know little to nothing about them, and are interested in learning the basics about them from someone they can talk to in person. So no prior reading is necessary. But if you want to get a head-start so you can come prepared with questions or ideas, these resources will be of interest:

https://bitcoinrollups.org

https://github.com/alpenlabs/Technical-Whitepaper/blob/main/whitepaper_v085.pdf

https://lightco.in/2023/03/13/sovereign-rollups

https://lightco.in/2023/12/13/lightning-validia-rollups

### Relevant Links

https://www.bitcoinrollups.io

# About the Speaker

John Light currently works on product at [Alpen Labs](https://alpenlabs.io) and is a research advisor at [bitcoinlayers.org](bitcoinlayers.org). Before that, he was the ZK Rollup Research Fellow at the Human Rights Foundation, among many other roles in other bitcoin-related projects over the years.

### Social Links
Github: https://github.com/john-light
Twitter: https://twitter.com/lightcoin
Website: https://lightco.in

# Talk Details
### Length of Talk

45-60 mins

### Preferred Day/Time Slot 

mid-day or afternoon. preferably before any other rollup-related talks that get on the schedule, so that people can first learn the basics at my talk then go to the more advanced talks later and not feel totally lost :)

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by bnonni** [comment]
Hey, @john-light, this issue has been accepted for TABConf 6; we are looking forward to having you there!

**Comment by jegamboafuentes** [comment]
Hey @john-light! 👋

I saw your awesome issue and thought I'd let you know about [Lightning Bounties](https://www.lightningbounties.com/)! 🚀 It's a super easy-to-use app where you can add a Bitcoin reward to this issue, encouraging devs to jump in and help you solve it.

Here’s a quick tutorial to get started: [Lightning Bounties Tutorial](https://docs.lightningbounties.com/docs/posting-a-bounty/create-a-github-issue-and-submit-a-new-reward). 💡 You can post your issue there, set up a bounty, and whoever cracks the code gets rewarded instantly in Bitcoin. 🔥

Let me know if you have any questions or need help setting it up!

Cheers! ⚡

**Comment by iglesiasbrandon** [comment]
Thank you for hosting this!
