### ISSUE TITLE
Taproot Assets on Lightning Workshop

### ISSUE THREAD

**Issue by HannahMR** [TABConf/6.tabconf.com#82]
## Taproot Assets Workshop

This workshop will help developers who are thinking about building with Taproot Assets to get hands-on experience using the protocol focusing on using the new Lightning functionality.

Specifically, here is what we will practice during the workshop:
-   Using tapd via litd
-   Review of the new v0.4 features
-   PSBT swaps
-   Review of Assets in Lightning channels
-   Edge Nodes
-   The RFQ process
-   Price oracles
-   Setting up a Taproot Assets node
-   Configuring an Edge Node
-   Sending assets on Lightning
-   Sending assets through an Edge Node

###  What would an attendee learn from this workshop?
Our goal is for attendees to leave the workshop with an understanding of the new Lightning functionality of Taproot Assets, and with some experience setting up a node, opening asset channels, sending assets on Lighting, and working with an Edge node.

As this workshop is designed to assist people looking to build with the protocol, we will endeavor to customize the discussion and work to the audience in attendance and to take time to answer any questions attendees may have about the protocol.

### Relevant Links for Preparation
The plan is to have workshop participants working with their own tapd node on one of the test networks. With this setup participants can send assets to each other. More specifics on that soon.  
  
Participants can prep for the workshop by having a look at the below resources.

-   The Taproot Assets docs: [https://docs.lightning.engineering/the-lightning-network/taproot-assets](https://docs.lightning.engineering/the-lightning-network/taproot-assets)
-   The Taproot Assets Intro video: [https://youtu.be/-yiTtO_p3Cw](https://youtu.be/-yiTtO_p3Cw)
-   The Tapd demo video playlist: [https://www.youtube.com/watch?v=pYh-4EfdZaM&list=PL-3jjRT_28Sh3u_9CPVJkm8BLomh23QGk](https://www.youtube.com/watch?v=pYh-4EfdZaM&list=PL-3jjRT_28Sh3u_9CPVJkm8BLomh23QGk)
  

### About the Speaker
Hannah Rosenberg is a Developer Advocate for Lightning Labs. Her journey with Bitcoin began in 2012, sparked by her interest in economics. With a strong technical background and years of experience as a web developer, Hannah founded Velas Commerce in 2014, focusing on Bitcoin integration and consulting services. Deeply rooted in the Bitcoin community, Hannah spent five years as the organizer of Chicago's Bitcoin and Open Blockchain meetup. Currently, she serves as the organizer of the San Juan BitDevs. In 2017, Hannah began sharing her knowledge of the technology through teaching. She has been an educator for various organizations, including non-profits, Saylor Academy, and her alma mater, UIC.

#### Social Links

-   Twitter: https://x.com/hmichellerose
-   LinkedIn: [https://www.linkedin.com/in/hannahmr/](https://www.linkedin.com/in/hannahmr/)
-   Nostr: hannahmr@snort.social
-   Github: [https://github.com/HannahMR](https://github.com/HannahMR)

### Workshop Details
120 mins

**Comment by bnonni** [comment]
Hey, @HannahMR we have accepted this issue for TABConf 6! We're looking forward to having you there! Just want to draw your attention to the fact that we also added a label of "Advanced" for this talk. If you think that's not reflective of the content, please let us know!

**Comment by dstadulis** [comment]
Here are the commands to start in polar
https://docs.google.com/presentation/d/1rkh3W9jon1vmk0TWUorStSHp5qG19dypBW55a7WcbmI/mobilepresent?slide=id.g30b38929169_0_0

**Comment by iglesiasbrandon** [comment]
thank you for conducting this workshop!
