### ISSUE TITLE
BitDevs Socratic Village #4

### ISSUE THREAD

**Issue by btsea** [TABConf/6.tabconf.com#83]
Super excited to put together the fourth edition of the BitDevs Socratic Village! Our content will be consistent with the event styles available in prior years. We may introduce some new content as well, but that is TBD!

### Description

The Socratic Village is based on the concept of a Socratic Seminar/Circle, a collaborative dialogue that is facilitated by participants examining a subject or text and articulating their questions and viewpoints. The group setting helps participants construct meaning through analysis, interpretation, listening and active engagement in conversation. **Content in the Socratic Village will primarily be a combination of Socratic Sessions with general themes and topic-specific Socratic Panels.** 

The Socratic Sessions will be a condensed version of a Socratic-style meetup. A discussion leader will curate some content based on a general theme and come prepared to give background on the material and provide discussion questions for the group.

The Socratic Panels will be driven by a small group of experts on a specific subject matter. The panelists will first give a 5-10 minute presentation on the topic, after which the panelists should expect to field questions from the community as well as have their own questions to stimulate discussion. The crowd can both ask and answer any questions. A moderator will come prepared with additional questions to stimulate discussion.

_**The Village will be closed out with Hardcore Trivia!**_ 

### Project Details

This is a village run and hosted by BitDevs communities spanning multiple cities. We will accept proposals for Socratic Panels from the general public alongside those we design ourselves. For inspiration, please see [last year's programming](https://github.com/orgs/TABConf/projects/1/views/7).  We are also willing to host speakers who might not be able to fit in on the main stage in certain limited circumstances. 

### Organizers
- @btsea (SF LitDevs, SF BitDevs)
- @RazTeve (BitDevs Miami)
- @HannahMR (San Juan BitDevs)
- @murchandamus (BitDevs NYC)
- @vnprc (Triangle BitDevs)

**Comment by btsea** [comment]
Updated with additional organizers!

**Comment by iglesiasbrandon** [comment]
thank you for hosting the village again! its always a hit at TABConf!
