### ISSUE TITLE
Technical Architecture for a 3rd party open source offering for Institutions to leverage and upgrade to Bitcoin self custody wallet Infra

### ISSUE THREAD

**Issue by sagungargs15** [TABConf/6.tabconf.com#84]
# Description
### What is this panel discussion about? Please give us as many details as possible. 

- How does the technical architecture look for a 3rd party open source offering for institutions to leverage and upgrade to Bitcoin self custody wallet Infra 
- Enterprise self-custody wallet Infrastructure to upgrade institutions to enable a new business model on Bitcoin standard to make Bitcoin as a modern Savings Account for the affluent wealth class to access it better from their traditional relationship managers.
 
### What would an attendee learn from this talk?
*Target Audience:* Wallet Provider Startups, Entrepreneurs, CTO Founders, CISOs and 
*Topics Covered:* The panel should cover the following Angles
      a. Where is the most profitable business in the Institutional wave of adoption in Bitcoin space - Enterprise Wallet Software. From an Enterprise Bitcoin self-custody startup standpoint where is the TAM/SAM/SOM market going for such a white labelled offering
      b. How do new technical founders pickup problem statements that have huge profit margins baked in Wallet Infra business? 
      c.  Enterprise wallet infra features like: Multi-party Bitcoin vault architecture, Revaulting Transactions, Revocation Transactions, Emergency Deep Vault, Cosigning servers, Spending policy engines, Key management(Manage multiple UTXOs co-owned by 
N stakeholders)
      d.  Containerised FOSS Deployments of Wallets with optionality of Enterprise support as a new business model for a white labelled OSS product. 
      e. How does the technical architecture and considerations respond to market needs of OnPrem based traditional banking Architectures

### Is there anything folks should read up on before they attend this talk?

1. How Traditional institutions will adopt/upgrade to Bitcoin Standard - https://www.youtube.com/watch?v=XugPQ2cDZu8
2. Where is the Profit in Bitcoin startups for CTO founders to focus on technology that earns money - https://tvp.fund/whitepapers/bitcoin-venture-capital-research/
3. Liana Wallet - https://www.youtube.com/watch?v=i2BfMsns-ks
4. Miniscript - https://www.youtube.com/watch?v=6rcXtuERxjs
5. Expanding/Contracting Multisig - https://www.youtube.com/watch?v=i2BfMsns-ks
6. Revault Architecture - https://github.com/revault/revaultd/blob/master/README.md
7. DIY vs Collaborative MultiSig: https://bitcoinmagazine.com/technical/diy-multisig-vs-collaborative-custody-multisig
8. Open Source & Institutional Custody - https://unchained.com/open-source
9. OpenVault: https://github.com/sagungargs15/openvault

### Relevant Links

# About the panelist
### Social Links of Panelist 1: Sagun Garg
*GitHub:* https://github.com/sagungargs15
*Twitter/X:* https://x.com/sagungarg
*Linkedin:* https://www.linkedin.com/in/sagungarg/
*Website:* https://sagungarg.com/
*Previous Panel Talk1*: https://youtu.be/XugPQ2cDZu8?si=3ApBaeuOWww1vgb4&t=427
*Previous Panel Talk2*: https://youtu.be/76lVeHxGh_A 
*Project Repo OPEN VAULT*: https://github.com/sagungargs15/openvault

### Social Links of Panelist 2
*GitHub:* <Insert..Speaker Wanted>
*Twitter/X:* <Insert..Speaker Wanted>
*Linkedin:* <Insert..Speaker Wanted>
*Website:* <Insert..Speaker Wanted>

### Social Links of Panelist 3
*GitHub:* <Insert..Speaker Wanted>
*Twitter/X:* <Insert..Speaker Wanted>
*Linkedin:* <Insert..Speaker Wanted>
*Website:* <Insert..Speaker Wanted>

# Panel Discussion Details
### Preferred Day/Time Slot : Flexible as per Agenda available: Flexible as per aavilability
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by sagungargs15** [comment]
@iglesiasbrandon Hey Brandon thanks for considering this talk. I have just fixed more details in the initial writeup. 

I have some panelists/speakers in mind for the same (these are mostly CTO/CISOs of renowned Bitcoin only wallet companies). Carrying on from my previous conversations with them I am in the process of checking their availability and interest to share on this platform.

**Comment by sagungargs15** [comment]
@iglesiasbrandon  On a side note: I am also willing to convert this into a Solo talk to share a very detailed walkthrough of how one can go about building this in a detailed play. I have been working on this for few months now. I have drawn up a detailed Architecture walkthrough of a such a white labelled product offering.

**Comment by sagungargs15** [comment]
@iglesiasbrandon Adding reference to FOSS repo: https://github.com/sagungargs15/openvault for the work being done in this space

**Comment by sagungargs15** [comment]
@iglesiasbrandon  Sharing a little preview of technical details for this to become a talk from initially proposed panel

**Overall Architectural Approach**
<img width="741" alt="Screenshot 2024-09-22 at 1 49 41 PM" src="https://github.com/user-attachments/assets/6e52ce31-4789-4c47-acaa-4e8608981921">

**Overall Product level Offerings options for BTC Investor to get exposure** 
<img width="743" alt="Screenshot 2024-09-22 at 1 49 02 PM" src="https://github.com/user-attachments/assets/2731bafd-d507-4629-93b3-f2889c7f6088">

**Comment by sagungargs15** [comment]
@iglesiasbrandon @miketwenty1 May I please propose this to be a talk instead of a Panel. I have shared some content overview that I plan to cover in the above notes

**Comment by sagungargs15** [comment]
Architectural Nuances for Bitcoin Enterprise Custody for Institutions/Orgs (Small/Medium) on Bitcoin Standard - Self Sovereignty for “Corporate Plebs & Non-Profits"

**Comment by iglesiasbrandon** [comment]
Thank you for conducting this talk!
