### ISSUE TITLE
Simulating Lightning Scenarios using Doppler

### ISSUE THREAD

**Issue by tee8z** [TABConf/6.tabconf.com#89]
# Description
### What is this workshop about? Provide as many details as possible. 
During this workshop the attendees will setup Doppler on their machines and work through a few different lighting scenarios built out in Doppler scripts. They will be able to watch the scenarios play-out in real time via a visualizer that will be running along side the Doppler binary.  If time allows, we will also go over how to call out to the nodes running in their cluster from a python script or via the browser. The workshop's goal is to show an additional tool that can used to better understand lightning and give developers an easy way to build on top of different implementations. Currently, Doppler support eclair, coreln, and lnd with simple grammar that can work across all three to generate active in a deterministic way. 

### What would an attendee learn from this workshop?
They will learn some of the oddities of lightning while working through the different simulations and see how they can use this simulator to build their own applications in a straightforward way. 

### Is there anything attendees should read up on before they attend this talk?
It's recommend to have read over some of the examples in the Doppler repo and possible have questions ready to go on what they may want to simulate.

### Is there anything attendees should set up before the workshop?
It is recommend to have the Doppler downloaded on their machine and have successfully run some of the scripts (not required). Downloading the docker images can take a while when doing over the conference wifi which is why it is recommend to have at least run some of the scripts (which will pull the images down) before attending.

### Relevant Links
[Doppler](https://github.com/tee8z/doppler)

 
# Level of difficulty Intermediate
 
# About the Speaker
tee8z is a backend developer at voltage working on simplifying using lightning and bitcoin infrastructure. He created this tooling to help with his own needs for side projects, with a focus on creating easy to reproduce multi-implementation network setups on lightning and bitcoin.

### Social Links
Github https://github.com/tee8z
Twitter https://x.com/Tee8z
Website

# Workshop Details
### Preferred Day/Time Slot  day 2 any time
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by iglesiasbrandon** [comment]
Thank you for conducting this workshop!
