### ISSUE TITLE
Shielded CSV 🛡: Private & Efficient Client-Side Validation

### ISSUE THREAD

**Issue by jonasnick** [TABConf/6.tabconf.com#90]
# Description
### What is this talk about? Give us as many details as possible.

The client-side validation approach removes transaction verification from the consensus rules. Instead, transaction data posted to the blockchain is only interpreted on each individual node ("client-side"). This approach allows building protocols with very low on-chain size and verification cost, while providing strong privacy.

This talk proposes the client-side validation protocol "zkCSV" (working title) that, in contrast to existing client-side validation protocols, only requires 64 bytes of on-chain space regardless of the size of the transaction and is fully private. The protocol's communication cost between transaction sender and receiver is independent of the transaction history. Furthermore, zkCSV can be instantiated with existing cryptographic zk-SNARK primitives.

With a trust-minimized mechanism like BitVM2 to bridge between the blockchain and the client-side validation protocol, zkCSV adds strong privacy to Bitcoin and scales Bitcoin to 100 transactions per second. It has been described as "the most useful thing you can do with BitVM2".

Even without a bridge, zkCSV can be used to create a private cryptocurrency pegged to bitcoin (for example via the one-way peg) that offers substantial advantage over existing private cryptocurrencies. These currencies require users to validate all transactions, which contain relatively large and computationally expensive Zero-Knowledge proofs. zkCSV, however, only requires the recipient of a transaction to download the full transaction data, which results in significant reductions in computational and bandwidth costs. Furthermore, zkCSV derives its resistance to double-spending from Bitcoin, eliminating the need for its own consensus mechanism. Moreover, private cryptocurrencies are not able to hide the transaction graph better than zkCSV.

### What would an attendee learn from this talk?

- What client-side validation is and what its advantages and limitations are.
- How it is possible to achieve only 64 bytes on-chain cost using sign-to-contract and signature half-aggregation.
- How zk-SNARKs and in particular proof-carrying data schemes are applied to provide strong privacy.
- That private & efficient client-side validation is a largely unexplored framework that has a vast design space and potential for innovation, in particular for designs that allow efficient layer 2's.

### Is there anything folks should read up on before they attend this talk?
no

# About the Speaker
### Social Links
- Github: https://github.com/jonasnick
- Twitter: https://x.com/n1ckler
- Website: https://nickler.ninja

# Talk Details
### Length of Talk
20 - 30 minutes
### Preferred Day/Time Slot
none

**Comment by iglesiasbrandon** [comment]
thank you for conducting this talk!
