### ISSUE TITLE
Next Gen Village

### ISSUE THREAD

**Issue by asherp** [TABConf/6.tabconf.com#91]
## Description

The NextGen Village is a fun interactive space for bitcoiners of all ages.
Our village focuses on activities and talks that expand Bitcoin education beyond the technical, through our NextGen panels, board games, crafts, puzzles and more.
We encourage contributions that focus on sovereignty and education and are geared toward a wider audience.
In addition to the fun, this is a great opportunity to meet other bitcoiner families - it takes a village to raise the next generation of sovereign individuals!

### What is this idea? Give us as many details as possible. 

Our board games showcase contributions from SHAmory and Free Market games (HODL up, Channel Up, etc).
These games demonstrate aspects of Bitcoin in a fun and intuitive way accessible to anyone.
Take home bitcoin games, books and toys to tide you over till next year!

Our mining challenge is back! Solve our 3D Bitcoin block using using transactions from our mempool of colorful acrylic pieces and you'll receive your mining reward in sats!

Digital Logic Lecture Series - 10 year old Silas will give two more mind-blowing lectures in his continuing series on digital logic and the foundations of computer science.

Crafts:
* Learn how to design and print your own 3D models
* Design your own buttons to take home with you
* Bead projects, crochet and more!

## Community call

Are you bringing your kids? Do you have ideas for activities, games, panels or talks? Submit your ideas!

### Relevant Links

Check out last year's events in our village - it was a huge success! 
https://github.com/orgs/TABConf/projects/1/views/10

**Comment by iglesiasbrandon** [comment]
thank you for hosting this amazing village!
