### ISSUE TITLE
Running Bitcoin

### ISSUE THREAD

**Issue by EllyPembroke** [TABConf/6.tabconf.com#92]
Join us for a 5k social run down the parks and streets of Atlanta GA.

WHAT
5km easy social run for all abilities.

WHEN
Thursday, October 24th at 5pm

WHERE
Meet at TABconf check-in area

WHY
Because POW matters. We are inspired by [Hal Finney](https://twitter.com/halfin/status/1110302988?lang=en).

WHAT TO BRING
Road running shoes and workout clothes

**Comment by iglesiasbrandon** [comment]
Hey Elly, Can you open another issue for Friday and make this one specific to Thursday? That way, we can show it on the schedule better!

**Comment by iglesiasbrandon** [comment]
thank you for conducting this workshop!
