### ISSUE TITLE
Building Decentralized Web Apps

### ISSUE THREAD

**Issue by csuwildcat** [TABConf/6.tabconf.com#93]
# Description

Block recently release a v1.0 of an open source, standards-based DWeb platform for working with decentralized identities and building decentralized apps. Attendees will learn how to create and use Decentralized Identifiers (DIDs) and DWeb Node personal datastores to author decentralized protocols and build Decentralized Web Apps (DWAs).

This will be an **intermediate** level workshop segmented into the following sections:

1. Boot up on DWeb concepts
2. Creating and using Decentralized Identifiers
3. Setting up a DWeb Node personal datastore (on-device in Web, and remote as a server)
4. Building your first Decentralized Web App (DWA)

## Skills & Technologies Used:

1. General web dev skills
2. JavaScript (browser and Node)
3. Awareness of distributed systems concepts

## Prereading & Background

1. [Presentation on the DWeb Platform](https://github.com/csuwildcat/presentations/blob/06298acf9e623f0d9c087fc7060a7511768c7c80/dweb-deep-dive.pdf)
2. [Long-form explainer video](https://www.youtube.com/watch?v=JVJVsm-93K8)

# About the Speaker
Daniel leads Decentralized Identity at Block. Prior to Block, he started the Decentralized Identity program at Microsoft after spending his early career at Mozilla leading its Developer Ecosystem product group. He represents Block in the W3C and Decentralized Identity Foundation, working with members of these organizations and the wider community to make decentralized identity and apps a reality.

### Social Links
Github: @csuwildcat
Twitter: [@csuwildcat](https://x.com/csuwildcat)

# Workshop Details

### Length of workshop

1-1.5 hours

### Preferred Day/Time Slot 

Day 2, if possible

**Comment by bnonni** [comment]
@csuwildcat thanks for submitting an issue to TAB Conf 6! We are excited to have you coming to do a workshop. It is currently under consideration. If accepted, we will re-label it as such, assign a day/timeslot and ping you here.

In the interm, we labeled this workshop as part of our "intermediate" track. This label is meant to describe the skill level required of the attendee to be able to successfully follow along. Please let us know if you think this is accurate. If not, let us know if it should be Advanced or Beginner, and we will change it.

**Comment by bnonni** [comment]
@csuwildcat we've officially accepted your workshop! You've been assigned to Workshop Day 2 at 1:00 to 2:30 pm in Workshop Room 2. Feel free to checkout the schedule on our project board: https://github.com/orgs/TABConf/projects/4/views/4
