### ISSUE TITLE
Codex32 hand-computed SSSS/Checksums Workshop

### ISSUE THREAD

**Issue by apoelstra** [TABConf/6.tabconf.com#95]
# Description
### What is this workshop about? Provide as many details as possible. 

This workshop aims to provide an introduction to algorithms which can be done by non-experts without electronics computers in a reasonable amount of time. In particular, our goal will be to cut out and assemble a paper computer, and then with the assistance of worksheets, validate the checksum on a bech32 address.

### What would an attendee learn from this workshop?

That it is possible to verify checksums by hand; and that by straightforward but tedious extensions of this idea, it is possible to generate checksums, split and recover data using Shamir's Secret Sharing Scheme, and maybe some unrelated patter about random number generation.

### Is there anything attendees should read up on before they attend this talk?

I have a [Youtube talk about this project here](https://www.youtube.com/watch?v=kf48oPoiHX0&list=PLyOGyBytgcuQLi9DC5g88DOEGnqBDPmq1&index=3). See also the main [codex32 website](https://secretcodex32.com).

None of this is essential reading.

### Is there anything attendees should set up before the workshop?

They may want to download the full [codex32 booklet](https://secretcodex32.com) and print out/assemble the addition volvelle (page 21/22). It is best to print it on cardstock. We will provide printouts and time to do assembly, but it takes 20-30 minutes and will not teach you anything you didn't learn as a child.

# Level of difficulty 

Intermediate. Nothing is technically hard or requiring prerequisites but it's frustrating and tedious work.

# About the Speaker
### Social Links
Github https://github.com/apoelstra
Website https://www.wpsoftware.net/andrew

# Workshop Details
### Length of workshop

I can work with anything from 1-3 hours. Will likely need close to 2 hours to complete a short presentation and the main task, depending on participant speed. But I have hundreds of hours of related tasks if somehow people run out of time.

### Preferred Day/Time Slot 

Any is good.

**Comment by iglesiasbrandon** [comment]
thank you for conducting this workshop!
