### ISSUE TITLE
Running Bitcoin

### ISSUE THREAD

**Issue by EllyPembroke** [TABConf/6.tabconf.com#97]
Join us for a 5k social run down the parks and streets of Atlanta GA.

WHAT
5km easy social run for all abilities.

WHEN
Friday, October 25th at 5pm

WHERE
Meet at TABconf check-in area

WHY
Because POW matters. We are inspired by [Hal Finney](https://twitter.com/halfin/status/1110302988?lang=en).

WHAT TO BRING
Road running shoes and workout clothes

**Comment by vnprc** [comment]
I can't run but I can cruise along on my board. 🤙

**Comment by vnprc** [comment]
I can't run but I can cruise along on my board. 🤙

**Comment by johnny9** [comment]
Here is the marked route around the campus. https://strava.app.link/UuXAt2s1XNb —  Pi mile

**Comment by iglesiasbrandon** [comment]
i hope yall had a good run!
