### ISSUE TITLE
Supercharging Transactions with Async Payjoin

### ISSUE THREAD

**Issue by thebrandonlucas** [TABConf/6.tabconf.com#98]
# Description
### What is this talk about? Give us as many details as possible. 

Level: **Beginner**

Payjoin is a simple, flexible, and powerful protocol for a sender and receiver to collaboratively construct Bitcoin transactions. This allows for many optimizations, such as fee savings and scaling via [batching](https://payjoin.org/docs/why-payjoin/scaling), opportunistic [UTXO consolidation](https://bitcoin.stackexchange.com/questions/103194/confused-about-utxo-management-and-consolidation), and [transaction cut-through](https://payjoin.org/docs/why-payjoin/scaling#transaction-cut-through), as well as better privacy by breaking [privacy-thieving heuristics](https://payjoin.org/docs/how-it-works/payjoin-v1-bip-78/#motivation), solving the sole privacy problem [left open in the whitepaper](https://nakamotoinstitute.org/library/bitcoin/#privacy). Payjoin *enhances transactions* without requiring any changes to Bitcoin. The magnitude of these positive effects scale with usage — the more transactions that are Payjoins, the more fee savings, blockchain throughput, and privacy for everyone.

The first version of Payjoin ([BIP-78](https://github.com/bitcoin/bips/blob/master/bip-0078.mediawiki)) required the receiver to run an always-online server secured by TLS or a TOR hidden service, which proved to be a [barrier to adoption](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-January/018358.html).

*Asynchronous Payjoin*, aka Serverless Payjoin, Payjoin Version 2, or Draft [BIP-77](https://github.com/bitcoin/bips/pull/1483), outsources this problem by delegating the coordination to an untrusted third party, while also taking measures to further improve privacy and improve UX by integrating novel protocols [Oblivious HTTP](https://blog.cloudflare.com/stronger-than-a-promise-proving-oblivious-http-privacy-properties/) and [HPKE](https://blog.cloudflare.com/hybrid-public-key-encryption).

A Rust library for developing with Payjoin, [PDK](https://payjoindevkit.org/), is under active development and is rapidly iterating.

Given the recent [attacks](https://www.justice.gov/usao-sdny/pr/founders-and-ceo-cryptocurrency-mixing-service-arrested-and-charged-money-laundering) on Bitcoin privacy, the use of censorship-resistant and privacy-by-default tools are more important than ever. The time and fee savings individuals and companies can accrue serve as an additional incentive to achieve improved privacy for the whole network.

Payjoin adoption is relatively [low](https://en.bitcoin.it/wiki/PayJoin_adoption) as of today. This talk seeks to shed light on Asynchronous Payjoin as a viable low-interaction protocol for optimizing privacy, efficiency, and fee savings in Bitcoin transactions.

This talk will cover:
- Brief history of ideas relating to Payjoin (Coinjoin, P2EP, etc.)
- Brief overview of how V1 works and barriers to adoption
- Benefits of Payjoin
	- Batching
	- Transaction cut-through
	- UTXO consolidation
	- Privacy
- Overview of Asynchronous Payjoin (BIP-77)
	- UX and Privacy Improvements
	- Outsourcing communication to untrusted Payjoin Directories
	- Oblivious HTTP
	- HPKE
	- Limitations
- Demonstration with reference implementation [`payjoin-cli`](https://github.com/payjoin/rust-payjoin/tree/master/payjoin-cli)
- Possible Use Cases, such as better batching for exchanges and Lightning cut-through

### What would an attendee learn from this talk?

- How can Payjoin save money?
- How does Payjoin improve privacy?
- Payjoin has been around for a few years. Why hasn't it seen much adoption?
- Why would exchanges integrate Payjoin?
- Why would wallet developers integrate Payjoin?
- How does Asynchronous Payjoin improve over BIP-78?
- How to do an Async Payjoin on Bitcoin Core

### Is there anything folks should read up on before they attend this talk?

This talk is for anyone who is interested in Payjoin and assumes no prior knowledge. That said, here are some links that can help shed light on Payjoin prior to attending:

- [payjoin.org](https://payjoin.org)
- [Payjoin V2](https://payjoin.org/docs/how-it-works/payjoin-v2-bip-77)
- [How Can Payjoin Save 16% on Transaction Fees?](https://payjoin.org/docs/how-payjoin-saves)
- [Payjoin for a Better Bitcoin Future](https://blu.cx/payjoin-for-a-better-bitcoin-future/)

# About the Speaker

Brandon Lucas is a frontend engineer at [Voltage](https://voltage.cloud), working on Payjoin and other open source Bitcoin projects in his spare time. See more of his work at [blu.cx](https://blu.cx).
### Social Links

Website: [blu.cx](https://blu.cx)
Github: [thebrandonlucas](https://github.com/thebrandonlucas)
Twitter: [brandonstlucas](https://x.com/brandonstlucas?ref=blu.cx)
Nostr: [blu@vlt.ge](https://primal.net/p/npub18agram6s6kulwwhc638d8q8y5vysutrrvvdll2wdjxd75wp4dfjqshytrf?ref=blu.cx)

# Talk Details
### Length of Talk

45 - 60 mins

### Preferred Day/Time Slot 

Preferably late morning, mid-day, or early afternoon, but will gladly give the talk anywhere it will fit in :)

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by iglesiasbrandon** [comment]
Hey @thebrandonlucas this talk has been accepted! 

Would you say this is beginner, intermediate or advance talk?

We are collecting an additional attribute for the workshops. Please update your issue and include a line item on the difficulty level of the workshop with either "Beginner", "Intermediate", or "Advanced".

- Beginner: would be no prior knowledge needed, very few technical skills required for workshop
- Intermediate: At least some knowledge needed to not be lost, technical skills, Comp Sci, IT related experience is greatly beneficial
- Advanced: Potentially a strong working knowledge of certain technologies, libraries, fundamentals, Comp Sci, and related protocols.

Error on the side of more advanced than less advanced as we want to set strong expectations. Depending on what you pick please gauge your workshop accordingly.

**Comment by thebrandonlucas** [comment]
@iglesiasbrandon Amazing! This is definitely meant as a beginner talk. Updated the issue to reflect that.

Thank you!

**Comment by iglesiasbrandon** [comment]
thank you for hosting this talk!
