### ISSUE TITLE
Writing smart contracts in Rust using Simfony workshop

### ISSUE THREAD

**Issue by uncomputable** [TABConf/6.tabconf.com#99]
# Description
### What is this workshop about? Provide as many details as possible. 
This workshop introduces Simfony, a language that looks and feels like Rust that lets you write Bitcoin smart contracts. We will explore how existing contracts written in Bitcoin Script are represented in Rust syntax. We will play around with a web IDE that lets you write Simfony programs. We will use the web IDE to make a Simfony transaction on Liquid testnet.

### What would an attendee learn from this workshop?
The main takeaway of this workshop is that smart contracts can be written in Rust syntax, which is arguably more elegant than Bitcoin Script or Solidity. The workshop aims to give attendees a clear understanding of what Simfony offers. By the end of the workshop, attendees will be able to make Simfony transactions on Liquid testnet.

### Is there anything attendees should read up on before they attend this talk?
Feel free to explore the [Simfony web IDE](https://simfony.dev/) to get a head start. There is a [manual on how to make a transaction on Liquid testnet](https://github.com/uncomputable/simfony-webide/blob/8ff8a993aa62b59f9ad75a887e32e6f7f896337a/doc/README.md).

### Is there anything attendees should set up before the workshop?
The entire workshop will run in the browser. Ideally bring a laptop.

### Relevant Links

[Simfony web IDE](https://simfony.dev)

[Manual how to make a transaction on Liquid testnet](https://github.com/uncomputable/simfony-webide/blob/8ff8a993aa62b59f9ad75a887e32e6f7f896337a/doc/README.md)

[Documentation of Simfony jets](https://docs.rs/simfony-as-rust/latest/simfony_as_rust/jet/index.html)

[Simfony web IDE repo](https://github.com/uncomputable/simfony-webide)

[Simfony compiler repo](https://github.com/BlockstreamResearch/simfony)

# Level of difficulty 
Advanced. Simfony is Rust without the hard parts  _(no ownership, no lifetimes, ...)_, so Simfony should be significantly easier to learn than Rust. That said, the Simfony tooling is immature and there are bound to be some rough edges in the UX. For instance, the Simfony wallet runs on the command line.  Attendees should understand the UTXO model and roughly how Bitcoin smart contracts work. Attendees should be proficient in _a_ programming language, which doesn't have to be Rust.

# About the Speaker
### Social Links
Github: https://github.com/uncomputable
Twitter: https://twitter.com/uncomputab1e
Website

# Workshop Details
### Length of workshop
The introduction and main part of the workshop will take roughly 2 hours. We can go for an additional hour depending on how people are engaged.

### Preferred Day/Time Slot 
Any time works.

**Comment by iglesiasbrandon** [comment]
@uncomputable Will this be available in liquid for the workshop?

**Comment by uncomputable** [comment]
Simplicity / Simfony will run on Liquid testnet for the workshop. Liquid mainnet will not have support because we want to thoroughly test Simplicity / Simfony on Liquid testnet first.

**Comment by uncomputable** [comment]
@iglesiasbrandon Will my workshop be added to the schedule? I couldn't find it.

**Comment by iglesiasbrandon** [comment]
hey @uncomputable yes it already is: you can see it here: https://github.com/orgs/TABConf/projects/4/views/4

**Comment by uncomputable** [comment]
I can see it now; thanks.

**Comment by mvuk** [comment]
Hello @uncomputable , I am interested to attend and participate in this workshop. Can you please elaborate any further resources about "how Bitcoin smart contracts work" that I should review and prepare for before the day of the event? I am currently looking through the Simfony example programs and web IDE. Thank you.

**Comment by uncomputable** [comment]
Good question!

You should be familiar with UTXOs, locking scripts and witness data. That is already more than most people know. [learnmeabitcoin](https://learnmeabitcoin.com/technical/script/) is a good resource for brushing up on these things.

Apart from that, you can do a lot to increase your understanding. You can look into common script types, such as P2PK, P2PKH, P2MS and so on. You can look into how absolute and relative lock times work, which confused me for a long time. I'm not sure if there is a good resource on how covenants work. [Bitcoin Optech](https://bitcoinops.org/en/topics/covenants/) might be the best. All of this is optional and it's about how to write scripts for specific use cases. Bitcoin Script is a tool and it has to be used in a particular way. Simfony / Simplicity is similar in this regard.

We will most likely use [the P2MS contract](https://github.com/BlockstreamResearch/simfony/blob/67eabe5e6e39fb566d269eee1b54fbbb2ac963dd/examples/p2ms.simf) for the workshop at TabConf. Take a look at the program and see if it makes sense to you. The program manually implements `OP_CHECKSIGADD` from [BIP 342](https://github.com/bitcoin/bips/blob/master/bip-0342.mediawiki).

**Comment by Impa10r** [comment]
Any chance to attend/view by telecommute?

**Comment by iglesiasbrandon** [comment]
@Impa10r no, TABConf is an in-person conference.

**Comment by uncomputable** [comment]
@Impa10r The great thing about my workshop is that most of the action happens on [a public website](https://simfony.dev). You can repeat the steps from the comfort of your home :) I will write up documentation after the workshop to enable everyone to make Simfony transactions on Liquid testnet.

**Comment by Impa10r** [comment]
@uncomputable What's the Simfony wallet that I can compile with Rust?

**Comment by uncomputable** [comment]
I will integrate transaction functionality into the web IDE. Right now, I am fighting with some WASM issues :)

For now, [the Simfony integration tests](https://github.com/BlockstreamResearch/simfony/blob/2d5e1b159374531ff7989ef43473922e7e644f05/bitcoind-tests/tests/common/test.rs) are the best "documentation" that we have. The tests go through the entire process of creating and spending a Simfony UTXO on Elements regtest.

**Comment by iglesiasbrandon** [comment]
thank you for conducting this workshop!
